### ISSUE TITLE
The table on the spec page squishes the leftmost column too much

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#10]
https://www.ampproject.org/docs/reference/spec.html

<img width="730" alt="screen shot 2016-01-14 at 3 41 16 pm" src="https://cloud.githubusercontent.com/assets/3888212/12341271/469e2574-bad5-11e5-8977-7cc81c47eac7.png">

**Comment by pbakaus** [comment]
This has been fixed by @Meggin. Thanks Meggin!
