### ISSUE TITLE
Document HTTPS requirements

### ISSUE THREAD

**Issue by jmadler** [ampproject/docs#101]
It can be difficult to understand which parts of AMP HTML require HTTPS and which are optional.  

I'm not sure exactly where or how, but I think there's an opportunity to clarify HTTPS requirements and link to relevant pages to improve discoverability of this information.

Examples include this page: https://www.ampproject.org/docs/guides/third_party_components.html

**Comment by bpaduch** [comment]
Todo: Make sure each component spells out the required protocol, if the need or use it. (e.g., amp-pixel requires https protocol).
