### ISSUE TITLE
AMP search page.

### ISSUE THREAD

**Issue by hemanth** [ampproject/docs#102]
It would be great to have a place where I can search all the AMP components, I am more than happy to do a PR ;) [Reference](https://github.com/ampproject/amphtml/issues/3267#issuecomment-221067325)

**Comment by pbakaus** [comment]
Great thanks for opening the ticket :) Go for it, looking forward to see what you come up with.

**Comment by pbakaus** [comment]
You still on this, @hemanth ?

**Comment by hemanth** [comment]
@pbakaus Yes. Sorry I got held up with too many personal challenges. 

//cc @shidhincr helping hand?

**Comment by shidhincr** [comment]
@hemanth @pbakaus I'm in for this. 

Let's discuss how we should go forward

**Comment by pbakaus** [comment]
I think in order to do this, we'd need some amp-filter compontent to be able to build a search like that. Any thoughts, @cramforce?

**Comment by cramforce** [comment]
Probably not high on the list.
@rudygalfi

**Comment by pbakaus** [comment]
I'll close this for now, as I don't see how we could make this feasible at this point. Sorry!

**Comment by hemanth** [comment]
NP, sorry couldn't contribute to this, yet.

**Comment by dandv** [comment]
We need a general search throughout https://www.ampproject.org/. Even a dumb Google site search would do - a text input submitting to `https://www.google.com/search?q=<query>+site%3Ahttps%3A%2F%2Fwww.ampproject.org`
