### ISSUE TITLE
Builds are failing due to flakiness

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#1025]
Since going to a parallel build, builds often fail for different reasons that seem to be flakiness, requiring a manual restart of the parallel build job, then a redeploy.  This isn't scalable and requires too much intervention.  

Why is the flakiness happening?  VMs?

Common errors that break build:

## Command failed
[Sample job 2053.2](https://travis-ci.org/ampproject/docs/jobs/402497739)
```
04:00:47] Error: Command failed: cd ./scripts && ./import_docs.js
/home/travis/build/ampproject/docs/scripts/import_docs.js:211
      for (var i = 0; i < data.length; i++) {
                               ^
TypeError: Cannot read property 'length' of undefined
```
Reason:? 
Resolution: restart build

## Exited with 1
[Sample job 2054.3](https://travis-ci.org/ampproject/docs/jobs/402950256)

```
The command "./build_scripts/build.sh it ko pt_BR" exited with 1.
```

Reason: ?
Resolution: Restart build

## Error 500
```
[17:56:29] Error: Command failed: cd ./scripts && ./import_docs.js
/home/travis/build/ampproject/docs/scripts/import_docs.js:32
      throw err;
      ^
Error: Error 500
```

**Comment by pbakaus** [comment]
I've fixed this particular issue.
