### ISSUE TITLE
Clean up docs to include ability for inline styles (not restricted anymore)

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#1027]
In reference to https://github.com/ampproject/docs/pull/1019 and https://github.com/ampproject/amphtml/issues/14072, make sure references to styling isn't exclusive to just using the single inline stylesheet, now users can use inline styles.

Docs to check:

- Tutorials
- Style guides

**Comment by CrystalFaith** [comment]
Also added changes in [pull request #17226](https://github.com/ampproject/amphtml/pull/17226) for documentation in amphtml. I wasn't able to assign a reviewer.
