### ISSUE TITLE
Add browser support table

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#103]
I thought we had this, but can't find it.

Our policy is: Latest 2 of major mobile and desktop browsers. Best effort for older versions.

**Comment by pbakaus** [comment]
Added/fixed with next deploy.

**Comment by lucasvazq** [comment]
2020 , its says "In general we support the latest two versions of major browsers"

**Comment by matthiasrohmer** [comment]
@lucasvazq, browser support is documented in the FAQ: https://amp.dev/support/faq/supported-browsers/

**Comment by lucasvazq** [comment]
@matthiasrohmer 

After four years, only details the compatibility in "we support the latest two versions of major browsers". A much broader compatibility detail is needed.
A table for each element and version of AMP components showing compatibility with different browsers.
I work on a page where all mobile device users are redirected to the AMP site, but not all browsers can properly process it.
I would need to filter on the user agents that I want to redirect or not to my amp site.
A company client where I'm work says "the carousel is not visible from Instagram browser". How can I know which browser/version the client is using when it hits the site from Instagram? How many users will that client have that do not warn that the site is not working for them and leave the page directly?

Imagine a table where it tells that the minimum version of Edge for the carousel v2 is "X", and that the minimum version of Chrome for amp-img is "Y". Then, if I use those two elements, with that info I can make an intersection of the sets of the compatibility of my elements and end up with a select group of browsers that I know are working on my site properly, and redirect the rest to a normal site.

Even if, if the company where I work, would dedicate all the effort and resources necessary to put together an internal compatibility table, it would not give us any benefit that compensates all expenses, and under this approach, if all companies made internal compatibility tables everyone would spend a lot of resources and nothing more than the big companies would end up getting some real benefit. Let's not even talk about independent developers.
You who work on the AMP project are primarily responsible for providing specific compatibility information. As developers, if we do not have the right information, not only becomes frustrated, but we also do mediocre jobs for our clients and for the company where we work and it is the final users who end up suffering the real consequences.

**Comment by sebastianbenz** [comment]
@lucasvazq thanks for adding more detail to this discussion. I think "we support the latest two versions of major browsers" is a clear statement. This applies to all components. Hence, there shouldn't be a need for a detailed break down per component. 

The important thing is: if you find a component not working in any of the major browsers then it's a bug in AMP. Please file these [here](https://github.com/ampproject/amphtml/issues/new/choose).
