### ISSUE TITLE
Document AMP's mission & vision

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#1038]
Find a place to document the vision of mission of AMP prominently on our website. As a reminder, AMP's:

- Vision: A strong, user-first open web forever.
- Mission: Provide a user-first format for web content, supporting the long-term success of every web publisher, merchant, and advertiser.

**Comment by mrjoro** [comment]
For reference, these were shared at AMP Conf 2018 in the [What's next in AMP talk](https://www.youtube.com/watch?v=HyVzwlnAIVk&feature=youtu.be&t=2m18s).

**Comment by pbakaus** [comment]
Completed: https://www.ampproject.org/about/mission/
