### ISSUE TITLE
AMP Roadmap doesn't seem to be updating once a day

### ISSUE THREAD

**Issue by jasti** [ampproject/docs#1044]
A few of us made some changes to the GH roadmap project which aren't yet reflecting in https://www.ampproject.org/roadmap. Is the roadmap supposed to update once a day?

**Comment by pbakaus** [comment]
I've manually updated yesterday, but still don't know why changes don't get picked up automagically every day, so leaving this bug open.

**Comment by pbakaus** [comment]
Should be fixed.
