### ISSUE TITLE
Ignore Markdown text from descriptions when sourcing description from the GH issues

### ISSUE THREAD

**Issue by jasti** [ampproject/docs#1045]
Markdown headers appear a bit off when sourcing them as is. If possible, we should ignore the Markdown on ampproject.org/roadmap

**Comment by pbakaus** [comment]
Sadly ignoring the markdown would ignore things like bold text, which would also look weird. So stripping out the markdown altogether is not a small problem.

**Comment by jasti** [comment]
Between the two, I'd pick having a consistent UX. Having bold text show is a P2. Any others you are thinking of?
As a temporary solution, we could tell everyone creating these not to add Markdown in the first comment but would be good to future proof it.
