### ISSUE TITLE
Add new vendor for amp-analytics

### ISSUE THREAD

**Issue by henryh15** [ampproject/docs#1058]
## Description of the issue

- Page link: https://www.ampproject.org/docs/analytics/analytics-vendors
- Description: [Mobify was recently added in as an analytics vendor](https://github.com/ampproject/amphtml/pull/12414) but is missing from the list of supported vendors.

We'd like to add an entry for Mobify as the following:

Mobify
Type attribute value: mobify

Adds support for Mobify. More details for adding Mobify support can be found at [docs.mobify.com](https://docs.mobify.com/amp-sdk/latest/guides/amp-analytics/) .

**Comment by bpaduch** [comment]
@henryh15 - Hi, as part of the [process for integrating your analytics platform into the code base](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md#adding-your-configuration-to-the-amp-html-runtime), you'll need to submit a PR to this repo to add your analytics type to the analytics vendors list (like this [PR](https://github.com/ampproject/docs/pull/742).
