### ISSUE TITLE
Better link target for the amp-boilerplate code on ampproject.org.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/docs#107]
Hi, currently, the Validator error messages concerning the amp-boilerplate code point at https://www.ampproject.org/docs/reference/spec.html#required-markup. Today I'm pointing these to https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md, reason being it's more convenient and should reduce some confusion. I think ideally, ampproject.org should have a section or page that includes the boilerplate and the explanation there directly, especially if / when we plan to translate this to other languages. The boilerplate should be stable enough by now so it can be copied, no need to link to Github.
If this is possible, then please ping us validator folks once such a link target on ampproject.org exists. Many thanks!

**Comment by pbakaus** [comment]
@Meggin can you take a stab at this?

**Comment by pbakaus** [comment]
Sorry for the delay! Here you go: https://www.ampproject.org/docs/reference/spec/amp-boilerplate
