### ISSUE TITLE
Improve Story Ads documentation

### ISSUE THREAD

**Issue by jasti** [ampproject/docs#1071]
We have some current documentation for Story ads but they are mostly buried in  the first link below:
- GH Story ads https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-ads.md
- AMP By Example documentation: https://ampbyexample.com/stories/monetization/doubleclick/
- Doubleclick documentation - https://support.google.com/dfp_premium/answer/9038178

Can we create a developer and ad operations facing friendly guide (in addition to making our existing documentation clearer) that explains the creation, delivery and integration aspects in a friendlier manner? Some questions we should ensure as part of the guide are: 

- What are the image specs for single page ads?
- Do the images have to be responsive? 
- How should I setup story ads in my ad server? 
- is the thing I'm responding back from my ad server a single page of a story or an AMPHTML ad? 
- What is an AMPHTML ad, I've never heard of it.
- Does the system have an overlay? How should I build my creative so as to not block any of these system overlays? 
- What are the CTA options - how they look visually?
- How can I add a new CTA? 
- I am an ad server and I am interested in serving story ads? How can I integrate? 
- Can you show me some samples? 
- I'd like to use a story as the landing page for my single page ad? What are the best practices to do so?
- When should I choose publisher served ads vs ad server served ads? 
- Is there a step by step tutorial to show me how I can build a high quality single page story ad? 
- How to pass along ad network specific data attributes as part of the story-auto-ads tag. 
- How to add advertiser tracking pixels.

**Comment by ithinkihaveacat** [comment]
An "overview" question:

- What are the different ways of generating the [AMP Story CTA Layer](https://www.ampproject.org/docs/reference/components/amp-story#amp-story-cta-layer) UX?
  - **Use amp-story-cta-layer element** — create normal AMP page, add [amp-story-cta-layer](https://www.ampproject.org/docs/reference/components/amp-story#amp-story-cta-layer) element to create outlink (super simple)
  - **Embed ad template** — embed Mustache "ad template" in page, pull data from publisher's server via [amp-story-auto-ads](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-auto-ads.md), runtime dynamically creates ads from JSON endpoint (publisher operates own simple ad server)
  - **[Direct sold, DFP-served AMP4ADS](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md)** — much more control, can use all features of AMP4ADS (though outlinks are neutered?)

Omissions:

- [amp-story.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md) does not mention amp-story-auto-ads
- [Introduction to advertising on AMP](https://www.ampproject.org/docs/ads/introduction_ads) does not mention AMP Story (and how the ad situation is different)

Questions:

- In what format is a [Sponsored story ad](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-ads.md#sponsored-story-ad)? It's just an AMP Story with a CTA on every page? Is this enforced?

**Comment by pbakaus** [comment]
@jasti is all of this sufficiently covered in https://www.ampproject.org/docs/ads/advertise_amp_stories? If that's the case, I'll close the issue. Thanks!

**Comment by jasti** [comment]
We are looking good here. Thanks so much to @CrystalFaith, @calebcordry and you!
