### ISSUE TITLE
Failed to build and run

### ISSUE THREAD

**Issue by vtiwari06** [ampproject/docs#1092]
##  The following tasks did not complete: sass
[18:00:45] Did you forget to signal async completion?

Please provide:

Try to do grow build

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. yarn
2. grow build

What browser are you using? - Chrome
What O/S are you using? - MacOs

**Comment by bpaduch** [comment]
Make sure you are using:

- The latest LTS version of Node
- The latest version of grow
- The latest version of yarn

Consider a clean install, that is removing your node_modules directory (`rm -rf node_modules/`), and [reinstalling the above-mentioned tools](https://github.com/ampproject/docs#install).
