### ISSUE TITLE
Validation issue for reference amp-video page.

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#110]
Page: https://www.ampproject.org/docs/reference/amp-video.html

Error:
validator.js:366 https://www.ampproject.org/docs/reference/amp-video.html:2606:18 The parent tag of tag 'amp-video > source' is 'p', but it can only be 'amp-video'. (see https://www.ampproject.org/docs/reference/amp-video.html)

Line 2606:
`<p>Required if no <source /> children are present. Must be HTTPS.</p>`

Should be:
`<p>Required if no &lt;source /&gt; children are present. Must be HTTPS.</p>`

**Comment by honeybadgerdontcare** [comment]
This is now fixed in ampproject/amphtml via https://github.com/ampproject/amphtml/pull/3417. Just needs to be pulled to ampproject.org.

**Comment by pbakaus** [comment]
Thanks! Fixed.
