### ISSUE TITLE
KO translations of AMP Project docs

### ISSUE THREAD

**Issue by techhtml** [ampproject/docs#1115]
I and some Korean volunteers planning to translate all of the documents into Korean.
This issues (I used this for documentation) will be helping someone has started translations.
@captain-lee helps this.

We have some points that need discussion.

**1. How to manage KO translations.**
Because the original one is always updated, but the translation is not updated, it is the wrong context.
We need some translation rules.

**2. Google's Official translations.**
Sometimes the translation is overriding with Google's official translations.
But Its quality is not excellent, and We will need better translations.

**3. Terms and keywords**
We need a constant term for Korean docs.
For examples, the term `Tutorial` can translate "자습서" or "튜토리얼".

Maybe someone wants to translate "자습서", but someone wants to translate "튜토리얼".
So if we create our translation, We need to create some glossary for translations.

If have any idea about translations.
Please comment on this issues.

**Comment by techhtml** [comment]
@captain-lee This issues creating for translations.
If you know volunteers GitHub id, please tag him or her.

**Comment by captain-lee** [comment]
This sounds good to me. I have one person who volunteered to contribute Korean translation, but I don't know his Github id yet. I will add him once I know his id.

**Comment by techhtml** [comment]
Thank you @captain-lee! I already share this document with other Korean developers who interested in AMP Project and Felix shin also included that :)

**Comment by JeongminFelixShin** [comment]
Hi. This is Felix Shin(신정민), I met captain-lee on GDG Korea seminar. How could I contribute to AMP Project? I already joined AMP Slack. Translation process LGTM!

**Comment by techhtml** [comment]
Hi Felix. You can contribute all of documentations in AMP Project.

Here is contribution process
1. Fork the docs repository
2. Pick a issues that you want contribution
2.1. If you want translate something, that is no issues
3. (In translation) Adding ‘@ko’ with filename, and you translate that content
4. Commit, Push, and PR
5. Reviewing (just adding me)
6. end

If you need more question, contact me in the slack. My slack account is techhtml

**Comment by techhtml** [comment]
Crystal and some KO translators having a meeting for improving translation experience in AMP.
I create some issues for better translation experience.

#1146 
#1147 
#1148

**Comment by CrystalFaith** [comment]
With the new instructions and guidance on [TRANSLATIONS.md](https://github.com/ampproject/docs/blob/master/TRANSLATIONS.md), the new KO label and Slack channel I think we can migrate conversation off of this issue on onto another platform. Closing this issue. Thanks again!
