### ISSUE TITLE
Broken "Next" button in AMP Story docs (404 error)

### ISSUE THREAD

**Issue by alankent** [ampproject/docs#1124]
(Rob Dobson pointed this one out.)

The NEXT button on a page is broken in docs for AMP Story. To repeat, go to https://www.ampproject.org/docs/getting_started/visual_story/parts_of_story then click on the big blue "NEXT" button in the bottom right corner of the page. The link goes to https://www.ampproject.org/docs/design/visual_story/start_story.html but the site comes up with a 404 error (page not found).

**Comment by CrystalFaith** [comment]
Thanks for pointing this out!
