### ISSUE TITLE
Document <amp-story-consent>

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1130]
It's documented [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#prompt-ui-for-stories), but I don't think it's documented on ampproject.org.

cc: @newmuis, @gmajoulet

**Comment by pbakaus** [comment]
It's documented, probably just wasn't updated recently. Just confirmed the same is in the deployed article :)
