### ISSUE TITLE
Pages use invalid `word-break:break-word` CSS

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/docs#114]
E.g. https://www.ampproject.org/docs/get_started/about-amp.html

It looks like `break-word` is not a valid value for `word-break`. In particular we got reports that these wrapping looks broken in Firefox.

**Comment by pbakaus** [comment]
break-word is a non-standard value needed for WebKit (see https://css-tricks.com/almanac/properties/w/word-break/). It's well documented in our Sass, and I just checked Firefox – all looks fine.

Closing for now, reopen if you think there's still an issue. Thanks!
