### ISSUE TITLE
[localization] Tracking Ko translations

### ISSUE THREAD

**Issue by techhtml** [ampproject/docs#1148]
Does anyone translating AMP documents into Korean?
Please create an new Issue and connect that issue in this issue.

**Comment by JeongminFelixShin** [comment]
#1168

**Comment by pbakaus** [comment]
We'd prefer not to create tracking issues for indeterminate projects that can never be completed. We have created a project though for "Localization", which is a better place to put it. We've also created labels for languages. Hope that works!
