### ISSUE TITLE
Broken link in AMP "Supported CSS" page

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/docs#116]
Hi all,

On the AMP project [Supported CSS page](https://www.ampproject.org/docs/guides/responsive/style_pages.html), the writeup links to the AMP project's own `head.html` Jekyll include file as an example for the tutorial. The link is broken.

The link URL: https://github.com/ampproject/docs/blob/master/_includes/head.html

The correct URL: https://github.com/ampproject/docs/blob/master/_jekyll/includes/head.html

As you can see, _jekyll has been added to the path in the Github repo. There may be other links to the site's includes that are broken for the same reason.

Note also that last week @Gregable reported (#109) another broken link on the same AMP project page. That link is different, goes to another AMP project page, not the repo. That link looks like it might now be editorially obsolete, by which I mean that it isn't necessary in the context of your tutorial, and the material it links to may no longer exist because of changes to the docs and site. (And to be clear, that link is still broken. I suggest just deleting it.)

Cheers,

Joe

**Comment by pbakaus** [comment]
Fixed with the next deploy. Thanks for the report, and sorry it took so long!
