### ISSUE TITLE
[ko-translation] the small part of ampproject benefit page

### ISSUE THREAD

**Issue by JeongminFelixShin** [ampproject/docs#1169]
1. the page url to translate :https://www.ampproject.org/ko/about/benefits/

2. some parts which has not translated in Korean(3 of 6parts)

3. how many times do I need : about 1 hour

Please check ko-translation.
Thank you in advance

**Comment by JeongminFelixShin** [comment]
#1168

**Comment by JeongminFelixShin** [comment]
#1168

**Comment by pbakaus** [comment]
Thanks! Seems we can close this one..
