### ISSUE TITLE
Can not close the cookie user consent overlay

### ISSUE THREAD

**Issue by aghassemi** [ampproject/docs#1196]
When picking a language such as Italian, the user cookie consent overlay shows up but clicking on the button or close icon does not do anything and leaves it still open

**Comment by pbakaus** [comment]
@morsssss can you take a look? this seems bad..

**Comment by pbakaus** [comment]
@aghassemi I've tried this recently in Germany and the cookie consent went away normally. Can you still repro?

**Comment by pbakaus** [comment]
Closing this to inactivity. Please reopen if still happening. Thanks!
