### ISSUE TITLE
ampproject.org documentation does weird highlighting of punctuation like ":"

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#12]
See screenshot. Would prefer if this just rendered like normal code text.

<img width="743" alt="screen shot 2016-01-14 at 3 43 17 pm" src="https://cloud.githubusercontent.com/assets/3888212/12341333/c160bf06-bad5-11e5-8389-f899b7cb1be3.png">

**Comment by pbakaus** [comment]
This is fixed with the next deploy!
