### ISSUE TITLE
How often are pages on ampproject.org/docs rebuilt?

### ISSUE THREAD

**Issue by calvinfo** [ampproject/docs#121]
Hey AMP team. 

We're wondering how often the pages on ampproject.org/docs get rebuilt? We recently added a Segment integration that we'd love to link to as part of an upcoming blog post, but it looks like the documentation won't reflect it until it re-pull the updates to the metadata and extensions. I was wondering what it would take to get the pages rebuilt with the new release. Thanks! :)

**Comment by cramforce** [comment]
CC @pbakaus @Meggin

**Comment by pbakaus** [comment]
We currently do it on a manual schedule, which we should really change. When do you need it? We have an update going out tomorrow.

**Comment by Meggin** [comment]
We should be doing this weekly, and I set aside time with great intentions
in my calendar each Friday to do this. But I haven't stuck with it. And I
feel bad about that. Time has been squished. Paul-- are you doing a push
tomorrow, or do you need me to do it?

**Comment by pbakaus** [comment]
I think Erwin is on it.

**Comment by calvinfo** [comment]
Thanks! Looking forward to it :)

**Comment by calvinfo** [comment]
We just put up a [blog post][blog] and [docs][docs] as well announcing our support for it! 

We'd love to be able to link to the main docs page listing Segment as a vendor from it!

If there's anything that doesn't seem right, definitely shoot me an email (calvin at segment) and we can help fix it on our side. I'm incredibly excited to help the project!

[blog]: https://segment.com/blog/support-for-amp/
[docs]: https://segment.com/docs/libraries/amp/

**Comment by erwinmombay** [comment]
i can add a weekly job to pull in the docs, unfortunately i know right now we are in a bad state with the script that pulls in the docs.

**Comment by calvinfo** [comment]
Ah, no problem. Is there anything we can do to help?

**Comment by pbakaus** [comment]
new branch megamerge is now being autodeployed (yay!), so closing this ticket for now. Will be online very soon.
