### ISSUE TITLE
AMP pages are not loading from ampproject servers

### ISSUE THREAD

**Issue by sameeh-harfoush** [ampproject/docs#1217]
to go google.com on any mobile device

Scenario 1:

1. search for "ready made food in beirut brate"
2. click on the amp page (URL: https://lb.brate.com/en/amp/ready-made-food-in-beirut/ccp-1-857)
3. the page keeps loading but doesn't display content 

![screen shot 2018-10-05 at 2 14 19 pm](https://user-images.githubusercontent.com/3295628/46532366-1d376d00-c8a9-11e8-85ce-efe0fa784132.png)

![screen shot 2018-10-05 at 2 14 36 pm](https://user-images.githubusercontent.com/3295628/46532373-24f71180-c8a9-11e8-85ed-abec8a84e495.png)

![screen shot 2018-10-05 at 2 14 47 pm](https://user-images.githubusercontent.com/3295628/46532375-29232f00-c8a9-11e8-925d-99172b14bddd.png)

The above AMP page test result keeps loading and doesn't show any content.

Scenario 2:
1. search for "fintech techcrunch "
2. click on the any amp page by Techcrunch
3. the page keeps loading but doesn't display content 

i am loosing a lot of traffic cause of this problem, please advise on the status and the way forward.

**Comment by CrystalFaith** [comment]
Hi @sameeh-harfoush - sorry to hear you're having issues. Unfortunately, this repo is related to the ampproject.org website and AMP documentation needs. This issue would be better supported if posted in [Webmaster Central Help Forum](https://productforums.google.com/forum/#!forum/webmasters). 

Closing this one out.
