### ISSUE TITLE
amp-form xhr amp-mustache not displaying returned json

### ISSUE THREAD

**Issue by IamAlta** [ampproject/docs#1222]
## Description of the issue found on ampproject.org
amp-form xhr amp-mustache not displaying returned json vars

Please provide:

- Page link: https://www.ampproject.org/docs/reference/components/amp-form#success/error-response-rendering the first example under "Success/error response rendering".

- Description of the documentation issue:
I coded the first example under "Success/error response rendering".

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

On page https://www.ampproject.org/docs/reference/components/amp-form#success/error-response-rendering the first example under "Success/error response rendering" was coded.
See here for code: https://codepen.io/iamalta/pen/vVyErX

The returned json is
[{"name":"Jane Miller","interests":[{"name":"Basketball"},{"name":"Swimming"},{"name":"Reading"}],"email":"email@example.com"}]

Expected behavior
Should get the following for the above example with the mustaches completed.
"Success! Thanks {{name}} for subscribing! Please make sure to check your email {{email}}
to confirm! After that we'll start sending you weekly articles on {{#interests}}{{name}} {{/interests}}."

This is what is displayed - missing name and start date.
"Success! Thanks for subscribing! Please make sure to check your email to confirm! After that we'll start sending you weekly articles on ."

What browser are you using?
Chrome and Firefox recent vers.

What O/S are you using? n/a

**Comment by IamAlta** [comment]
@pbakaus @CrystalFaith 
I spend hours on a problem and when I ask for help, I then see the problem.
This is solved.
The problem was the returned json had too many dimensions in the array. It was created as for amp-list with "items" as the parent array.

So sorry but thanks for the kick to get this solved :)

Make it a nice day. You all deserve it.

**Comment by CrystalFaith** [comment]
@IamAlta - Glad to hear your issue was resolved! Thanks for reaching out (and closing a resolved issue :) )
