### ISSUE TITLE
Broken: https://g.co/ampdemo 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/docs#125]
https://g.co/ampdemo does not demo the Google Search news carousel as expected. (on Mobile or Desktop)

@pbakaus

**Comment by pbakaus** [comment]
the carousel is enabled on google.com, so the link isn't required anymore. It's not enabled in every country yet though. Which locale are you coming from?

**Comment by aghassemi** [comment]
oh I got it. I didn't expect I needed to actually do a search after hitting the link. (until I watched the video of the demo). Should the link do a common news related search by default?

**Comment by pbakaus** [comment]
good idea, but probably out of scope for the project website. Glad you were able to see it now though! Closing the ticket for now.
