### ISSUE TITLE
Broken links on overview page.

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#1278]
## Broken links on overview page

- Page link: https://www.ampproject.org/learn/overview/
- Description of the documentation issue: Five broken links.
Three under AMP HTML section, one under AMP JS and one under AMP Cache

https://www.ampproject.org/learn/overview/%7Bg.doc('/content/docs/fundamentals/spec.md',%20locale=doc.locale).url.path%7D
https://www.ampproject.org/learn/overview/%7Bg.doc('/content/docs/getting_started/create.md',%20locale=doc.locale).url.path%7D
https://www.ampproject.org/learn/overview/%7Bg.doc('/content/docs/fundamentals/discovery.md',%20locale=doc.locale).url.path%7D
https://www.ampproject.org/learn/overview/%7Bg.doc('/content/docs/fundamentals/spec.md',%20locale=doc.locale).url.path%7D
https://www.ampproject.org/learn/overview/%7Bg.doc('/content/docs/fundamentals/validate.md',%20locale=doc.locale).url.path%7D

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to https://www.ampproject.org/learn/overview/
2. Click all the links and discover which ones are broken (or alternative go to source and look for the links above)

What browser are you using?
Ubuntu
What O/S are you using?
Chrome

**Comment by pbakaus** [comment]
Fixed.
