### ISSUE TITLE
Broken links on overview page

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#1280]
To repro go to https://www.ampproject.org/learn/overview/
and click "HTML Tags in the AMP spec"

**Comment by pbakaus** [comment]
@CrystalFaith can you take a look at this? I think this broke with our URL function rewrite branch, and specifically because using the grow function to resolve the URL doesn't work in the front matter (I think that carousel content comes from the front matter / YAML).

**Comment by pbakaus** [comment]
Everything fixed.
