### ISSUE TITLE
Create documentation for VSCode extension for AMPHTML validator.

### ISSUE THREAD

**Issue by dparikh** [ampproject/docs#1292]
VSCode extension for AMP HTML validator is now available and the documentation can be modified to add the link and some details.

VSCode marketplace link: https://marketplace.visualstudio.com/items?itemName=amphtml.amphtml-validator
Github: https://github.com/diparikh-project/vscode-amphtml-validator

**Comment by pbakaus** [comment]
Note to assignee: This should be appearing in the new Tools overview page we're launching as part of amp.dev.

**Comment by matthiasrohmer** [comment]
@pbakaus, can you check if what we have on the [Tools page](https://amp.dev/documentation/tools.html#vscode) is what you had in mind?

**Comment by pbakaus** [comment]
yep that's great, thanks!
