### ISSUE TITLE
Broken link for: So your AMP test doesn’t perform — now what?

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1297]
- Page link: https://www.ampproject.org/ (The latest), https://www.ampproject.org/latest/blog/ (So your AMP test doesn’t perform — now what?)
- Description of the documentation issue: The link to the blog post https://www.ampproject.org/latest/blog/so-your-amp-test-doesnt-perform%e2%80%8a-%e2%80%8anow-what/ is broken.

**Comment by pbakaus** [comment]
I've noticed that one...but closing it as wontfix for now, as it doesn't make sense to spend much energy on now. Thanks for the catch though!
