### ISSUE TITLE
Guide for AMP Analytics (incl. amp-analytics and amp-pixel)

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#13]
Should touch on these points:
- Capabilities of amp-pixel vs. amp-analytics. Why use one over the other?
- Components are designed to work whether you're interested in collecting for yourself (owned ingestion endpoint) or want to transmit the data to a 3P (e.g. analytics provider for reporting, dashboards, etc.)
- Basic overview of how amp-pixel works technically and how amp-analytics works technically (talk about how amp-analytics uses a "measure once, report to many" approach)
- Guide to getting a basic amp-analytics request set up
- How amp-analytics works if you want to send the data to a vendor; talk about vendor configuration
- Link to a reference on what to do if you are a vendor and want to add a vendor config
- Guides on how to use various attributes of amp-analytics and what use cases they address
- Talk about client identifier

cc @Meggin

**Comment by Meggin** [comment]
In this pull request: https://github.com/ampproject/docs/pull/46

**Comment by Meggin** [comment]
Delivered decent set of analytics docs for public launch, so closing this one.
