### ISSUE TITLE
Add support for <amp-video> and poster images 

### ISSUE THREAD

**Issue by CrystalFaith** [ampproject/docs#1316]
Support <amp-video> and poster images in amp.dev

**Comment by matthiasrohmer** [comment]
Implemented together with the support for captions. Usable by

`[video src="https://www.youtube.com/watch?v=2WjFBnCj2ew" width="480" height="270" caption="Watch our video on creating delightful AMP story experiences."]`

Alternatively use a local video path (video source in `~pages/static`).
