### ISSUE TITLE
Keep sidebar scrolled to document currently viewing 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#1340]
## Keep sidebar scrolled to document currently viewing 

Not sure if this was brought up before or not, but, when clicking on a new guide or tutorial the sidebar scrolls back up to the top when the page reloads. It's a bit disorienting to loose your place. While taking inventory of migrated docs I kept mistaking where I was in the sections. 

Hoping theres a way we can correct this behavior. Thanks!

**Comment by matthiasrohmer** [comment]
Yep I remember we talked about this when you were in Hamburg. It might be that I am mistaken but didn't @pbakaus inject a tiny (AMP invalid) script to work around this at least during migration?

**Comment by matthiasrohmer** [comment]
We've the rebuild of the sidebar using `amp-sidebar` that's fixed. 🎉
