### ISSUE TITLE
Annotate all document types (templates) with schemas

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1343]
## Objective

Follow-up to #1315. To make the information on amp.dev widely available (search, voice, ...) we should annotate the various document types with matching schemas.

**Comment by sebastianbenz** [comment]
Can you provide a list of schema types we should use?

>

**Comment by matthiasrohmer** [comment]
There is still some research left to do but the most promising type seems to be [TechArticle](https://schema.org/TechArticle)... This could at least cover the guides and tutorials I assume. For overview pages [CollectionPage](https://schema.org/CollectionPage) probably is the best fit without having checked its individual properties in detail.
