### ISSUE TITLE
Order documents and collections in Guides & Tutorials section

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1344]
## Objective

The documents and collections inside the Guides & Tutorials section should be ordered according to the IA provided by @CrystalFaith.

**Comment by matthiasrohmer** [comment]
One of our student assistants took care of bringing the documents in order today, @CrystalFaith. Just have a look at the updated [staging environment](https://amp-dev-staging.appspot.com/documentation/guides-and-tutorials.html). Though he found some inconsistencies you could maybe take a look at. That would be great 🙂 

_Create interactive AMP pages_, _Create a login-requiring AMP page_ and _Configure Analytics_ are listed as individual documents but are actually collections - is that okay and are the documents inside the collections are correct?

_Integrating with AMP to serve display ads_ doesn't seem to be on the page - did it get a new title recently maybe or is it not yet written?

_Integrating your analytics tool with AMP_, _Managing non-authenticated user state with AMP_ and _Supported partners & integrations_ are on the page but don't seem to be in the sheet.

**Comment by pbakaus** [comment]
@matthiasrohmer thanks for this, and sorry for the late response from us. I've taken a look and worked hard to get everything into good shape. Everything should look fairly decent now. I also created stub pages for pages that we want to write – these I'd obviously mark as hidden before we launch for real, but it's good to see the whole picture. There are still a bunch of smaller issues, but I will open individual issues for these.
