### ISSUE TITLE
Integrate playground

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1346]
## Objective

Integrate playground from AMP by Example:

* add a new dir `playground` which will contain the playground frontend and backend.
* load playground router from platform/serve.js
* stepwise migrate backend functionality from node
* implement embed mode

**Comment by matthiasrohmer** [comment]
I am pondering if it makes sense to make the `docs` repository also the home of the Playground: from a IA perspective I'd say definitely but technically I think it doesn't have any strong dependencies to what is needed to run amp.dev.

But it might also be that I am missing some background on this and that the Playground is indeed more dependent on the samples for example than I am aware of, then I'd be happy for some insights 🙂

**Comment by sebastianbenz** [comment]
I agree, it could be standalone as well. For now, it's easier to keep everything in the same repo. My main concern is the negative impact on build times, but that's something that should be solvable by caching. One benefit is that it gives us the possibility to reuse CSS and assets for the playground. 

//cc @pbakaus for thoughts

**Comment by pbakaus** [comment]
+1 on having it in one repo. We can revisit if there are strong reasons to move out again.

**Comment by matthiasrohmer** [comment]
That's done!
