### ISSUE TITLE
Even i do page in amp page speed is still 56%(because of ads), ads reduces speed for amp pages also??

### ISSUE THREAD

**Issue by NaveenaBlessy** [ampproject/docs#1359]
## Objective

(Shortly describe what this issue should achieve)

## Background

(Carefully describe why this task should be done)

## Tasks
- [ ] List tasks that need to be
- [ ] completed to finish this task

**Comment by pbakaus** [comment]
Hi @NaveenaBlessy, this isn't the right place to ask questions about AMP, but any bugs with the documentation or website of AMP. For general AMP related questions, find support options [here](https://www.ampproject.org/support/developer/get_support).
