### ISSUE TITLE
[amp.dev] Bad title for homepage

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#1389]
The homepage title is currently just "Start".

Also the link on the logo goes to `/index.html`. Please change to `/`.

**Comment by sebastianbenz** [comment]
The /index.html part is already fixed. @matthiasrohmer can you fix the title.

**Comment by matthiasrohmer** [comment]
Sure! What do we wanna go with? ampproject.org uses "Accelerated Mobile Pages Project" but I think you wanted the full name to slowly fade out in favor of just "AMP". 

I am by no means a copywriter but maybe "AMP the web component framework" in companion to our tag line? @pbakaus, you have an idea?

**Comment by pbakaus** [comment]
Similar to how react does it, maybe:

> "AMP – a web component framework to easily create user-first web experiences"
