### ISSUE TITLE
Underwhelming footer

### ISSUE THREAD

**Issue by derekcecillewis** [ampproject/docs#139]
The way the footer is currently just blank excpet a GitHub logo doesn't seem to be an exercise in minimalistic design. I'm concerned that some data should be there that is missing. Possibly copyright info or terms and privacy links?

**Comment by cramforce** [comment]
Don't want to be too snarky, but this must be the first time a user complained about lack of a spammy footer :)

If any content is missing, we should file separate issues and track it there.

**Comment by derekcecillewis** [comment]
Sorry for the confusion, but please do not interpret the creation of this issue as my request for a spammy footer. Although I am aware Google doesn't like boilerplate content, I do not think adding a line of text and a couple links to the footer would constitute it as being spammy. I only created this issue because I was asked to by @erwinmombay. All I really wanted was some insight into the AMP developer's thought process on having an empty footer. I'm still very new to AMP and was thinking that empty footers might possibly be an AMP design pattern, so I tweeted about it. This, however, does not appear to be the case. So what I am left to believe is that you all have either a) been avoiding a footer entirely for fear that it would become spammy or b) you, like me, have no idea what would be appropriate to put in the footer of an open-source docs website.

After looking at a few other Google-operated open-source docs websites ([source.android.com](https://source.android.com/), [angular.io](https://angular.io/), [dartlang.org](https://www.dartlang.org/), [golang.org](https://golang.org/)), I discovered that it is very common to at least have a word about licenses. Something like this:

> Except as noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code is licensed under a BSD license.

As for what you are legally required to have, I hope this issue gets seen by someone savvy on the laws about these things. Anyways, hope none of this came off in the least bit snarky. Just know that I'm a fan and wish the best for this project. :)

**Comment by pbakaus** [comment]
That docs pages didn't have footers was just a bug. Should be fixed now. Closing this issue for the time being as I don't see any real potential for action – no need to add stuff if we heard no complaints :)
