### ISSUE TITLE
AMP Docs Element media queries - please flip-flop the widths in example.

### ISSUE THREAD

**Issue by ricksherm** [ampproject/docs#1392]
## Objective
https://www.ampproject.org/docs/design/responsive/control_layout#using-media-queries
AMP Docs Element media queries -
media="(min-width: 650px)"
src="wide.jpg"
width=466
media="(max-width: 649px)"
src="narrow.jpg"
width=527
The wide image has width 466 and the narrow image has width 527.
The 466 and 527 number are reversed and they should be flip-flopped.

## Background

Width=466 is shown for wide.jpg and width=527 is shown for narrow.jpg, however the numbers 466 and 527 are reversed and should be flip-flopped so that they make sense to the reader. Please and Thank you.

## Tasks
- the numbers 466 and 527 are reversed and should be flip-flopped

![amp docs element media queries flip-flop image widths](https://user-images.githubusercontent.com/14152097/52924582-f7a87e80-32f2-11e9-92c9-b7f81163dbd6.png)

**Comment by matthiasrohmer** [comment]
That's fixed for amp.dev, will probably won't update the documents for ampproject.org, @CrystalOnScript?
