### ISSUE TITLE
Extension documentation should have reminder about include statement

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#14]
General extension documentation has it here: https://github.com/ampproject/amphtml/blob/master/extensions/README.md#amp-html-extended-components

But I think it would improve usability of the extensions if there was a standard section that was something like:

```
# Include `amp-frame` on your page
Add `<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>` in the head of your page.
```

**Comment by Meggin** [comment]
I've added the custom-element scripts to the new intro tables, and I've also documented the validation error when it isn't included. This should cover this. Changes are in /docs, but not yet pushed to ampproject.org.
