### ISSUE TITLE
Include visual affordance to close sidebar

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/docs#140]
@pbakaus 

Filing an issue to enable a visual affordance to close the sidebar

If the user accidentally opened the sidebar, or opened it then realized that it wasn't what they wanted, it would be nice to be able to tap the same spot to close it again. Instead, tapping in the same spot opens the language menu it takes a little experimentation to tap outside the sidebar to close.

I recommend adding the hamburger menu icon to the sidebar so it stays in roughly the same place, and shifting the drop-down arrow out of the way, bringing it closer to the word "English" and making it a little smaller, to get something like the following screenshot

<img width="460" alt="screen shot 2016-07-18 at 4 43 15 pm" src="https://cloud.githubusercontent.com/assets/16807766/16934109/3d3110da-4d08-11e6-8e03-ab4f02ccbfd5.png">

**Comment by pbakaus** [comment]
Fixed!
