### ISSUE TITLE
Components need inline examples

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#141]
E.g. https://www.ampproject.org/docs/reference/amp-img.html

This page has a lot of text but not `<amp-img></amp-img>` I can copy and paste.

**Comment by bpaduch** [comment]
Now that embedded samples work, I'll include some; however, need #457 fixed to really get rolling on embedding samples in ref docs.

**Comment by bpaduch** [comment]
Top 10 accessed components:

-  [x] amp-img
-  [x] amp-ad
-  [x] amp-form
-  [ ] amp-accordion
-  [ ] amp-iframe
-  [ ] amp-sidebar
-  [ ] amp-pixel
-  [ ] amp-list
-  [ ] amp-carousel
-  [x] amp-facebook

**Comment by bpaduch** [comment]
Closing out.  Will implement amp-list when Sebastien corrects ABE code for embedded examples.
