### ISSUE TITLE
Translation mistake: "How AMP Works" page

### ISSUE THREAD

**Issue by sisidovski** [ampproject/docs#1412]
## Objective

This is not a big problem at all though, I'd like to fix "How AMP Works" page Japanese translation, because the speaker name is wrong.

Original file is [here](https://github.com/ampproject/docs/blob/4f8b3941cb3339798754cea707ee0f0a7a2f6f58/content/learn/about-how.yaml), and translated file which should be fixed is [here](https://github.com/ampproject/docs/blob/4f8b3941cb3339798754cea707ee0f0a7a2f6f58/content/learn/about-how@ja.yaml)

I think he is Paul, not Malte🙃

![www ampproject org_ja_learn_about-how_ 1](https://user-images.githubusercontent.com/1642255/53669437-ec771c00-3c2b-11e9-9fa8-6bb3dfce767b.png)

Just removing one sentence would be fine.

## Background

(Carefully describe why this task should be done)

## Tasks
- [ ] List tasks that need to be
- [ ] completed to finish this task

**Comment by matthiasrohmer** [comment]
Thanks for the report @sisidovski! My Japanese is limited to Google Translator sadly but the translation it gives also attributes the title "Engineering Leader" to Malte which would not be 100% accurate for Paul. Can you give a whole sentence that'd make sense?

**Comment by sisidovski** [comment]
@matthiasrohmer

in the section in Japanese, this sentence is just unnecessary.

```
この動画では AMP エンジニアリング リーダーの Malte Ubl が、以下の記載内容と同様の概要説明をしています。
```

The sentence means "In the video, Malte Ubl, an Engineering Leader of AMP explains the basic concept of AMP, which is explained in this page."

But this sentence doesn't exist in the original English page. So I think just removing this sentence would be good. I made a PR to fix it at the moment. https://github.com/ampproject/docs/pull/1673
