### ISSUE TITLE
Get started link broken

### ISSUE THREAD

**Issue by warpr** [ampproject/docs#143]
When clicking the "Get Started" link in the Tutorial box I get a 404 page, the link is to this url:

https://www.ampproject.org/docs/get_started/create_page.html

**Comment by ggshow** [comment]
The correct URL should be
https://www.ampproject.org/docs/get_started/create.html

**Comment by pbakaus** [comment]
On it. Will be fixed soon.

**Comment by pbakaus** [comment]
Fixed with the next deploy.
