### ISSUE TITLE
Create guides section on advertising

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#145]
Use the help guides at http://dfp-amp-testing-1185.appspot.com/ and migrate/convert generic content to ampproject.org.

**Comment by bpaduch** [comment]
@pbakaus  Do we still need this if we now have "[Serving Ads on AMP](https://www.ampproject.org/docs/guides/author-develop/ads_on_amp
)" Guide?

**Comment by pbakaus** [comment]
Nope, I think this bug is redundant now! Thanks.
