### ISSUE TITLE
Add AMP Cache guidelines

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#146]
We'd like to document what the AMP Cache guidelines are, for people interested in how the cache works, or interested in building their own.

**Comment by Antiie** [comment]
+1

**Comment by erwinmombay** [comment]
cc @dknecht

**Comment by bpaduch** [comment]
Documented here - https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md. Sufficient?
