### ISSUE TITLE
Update list of custom fonts

### ISSUE THREAD

**Issue by Gregable** [ampproject/docs#147]
https://www.ampproject.org/docs/reference/spec.html#custom-fonts mentions that there are only two font serving origins whitelisted:

* https://fast.fonts.net
* https://fonts.googleapis.com

There are a few more implemented currently:

* https://maxcdn.bootstrapcdn.com/font-awesome/
* https://cloud.typography.com/

**Comment by pbakaus** [comment]
Good  catch. Should be fixed here: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md

/cc @cramforce

**Comment by pbakaus** [comment]
Could you reopen the bug in the amphtml repo? Thanks!
