### ISSUE TITLE
Incorrect link: "Examples" link not working on amp.dev

### ISSUE THREAD

**Issue by seagyn** [ampproject/docs#1500]
## Objective

Trying to open up the `Examples` link from the main menu doesn't work.

**Comment by sebastianbenz** [comment]
Thanks for reporting! We will fix this soon.

**Comment by yazdotdev** [comment]
I received a 503 error.  Is that what you are seeing too?  It may be more of a devops than an AMP issue.

![Screenshot from 2019-03-11 12-31-44](https://user-images.githubusercontent.com/48443543/54131193-b7c44b00-4409-11e9-9cc3-5171c40dcf87.png)

**Comment by seagyn** [comment]
I received a 404 not found earlier.

**Comment by yazdotdev** [comment]
![](https://i.giphy.com/media/a5viI92PAF89q/giphy-downsized.gif)

**Comment by sebastianbenz** [comment]
The playground issue is a different one. Looking into it.

**Comment by yazdotdev** [comment]
That's what I thought @sebastianbenz 
But I did not want to create a separate issue just in case of duplication.  Thank you for your efforts.
