### ISSUE TITLE
Better integration of ampbyexample.com into our site

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#152]
We should surface examples with screenshots etc, and maybe even iframe some wherever we can. This is a placeholder bug until we can figure out the details.

**Comment by bpaduch** [comment]
Is this in addition to the embedded examples?  
Where possible, I've also been calling out - "Hey, check out the live demo on ABE".  Is that sufficient or do we want to take this even farther?

**Comment by pbakaus** [comment]
I think it'd be super nice if we had a better integration, e.g. we show simple demos on most of our guides, but automagically link to more complex demos about the same topic in a standardized way.

**Comment by bpaduch** [comment]
Yeah, cool. I agree.

**Comment by mattludwig** [comment]
FYI, we're discussing the strategy to bring ABE, AMP Start (as it gets built out) and the project site together more -- whether through better linking or merging content. More details to come.

**Comment by sebastianbenz** [comment]
I think we can close this now...
