### ISSUE TITLE
Analytics guide: Document a way to sample requests

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#154]
@avimehta can you explain what needs to be done here?

**Comment by avimehta** [comment]
yes. Would you like this to be a thing separate from the usual analytics docs? I need to update the analytics docs with information on sampling. Do you mind waiting for that and then deciding on what to do here?

**Comment by pbakaus** [comment]
Sure, happy to wait for it! I need to get a feel for how substantial the amount of content is, to be able to understand if we need a separate page for it.

**Comment by avimehta** [comment]
Will send out a PR by today. I am planning to write less than two paragraphs on this.

**Comment by avimehta** [comment]
Hi! Would you like to look at https://github.com/ampproject/amphtml/pull/4219 before I merge it? It contains the sampleSpec  and other changes.

**Comment by pbakaus** [comment]
LGTM!
