### ISSUE TITLE
Developer guide for live blogs

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/docs#156]
@pbakaus (taking email discussion into a tracking issue to develop guides for implementing <amp-live-list> for live blogs)

Should solve two use-cases:
• Standard approach for live blogs (publisher just wraps updating sections in amp-live-list + relevant child elements, and republishes when there are updates)
• Publishers using 3P <iframe> widgets (can use <amp-iframe>)

Should also include schema markup for live blogs

Let me know what you need along the way—thanks!

**Comment by kul3r4** [comment]
I am working on adding a tutorial for live blogs.

**Comment by bpaduch** [comment]
Live Blog Tutorial published - https://www.ampproject.org/docs/get_started/live_blog
