### ISSUE TITLE
Unexpected layout="responsive" in Create Responsive AMP Pages code example

### ISSUE THREAD

**Issue by ggshow** [ampproject/docs#158]
https://www.ampproject.org/docs/guides/responsive_amp.html
https://github.com/ampproject/docs/blob/master/content/docs/guides/responsive_amp.md

**Below this section**
Define component styles with class or element selectors using common CSS properties. For example:

There is an unexpected **_layout="responsive"_** at line 10:
`<body>
  <p>Hello, Kitty.</p>
  <amp-img
    class="grey-placeholder"
    src="https://placekitten.com/g/500/300"
    srcset="/img/cat.jpg 640w,
           /img/kitten.jpg 320w"
    width=500
    height=300>
    layout="responsive"
  </amp-img>
</body>`

**Comment by dvoytenko** [comment]
@ggshow Thanks for the report. Do you have a doc running somewhere with this markup? In this example `layout=responsive` appears to be outside of the `<amp-img>` tag in the contents of this element. Is that intended?

**Comment by ggshow** [comment]
Hi @dvoytenko Thank you for reply.

I mean code example appear in docs below need to be fixed.
https://www.ampproject.org/docs/guides/responsive_amp.html

`  <amp-img`
`    class="grey-placeholder"`
`    src="https://placekitten.com/g/500/300"`
`    srcset="/img/cat.jpg 640w,`
`           /img/kitten.jpg 320w"`
`    width=500`
`    height=300>`
`     layout="responsive"`  **<--- this line has been wrongly placed here?**
`   </amp-img>`

**Comment by dvoytenko** [comment]
@ggshow I see. Thanks!
