### ISSUE TITLE
Horizontal scrollbar for code samples is too tiny to see and grab

### ISSUE THREAD

**Issue by douyo** [ampproject/docs#1603]
## Horizontal scrollbar for code samples is too tiny to see and grab

Some pages have long lines of code that are wider than the code snippet box. e.g., 

https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.html?format=websites#adding,-removing,-and-toggling-classes

![image](https://user-images.githubusercontent.com/13109990/54860772-4a070180-4cdc-11e9-9eaa-932c261d2b8d.png)

In order to scroll to the right to see the rest of the code, I would use the horizontal scrollbar, but I don't see one.

The `<div>` around the `<pre>` block actually does have a horizontal scrollbar, but the scrollbar seems to be only 2px in height.

![image](https://user-images.githubusercontent.com/13109990/54860834-11b3f300-4cdd-11e9-849b-faea0247d39b.png)

I'm using Chrome Version 73.0.3683.86 (Official Build) (64-bit)
on Debian GNU/Linux rodete (4.19.20-1rodete1-amd64)

**Comment by sebastianbenz** [comment]
//cc @matthiasrohmer can you discuss this with Longo?

**Comment by matthiasrohmer** [comment]
Already shortly spoke with him about that last week, I'll bump it up to a usable size.

**Comment by sebastianbenz** [comment]
The only thing is that we have to make sure that it doesn't look weird on single line code snippets (which probably has been the reason to decrease the size).

**Comment by keevkeev** [comment]
![Screen Shot 2019-05-09 at 11 13 41](https://user-images.githubusercontent.com/17259420/57442123-9639e100-724b-11e9-8c20-12c508a593d5.png)

@sebastianbenz this is from 2px to 4px. What do you think?

**Comment by sebastianbenz** [comment]
@keevkeev LGTM
