### ISSUE TITLE
When loading a URL with a #fragment, "Toggle Sidebar" covers content

### ISSUE THREAD

**Issue by douyo** [ampproject/docs#1604]
## When loading a URL with a #fragment, "Toggle Sidebar" covers content

When you load a URL with a #fragment -- e.g.,:

https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.html?format=websites#adding,-removing,-and-toggling-classes

The "Toggle Sidebar" label is displayed and covers some of the content.

![image](https://user-images.githubusercontent.com/13109990/54861057-568d5900-4ce0-11e9-80ff-22a899603d51.png)

Scrolling the page up and down doesn't hide the "Toggle Sidebar" label. The label continues to cover some of the content on the page.

![image](https://user-images.githubusercontent.com/13109990/54861062-6c9b1980-4ce0-11e9-985f-7ea7ae6c60fd.png)

In order to hide the "Toggle Sidebar" label, I need to scroll all the way up to the top of the page and then scroll down the page.

![image](https://user-images.githubusercontent.com/13109990/54861078-aec45b00-4ce0-11e9-8527-d8c243a3d981.png)

I'm using Chrome Version 73.0.3683.86 (Official Build) (64-bit)
on Debian GNU/Linux rodete (4.19.20-1rodete1-amd64)

**Comment by keevkeev** [comment]
I believe this issue is coming from where we've placed our position observer. I'll take care of this issue

**Comment by matthiasrohmer** [comment]
The position of `amp-position-observer` in the DOM shouldn't have any effect on this. I fear the component just doesn't react to scroll on page load. I couldn't quickly find a matching issue in amphtml though, @sebastianbenz do you have more information on this?

**Comment by sebastianbenz** [comment]
amp-position-observer works on page load (see [this demo on mobile](https://amp-demos.glitch.me/sticky-header.html#item3)). Moving the position observer closer to the title might be a way to fix this.

Sidenote: I'd find it supercool if the button collapses relative to the scroll speed.

**Comment by matthiasrohmer** [comment]
Thanks for the heads-up! @keevkeev, then go ahead and try your suggested fix.

**Comment by matthiasrohmer** [comment]
Fixed.
