### ISSUE TITLE
Add cookie language to "experimental" docs

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/docs#164]
(Don't have access to this repo, otherwise I would issue a PR myself)

Could we make the following edit to the language in the [experimental docs](https://github.com/ampproject/docs/blob/e20b653c7f608975be7e15bdba838261508f4f7e/content/docs/reference/experimental.md)

After the sentence:

> For content served from https://cdn.ampproject.org, go to the AMP experiments page and enable (or disable) any experimental component by toggling them on (or off).

Add:

> Opting in will set a cookie on your browser that will enable the experiment on all AMP pages served through the google AMP Cache

Doesn't have to be exact, but let me know if there are any changes so I can confirm that it contains the right information.

Thanks!

**Comment by dvoytenko** [comment]
@erwinmombay are you handling this?

**Comment by pbakaus** [comment]
Done: https://github.com/ampproject/docs/commit/eb476bbd286277f382532a8c97385e549c049bbb
