### ISSUE TITLE
schema metadata logo URL is 404

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#1662]
https://www.ampproject.org/ (and I think all pages on the site) includes the schema.org metadata:

```json
    "publisher": {
      "@type": "Organization",
      "name": "AMP Project",
      "logo": {
          "url": "https://www.ampproject.org/assets/img/logo-blue.svg",
          "width": 175,
          "height": 60,
          "@type": "ImageObject"
      }
    }
```

The URL https://www.ampproject.org/assets/img/logo-blue.svg 404s. I think this should instead by https://www.ampproject.org/static/img/logo-blue.svg.

**Comment by sebastianbenz** [comment]
I'm not sure this is relevant anymore, we should make sure though that the schema.org data is correct for amp.dev.

**Comment by ithinkihaveacat** [comment]
In that case, this can probably be closed: the amp.dev schema.org data looks fine (i.e. no 404s).

(https://amp.dev does have the image https://www.ampproject.org/static/img/logo-og-image.jpg though.)
