### ISSUE TITLE
Wrong URL for AMPHTML spec

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1676]
The AMPHTML spec URL ends in `index.html` instead of `amphtml`:

`https://amp.dev/documentation/guides-and-tutorials/learn/spec/index.html?format=websites`

vs

`https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.html?format=websites`

**Comment by matthiasrohmer** [comment]
But those are two different pages 😁 #1678 updates `/documentation/guides-and-tutorials/learn/spec/index.html` to `/documentation/guides-and-tutorials/learn/spec/amp-html.html` though. WDYT?

**Comment by sebastianbenz** [comment]
Yes, they're two different pages, but they should use the same link naming scheme:

* `.../spec/amp-boilerplate`
* `.../spec/amphtml`

**Comment by matthiasrohmer** [comment]
Updated #1678!
