### ISSUE TITLE
Preview header on mobile is broken

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1680]
Two problems:

1. Logo and title overlap. Suggestion: remove 'Example Preview' and scale title down. Maybe Longo has a better idea.
2. Logo and title are not aligned

<img width="494" alt="Screenshot 2019-04-01 at 19 30 02" src="https://user-images.githubusercontent.com/380472/55347936-45013980-54b6-11e9-9296-abec04fcbd2a.png">

**Comment by matthiasrohmer** [comment]
That was on `future`, wasn't it? Because on `perf/sample-preview` we already got rid of "Example" and just call it "Preview" and also the alignment issue is fixed. The overlapping still occured though, that is now also fixed.
