### ISSUE TITLE
Remove Table of Contents for coursework

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1686]
The Table of Contents makes the space for actual content quite small. In the courses, this poses a special problem, since our code samples need a lot of horizontal scrolling. Meanwhile, there's a lot of unused space on the right.

Can we remove the ToC for courses - and reassign those grid columns to the main content?

/cc @sebastianbenz @mandarini @matthiasrohmer

**Comment by matthiasrohmer** [comment]
Not setting `toc: true` in the frontmatter and not having `[TOC]` somewhere in the content while hide the marginalia and give the main column more space. The condition was broken though, fixed this in #1688.

**Comment by morsssss** [comment]
Yes, #1688 closes this. Thank you!
