### ISSUE TITLE
Broken amp.dev links in Search

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1687]
Search contains links to amp.dev that have the old ampproject.org file structure. These links are broken.

(Not sure if you can do much about this, but wanted to flag it just in case!)

![Screen Shot 2019-04-01 at 3 45 23 PM](https://user-images.githubusercontent.com/29419498/55355055-4b32ee00-5495-11e9-8d6e-bcbd7c7c6968.png)

**Comment by matthiasrohmer** [comment]
That looks especially strange. Do you have a link for us to reproduce this SERP?

**Comment by sebastianbenz** [comment]
I think this slowly got fixed with subsequent index updates...
