### ISSUE TITLE
Home page, Who and Roadmap are always in english and unable to change language on those pages

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#169]
The home page (https://www.ampproject.org/), who (https://www.ampproject.org/who/) and roadmap (https://www.ampproject.org/roadmap/) are always in english and there is no ability to change language (clicking and hovering does nothing on icon and text "English").

Subpages (didn't test all though) under FAQ allow for changing the language, but once one goes back to any of those three pages (home page, who, or roadmap), language gets reset to english.

**Comment by pbakaus** [comment]
First of all, you have the worst username for somebody who *actually cares* ;)

But I disgress.. you're right, this is confusing, and I've just fixed it. Enjoy.
