### ISSUE TITLE
Seatmap multiple selection sample not migrated

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1692]
https://github.com/ampproject/amp-by-example/blob/master/src/30_Advanced/SeatMap_Multiple_Selection.html is missing on amp.dev

**Comment by matthiasrohmer** [comment]
Thanks for the hint! There are some more. I'll wait for Robin to finish the first round on matching amp.dev samples with the abe.com sitemap and then see which ones are missing and migrate them in a batch, fine?

**Comment by sebastianbenz** [comment]
SGTM

>
