### ISSUE TITLE
!important used in CSS styles on amp.dev

### ISSUE THREAD

**Issue by Gregable** [ampproject/docs#1721]
Example page:
https://amp.dev/documentation/guides-and-tutorials.websites.amp.html

This doesn't validate:
https://validator.ampproject.org/#url=https%3A%2F%2Famp.dev%2Fdocumentation%2Fguides-and-tutorials.websites.amp.html

The text inside tag 'style amp-custom' contains 'CSS !important', which is disallowed.

It looks like the offending CSS is (at least post-minification):
`.ap-o-banner-headline{color:#fff!important;max-width:720px}`

**Comment by sebastianbenz** [comment]
Thanks Greg! 

Culprits are:

```
components/molecules/tip.scss
20:important
122:  &-important {

components/organisms/mini-card-list.scss
28:  padding-left: 0 !important;

components/organisms/banner.scss
30:    color: color('white') !important;
```
