### ISSUE TITLE
amp.dev stories docs missing amp-story link in side nav

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#1724]
## Description of the issue found on ampproject.org

Please provide:

- https://amp.dev/documentation/components.html?format=stories
- This page, which is filtered to the stories view, is missing amp-story itself in the component nav on the side.

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. https://amp.dev/documentation/components.html?format=stories
2. Scroll down and look under S for amp-story
3. …

What browser are you using?
What O/S are you using?

**Comment by sebastianbenz** [comment]
Has been already fixed.
