### ISSUE TITLE
ampproject.org: Include instructions on image size specs & image resizing

### ISSUE THREAD

**Issue by Antiie** [ampproject/docs#173]
Prevent errors like blurred images, captions missing, images missing. Clarify what are common specs, what is the difference between responsiveness and rescaling, what can be consequences of misimplementations or - rephrasing this - highlight common errors.

**Comment by dvoytenko** [comment]
@Antiie The spec is documented here: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md

Please send examples where you see the common errors.

**Comment by Antiie** [comment]
@dvoytenko: this is a request for ampproject.org page :-)

**Comment by Antiie** [comment]
Essentially, information is available on github, but people don't find it readily. would suggest including it [here](https://www.ampproject.org/docs/guides/amp_replacements.html) or [here](https://www.ampproject.org/docs/reference/amp-img.html)

**Comment by pbakaus** [comment]
I don't think the commit sufficiently covers what's being asked here, so reopening. However @Antiie, a little more detail would be much appreciated :)

**Comment by bpaduch** [comment]
Working on Guide for Responsive Pages.  Hope to be out this quarter.
