### ISSUE TITLE
Use explicit hints for AMP extensions

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1747]
The string-lookup based dependency injection is not 100% reliable and might create invalid AMP pages. Therefore this solution should be replaced by manual hints similar to `{% do doc.amp.use('amp-animation') %}`. Follow-up issue to #1670.

**Comment by matthiasrohmer** [comment]
Prioritizing this down as the injection works much more reliable than thought before. Also see #1802.

**Comment by matthiasrohmer** [comment]
If we want to use `amp-lightbox-gallery` injecting dependencies based on string lookups ultimately fails and needs to be replaced by a different solution.

**Comment by sebastianbenz** [comment]
We should at least offer explicit declaration as an additional option. This could also then be used by @tharders for the preview generation.

**Comment by matthiasrohmer** [comment]
@dlemm, I laid the foundation for this in #2367 (`refactor/manual-deps`). The page is hopelessly broken now as now AMP component get's added to the page. It'd be great if you could now readd the needed dependencies by going over our templates and adding them where needed with 

`{% do doc.amp_dependencies.add('amp-sidebar', '0.1') %}``

Let me know if there are questions! 🙂
