### ISSUE TITLE
Create shortcode for format-filtered paragraphs

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1748]
It would be nice to have a shortcode that allows to filter certain paragraphs for specific formats. E.g.

```
[filtered format="stories"]
This is only shown when the document is filtered for stories.
[/filtered]
```

/cc @pbakaus @CrystalOnScript

**Comment by matthiasrohmer** [comment]
Increasing priority since the filtering seems to cause confusion:

>ambiguous documentation.
>In list of available AMP components for emails their is no reference to amp-video or amp-youtube.
>But in the Event documentation their are part that talk about those event.
>So does those components exist in the email section?
>My hypothesis is that the event page was copied from an other part of AMP website and not well updated.

**Comment by pbakaus** [comment]
Yes, that makes sense! Would be great to get this built ASAP.
