### ISSUE TITLE
Cleanup Support page

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1751]
http://localhost:8080/support/

* remove link to ampbyexample
* remove link to ampstart
* add link to supported browsers http://localhost:8080/support/faq/supported-browsers

**Comment by matthiasrohmer** [comment]
Note to assignee: the support page is located in the ampproject/amphtml repository. It's getting imported during build from https://github.com/ampproject/amphtml/blob/master/SUPPORT.md.
