### ISSUE TITLE
"Get involved" text is unreadable

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1752]
<img width="1224" alt="Screenshot 2019-04-05 at 00 38 49" src="https://user-images.githubusercontent.com/380472/55593182-3c6d6500-573b-11e9-9aae-a541b80547db.png">

**Comment by sebastianbenz** [comment]
https://amp.dev/documentation/guides-and-tutorials/?format=websites

**Comment by keevkeev** [comment]
fixed with #1768
