### ISSUE TITLE
Issues with URL hashes - Adding them in URL does nothing

### ISSUE THREAD

**Issue by mandarini** [ampproject/docs#1757]
## This issue was found when working on the amp.dev courses docs.

- Description of the documentation issue

I try to create/generate relevant links for other pages within amp.dev. 
So I am using this format:
`{{g.doc('/content/amp-dev/documentation/components/reference/amp-bind.md', locale=doc.locale).url.path}}`

But in some cases I need to add an anchor link for a section of that page. For example, I need to direct the user to the Appendix of amb-bind, so I would need to generate a link like that:
`https://amp.dev/documentation/components/amp-bind.html?format=websites#appendix`

Adding the hash directly to the above format like this:
`{{g.doc('/content/amp-dev/documentation/components/reference/amp-bind.md#appendix', locale=doc.locale).url.path}}`
does not work. It just produces the amp-bind URL without the hash, like this:
`https://........./documentation/components/amp-bind.html?format=websites`

So, how could I add a hash in the URL and make it work, too?

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Try to create a link within amp.dev using the `{{g.doc('/content/amp-dev/documentation/components/reference/amp-bind.md', locale=doc.locale).url.path}}` format
2. Try adding a hash to it
3. …

What browser are you using?
Chrome Version 73.0.3683.75 (Official Build) (64-bit)

What O/S are you using?
Tested on Ubuntu 18.04.2 LTS
and macOS Mojave

@morsssss

**Comment by matthiasrohmer** [comment]
`{{g.doc('/content/amp-dev/documentation/components/reference/amp-bind.md', locale=doc.locale).url.path}}` is correct to generate the URL, you just need to append the fragment *outside* of the curly braces.

**Comment by mandarini** [comment]
Ohhh!! Makes sense! Thanks!
