### ISSUE TITLE
Story Ads templates: poor quality previews

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#1764]
Two of the video previews in the Story Ads templates are of poor quality, see "Annual Clothing Sale" and "Explore the Sea" on https://amp.dev/documentation/templates/ (filter by "Story Ads"):

![amp dev_documentation_templates_](https://user-images.githubusercontent.com/51244/55708119-0bac5a80-59dd-11e9-8a92-75a4e992aec4.png)

These should be replaced by higher-quality versions. The relevant assets appear to be:

- https://amp.dev/static/img/templates/single-image-template.mp4
- https://amp.dev/static/img/templates/single_video.mp4

They were last touched by @keevkeev in https://github.com/ampproject/docs/pull/1590, but that may have been just an automatic GIF to MP4 conversion? Perhaps we need new assets generated?

/cc @mattludwig @hongwei1990

**Comment by matthiasrohmer** [comment]
>They were last touched by @keevkeev in #1590, but that may have been just an automatic GIF to MP4 conversion? Perhaps we need new assets generated?

That's exactly the case 😉We quickly wanted to get rid of the GIFs and the template ZIPs only have the blurred images so we couldn't record new screen casts. Who could provide either the unblurred images or new recordings?

**Comment by anushkaghatia** [comment]
![New_Single_Image_template_for_amp_dev (1)](https://user-images.githubusercontent.com/49408891/55743191-8332b780-59e6-11e9-8fea-06fa58c49f5f.gif)
![New_Video_Template_for_AMP_dev (1)](https://user-images.githubusercontent.com/49408891/55743193-84fc7b00-59e6-11e9-875d-3211c454dc40.gif)

**Comment by keevkeev** [comment]
Thanks @anushkaghatia I'll take care of it

**Comment by ithinkihaveacat** [comment]
@keevkeev If you prefer MP4s let me know and I'll figure out how to get them to you.

**Comment by keevkeev** [comment]
Thanks @ithinkihaveacat, wonderful GH name btw

**Comment by matthiasrohmer** [comment]
> @keevkeev If you prefer MP4s let me know and I'll figure out how to get them to you.

MP4s please 😉

**Comment by ithinkihaveacat** [comment]
Here they are:

https://photos.app.goo.gl/empWSW3HJQs3nT3L7
