### ISSUE TITLE
Support SSR for filter bubbles on overview pages

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#1765]
https://amp.dev/documentation/templates/ can be filtered via the UI, but the URL doesn't update, which makes it impossible to share a link to specific templates among other things.

To reproduce:

1. Load https://amp.dev/documentation/templates/.
2. Select "Story Ads".
3. Copy link.
4. Paste into another browser/share to friend, embed in bug report, etc.

Actual:

Recipient sees all templates.

Expected:

Recipient sees filtered templates.

(Might be related to https://github.com/ampproject/docs/issues/1321.)

**Comment by matthiasrohmer** [comment]
Thanks for the report! That's on our list, even thought there already is an issue for this. Updated yours to handle a bunch of use cases 🙂

**Comment by matthiasrohmer** [comment]
... and there indeed is #1694.

**Comment by ithinkihaveacat** [comment]
Thanks! #1694 was indeed what I thought this might be related to, some copy-and-paste error happened there…
