### ISSUE TITLE
Metrics collection

### ISSUE THREAD

**Issue by dknecht** [ampproject/docs#177]
How are the metrics currently collected?

**Comment by pbakaus** [comment]
@erwinmombay

**Comment by erwinmombay** [comment]
so unfortunately it is done through an internal google instrumentation library + internal processing. but basically it records initialization and the amp runtime calls the tick method from performance-impl.js which then forwards it to the viewer. The tick method is basically just a signal for the instrumentation library to record the time (Date.now() - initializationTime, is the basic gist)

**Comment by pbakaus** [comment]
Since this issue isn't actionable, I'm closing it.
