### ISSUE TITLE
AMP Image and Supported Layout types Docs are Inconsistent

### ISSUE THREAD

**Issue by kscoulter** [ampproject/docs#179]
<amp-img> docs page shows the following layout types are supported:
`FILL, FIXED, FIXED_HEIGHT, FLEX_ITEM, NODISPLAY, RESPONSIVE`
https://www.ampproject.org/docs/reference/amp-img.html

However, when when trying to use fixed_height, AMP does not validate and says unknown layout type. The correct layout is fixed-height.

Also, Supported Layouts page does not describe what a flex-item layout is:
https://www.ampproject.org/docs/guides/responsive/control_layout.html

**Comment by cramforce** [comment]
This seems to be an issue across all docs. These should not be upper case and they should use `-` instead of `_` (this is fatal, the case is ignored).

**Comment by cramforce** [comment]
CC @Meggin @pbakaus

**Comment by cramforce** [comment]
@ericlindley-g Any chance you could fix this?

**Comment by ericlindley-g** [comment]
Sure thing—I'll take a look and see what I can do

**Comment by Meggin** [comment]
Thanks, Eric, for stepping in. This is marked as a partial fix-- is the only thing left to do is update the live version of the reference docs?

**Comment by ericlindley-g** [comment]
One remaining piece is to update the live version of the reference docs (I'm not sure how often that's generated—do you?)

Another task mentioned in this bug (though may be worth opening a separate issue for) is to document "flex" and "flex-item" layout where it makes sense. @zhouyx has already documented it [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#flex-item), but I think those docs could use more detail, and [this doc](https://www.ampproject.org/docs/guides/responsive/control_layout.html) needs them added as well.

**Comment by pbakaus** [comment]
The docs on the site are built automatically, and are automatically redeployed every day. If you don't see them updating (make sure to reload twice to clear the Service Worker), that's likely a bug.

**Comment by ericlindley-g** [comment]
Thanks @pbakaus — looks like the pages have been updated to lowercase, hyphen-separated, so we're set there. I can sync with @zhouyx to determine documentation for "flex" and "flex-item"

**Comment by bpaduch** [comment]
@ericlindley-g & @zhouyx - I've added "flex-item" layout to the Support Layouts doc page.  ptal.

cc: @pbakaus

**Comment by pbakaus** [comment]
Looks like we're all good then – closing the bug! Reopen if you're still missing something.
