### ISSUE TITLE
Clicking many linkable text led to 404

### ISSUE THREAD

**Issue by yogykwan** [ampproject/docs#1795]
## Description of the issue found on ampproject.org

Please provide:

- Page link: https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml.html
- Description of the documentation issue: clicking clickable texts like "contain the AMP boilerplate code" would end in 404 page

## Root cause:

The src all end with ".md", they should may be changed to ".html". Moreover, some files don't belong to current folder. Correct me if I'm wrong please!

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml.html
2. Click any linkable text for another page, like "contain the AMP boilerplate code " 

What browser are you using?
Chrome

What O/S are you using?
Macbook

**Comment by sebastianbenz** [comment]
Thanks for reporting! 

@matthiasrohmer can you look into this? Seems like the internal markdown links don't match our URL scheme.
