### ISSUE TITLE
Make amp.dev header & footer easily importable for blog.amp.dev

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1800]
See #1799.

**Comment by felixarntz** [comment]
Thanks for the quick support on this! Here's what we'd mostly wanna have:
* A single HTML file with all markup making up the header (first top-level `svg`, `header`, `label`, `input`, `nav` nodes)

I also opened #1806 to make something similar available for the footer.

**Comment by matthiasrohmer** [comment]
You're very welcome, thanks for your input @felixarntz and @swissspidy! Please see #1814 and check if it fits your needs 🙂

**Comment by matthiasrohmer** [comment]
Sorry, just saw that you wouldn't even require the `style` node. That's easy to remove, thought it would dynamically change in respect to if there's a banner like currently for AMPConf - maybe that helps.

**Comment by matthiasrohmer** [comment]
Fixed by #1814, we'll ping you as soon as it's live!

**Comment by swissspidy** [comment]
Awesome, thanks!

**Comment by matthiasrohmer** [comment]
Now available via:

- https://amp.dev/shared/header.html
- https://amp.dev/shared/footer.html
