### ISSUE TITLE
Video example is broken for amp-video

### ISSUE THREAD

**Issue by westonruter** [ampproject/docs#1804]
URL: https://amp.dev/documentation/components/amp-video#example

The poster and video assets are apparently missing.

![image](https://user-images.githubusercontent.com/134745/55815398-277b3380-5aa5-11e9-8ff0-e6e8ef330b8f.png)

**Comment by matthiasrohmer** [comment]
@sebastianbenz, none of `https://ampproject-b5f4c.firebaseapp.com/examples/**/*` gets redirected to amp.dev, which is correct. Therefore my guess would really be that the samples' static files didn't make it into the build. Could it be that building the samples for ampproject.org needs to be triggered manually before `firebase deploy`?

**Comment by sebastianbenz** [comment]
Will be fixed as part of #2053
