### ISSUE TITLE
AMP Email link "Get Started" is broken

### ISSUE THREAD

**Issue by mobiliodevelopment** [ampproject/docs#1807]
Hello there. Here is bug on new AMP site:

- Page link: https://amp.dev/about/email
- Clicking on button "Get started" download file

Peters-Mac-mini-i5:SearchConsole-DL peternikolow$ curl -I https://amp.dev/documentation/guides-and-tutorials/start/create_email?format=email
HTTP/2 200 
x-powered-by: Express
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
accept-ranges: bytes
last-modified: Tue, 09 Apr 2019 14:28:25 GMT
etag: W/"2a1da-16a02800328"
content-type: application/octet-stream
content-length: 172506
date: Tue, 09 Apr 2019 18:41:51 GMT
via: 1.1 google
cache-control: public, max-age=3600, stale-while-revalidate=7200
age: 48
alt-svc: clear

Since browser receive application/octet-stream it's being downloaded.

**Comment by matthiasrohmer** [comment]
Thanks for reporting! Will be fixed by #1813.
