### ISSUE TITLE
`create your first email` link in sidebar downloads a document instead of taking you to the tutorial 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#1808]
https://screenshot.googleplex.com/89qmvFzbBaZ

`create your first email` link in sidebar downloads a document instead of taking you to the tutorial

**Comment by matthiasrohmer** [comment]
Thanks for reporting, Crystal! Related to #1806 and will be fixed by #1813.

**Comment by matthiasrohmer** [comment]
Fix is live.
