### ISSUE TITLE
Download amp-ad.md and amp-embed.md from new location

### ISSUE THREAD

**Issue by lannka** [ampproject/docs#182]
Right now, there are duplicated files:

```
builtins/amp-ad.md
builtins/amp-embed.md
```

and

```
extensions/amp-ad/amp-ad.md
extensions/amp-ad/amp-embed.md
```

It was due to the migration of amp-ad from builtins to extensions. However, `builtins/*` still exists because amp docs is still downloading from there.

This is right now blocking the PR to dedupe: https://github.com/ampproject/amphtml/pull/4761/files

A fix could be added [here](https://github.com/ampproject/docs/blob/master/scripts/import_docs.js#L96) to explicitly download `amp-ad` and `amp-embed` from new location.

@erwinmombay @pbakaus how does this sound?

**Comment by pbakaus** [comment]
Sounds good, but why would the script need a change at all? Moving them to the new location should be just fine for the script to handle – it will then simply not show them in the first level nav anymore and (correctly) place them into the extended directory.

**Comment by lannka** [comment]
@pbakaus that was my original thought, thus the PR #181. The only problem is `amp-embed.md` is not an extension itself, it's in the folder of `amp-ad`. We have to hard code `amp-embed` somewhere if we still want it shown up in the doc.

I was thinking of having the hardcode at the original place, so the code change is minimal. And also, `amp-ad` and `amp-embed` are probably common enough to deserve a place at the sidebar?

Other way to avoid this special case is just change the content of `amp-ad.md` to include `amp-embed`. This will avoid all those kind of hassle mentioned above. I personally like this approach better, since `amp-embed` is just an alias of `amp-ad`.

Your thoughts?

**Comment by pbakaus** [comment]
I would prefer the last way, simply embedding the info for amp-embed into amp-ad. This solves the hacks, and also hopefully phases out amp-embed usage.

**Comment by lannka** [comment]
Cool. Same here. I created an issue in amphtml https://github.com/ampproject/amphtml/issues/4946.
We can close this issue with no-op if the team agrees to proceed with the proposed approach.

**Comment by lannka** [comment]
Close this as we decided to merge amp-embed.md inoto amp-ad.md
