### ISSUE TITLE
Distorted images on Blog pages

### ISSUE THREAD

**Issue by antoinebisch** [ampproject/docs#1823]
On this page: [https://blog.amp.dev/2018/11/13/developer-preview-of-better-amp-urls-in-google-search/](https://blog.amp.dev/2018/11/13/developer-preview-of-better-amp-urls-in-google-search/), the Signed Exchanges section and below contain stretched out images that extend beyond the page (which itself cannot be scrolled horizontally).

**Comment by matthiasrohmer** [comment]
That's not the case anymore. Thanks for reporting!
