### ISSUE TITLE
Animated elements overlap on Stories landing page

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1840]
https://amp.dev/about/stories on Chrome on desktop -

When "Build your first story" animates, it overlaps with the matching element to its right.

I also see a bunch of HTML classes that seem partially built to me, like they're missing prefixes. Maybe this is ok. But they look like this:

```HTML
<main class="ap--main -ib"><section class="ap--stage -tt"><div class="-ry"><div class="-tt"><div class="-rb"><div class="-rw ap-a-ico"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#bolt-solid"></use></svg></div><h2 class="-rk">AMP Stories</h2><h1 class="-rx"
```

**Comment by matthiasrohmer** [comment]
Thanks for the report, the minified selectors are fine actually. 🙂 @keevkeev, Ben is referring to the hover animation of the links: 

![Bildschirmfoto 2019-04-11 um 10 10 27](https://user-images.githubusercontent.com/12857772/55941518-a3f74900-5c42-11e9-8eda-7caec6ab52ba.png)

**Comment by morsssss** [comment]
Thanks! Looking at the site further, I realized those two-letter selectors that start with `-` are in fact normal :) Pardon my false alarm there. And thanks for looking at those animations!
