### ISSUE TITLE
Example of amp-audio in AMP Story causes validation errors

### ISSUE THREAD

**Issue by westonruter** [ampproject/docs#1846]
Page link: https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/#amp-audio

I pasted the `amp-audio` example for AMP Stories into the Hello World test story in the playground and it produces a validation error:

> The implied layout 'FIXED_HEIGHT' is not supported by tag 'amp-story >> amp-audio'.

![image](https://user-images.githubusercontent.com/134745/55970177-ea917700-5c33-11e9-9bcd-451f7d8d8b3d.png)

Apparently background audio is the only supported way to add audio to an AMP story page, as the only `layout` that seems to work is `nodisplay`?

This came up while working on the AMP Stories editor for the WordPress plugin as well. See https://github.com/ampproject/amp-wp/pull/2015#issuecomment-475820596

**Comment by sebastianbenz** [comment]
That makes total sense, I was actually wondering about this when I created the sample...

**Comment by keevkeev** [comment]
@sebastianbenz what you you propose for a fix here then. Adding the ```layout="nodisplay```property to the amp-audio component seems to render valid amp and the controls are visible when given the same width and height properties from the sample. 

However, maybe for now just referencing the ```background-audio``` attribute for an amp-story-page is the better solution?

**Comment by sebastianbenz** [comment]
@keevkeev yes, please change the section to explain and demo background audio. Maybe mention that this can also be defined for a whole story.
