### ISSUE TITLE
Google Maps in amp-iframe example has invalid API key

### ISSUE THREAD

**Issue by westonruter** [ampproject/docs#1847]
Page link: https://amp.dev/documentation/components/amp-iframe#behavior

The Google Maps `iframe` displays an error message:

> Google Maps Platform rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address 2607:fb90:8064:f186:d1d1:170a:b1f3:3a9c, with referer: https://amp.dev/documentation/components/amp-iframe

![image](https://user-images.githubusercontent.com/134745/55971656-c1261a80-5c36-11e9-9634-6742d6393867.png)

**Comment by sebastianbenz** [comment]
Thanks Weston! It's fixed now. API key was working for preview.amp.dev, but not amp.dev. Fixed.
