### ISSUE TITLE
Ensure all the AMP Story ad templates contain README

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#1862]
Some of the (zipped) Story Ad templates downloadable from https://amp.dev/documentation/templates/ are missing a README explaining how to make the ad visible.

They should all contain a README with the following text:

```text
In order to see this ads as a standalone AMP page add the amp-story-visible attribute to the <body> tag of the ad. Please remove it when you are ready to upload the ad to your platform to ensure the ads animations only play when the story has started.
```

Can someone assign this issue to me?

FYI @jasti @calebcordry

**Comment by ithinkihaveacat** [comment]
Actually, @jasti @calebcordry @hongwei1990 how about we change the README to explain why the resulting template won't look much like what you see on https://amp.dev/documentation/templates/?

For example:

```text
In order to see this ad as a standalone AMP page add the amp-story-visible
attribute to the <body> tag of the ad. Please remove it when you are ready to
upload the ad to your platform to ensure the ads animations only play when the
story has started.

Note that even with the amp-story-visible attribute added, the template will
still not render as shown in the preview image on https://amp.dev/. There are a
few reasons for this:

- Assets (videos, etc.) have been intentionally blurred.
- Parts of the preview (the "Ad" overlay in the top left corner, and the CTA
  button itself) are generated by the ad runtime, which is not available when
  developing locally. These will only appear when the ad is uploaded to your ad
  platform.
```

For reference, this is what the "Video" template looks like when downloaded and viewed locally:

![localhost_8000_single-video html(Pixel 2)](https://user-images.githubusercontent.com/51244/56028559-547f4e80-5d10-11e9-8a23-24837d8afd3b.png)

**Comment by matthiasrohmer** [comment]
@ithinkihaveacat, good idea! Also added you as a collaborator.

**Comment by jasti** [comment]
@ithinkihaveacat good idea.

**Comment by ithinkihaveacat** [comment]
@jasti Are you okay with the suggested README text at https://github.com/ampproject/docs/issues/1862#issuecomment-482512518?
