### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by usmanyunusov** [ampproject/docs#1865]
https://github.com/ampproject/docs/blob/27f8b08dae6795aea860201901e0035cf21387de/examples/source/1.components/amp-web-push/index.html#L40

Page 404: https://amp.dev/documentation/examples/components/amp-web-push/amp-web-push-helper-frame.html

**Comment by sebastianbenz** [comment]
The URL is correct, but it looks like the router doesn't pickup the page. //cc @matthiasrohmer
