### ISSUE TITLE
amp-carousel component page failing to load preview images

### ISSUE THREAD

**Issue by KESchuettler** [ampproject/docs#1870]
## amp-carousel component page getting 404 responses from images in "preview tab"

Please provide:

- Page link:  
    - https://amp.dev/documentation/components/amp-carousel.html?format=websites
- Description of the documentation issue:
    - Clicking the "Preview" tab in the **Behavior** section renders an empty box

## How do we reproduce the issue?
Navigate to [the amp-carousel component page](https://amp.dev/documentation/components/amp-carousel.html?format=websites) and click any of the "Preview" tabs

What browser are you using? **Chrome**
What O/S are you using? **Debian and replicated on macOS High Sierra (10.13.6)**

**Comment by matthiasrohmer** [comment]
Thanks for the report! Is related to #1804 and we'll look into it shortly.

**Comment by sebastianbenz** [comment]
Will be fixed as part of #2053
