### ISSUE TITLE
amp.dev component pages still reference AMP By Example

### ISSUE THREAD

**Issue by noodles** [ampproject/docs#1889]
Some of the component pages on amp.dev still reference the AMP By Example site.

Example:

On [the amp-selector component page](https://amp.dev/documentation/components/amp-selector.html?format=websites), in the 'examples' section of the table at the top of the site, it says:

"See AMP By Example's [amp-selector example](https://ampbyexample.com/components/amp-selector/)."

The copy & the URL still reference AMP By Example

**Comment by matthiasrohmer** [comment]
Thanks for pointing that out! We're aware but all content in the Components section is coming from the ampproject/amphtml repository where it still needs to be updated 🙂

**Comment by matthiasrohmer** [comment]
Will be handled in ampproject/amphtml#21965.
