### ISSUE TITLE
[tip][/tip] tags visible on advanced tracking page 

### ISSUE THREAD

**Issue by noodles** [ampproject/docs#1890]
There are there are [tip][/tip] tags visible around the last 2 paragraphs on the [Tracking engagement with analytics](https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/tracking_data?referrer=ampproject.org) page. 

Screenshot: ![Screen Shot 2019-04-15 at 3 23 24 PM](https://user-images.githubusercontent.com/183972/56109107-7425a980-5f92-11e9-986e-fcdaa19d7329.png)

MacOS 10.14.4
Google Chrome - Version 73.0.3683.103

**Comment by sebastianbenz** [comment]
This has been fixed with the latest deployment.
