### ISSUE TITLE
White spaces should be removed from "Dev Ops"

### ISSUE THREAD

**Issue by chikoski** [ampproject/docs#1896]
## Description of the issue found on ampproject.org

This is a localization issue, which is found in [Japanese localized page for AMP Conf 2019](https://amp.dev/ja/events/amp-conf-2019). 

The second paragraph of the lead text is translated as "リッチ アニメーション、動的なコンテンツ、Dev Ops やマネタイゼーションなど、Web における良質なユーザー体験を実現するためのすべてを、一緒に見ていきましょう。皆さまにお会いできるのを心より楽しみにしています。"

However, "DevOps" is translated as "Dev Ops", however this translation would be incorrect. "DevOps" is translated into "DevOps" in usual case, i.e. we should remove the white space.

## How do we reproduce the issue?

1. Go [Japanese localized page of AMP Conf 2019](https://amp.dev/ja/events/amp-conf-2019).
2. Read the second paragraph of the lead text.

**Comment by matthiasrohmer** [comment]
That has been fixed by #1897 that you contributed 🙂Thanks!
