### ISSUE TITLE
Make Tools page format-filterable and add new tools

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#1914]
With especially that many stories related tools it might make sense to introduce format-filtering to the [Tools page](https://amp.dev/documentation/tools) and adding those tools in.

I know we've once voted against making this section much bigger, but I think this section would hugely benefit adding other (good quality) third-party tools.

@pbakaus, @CrystalOnScript, @sebastianbenz: WDYT?

**Comment by sebastianbenz** [comment]
Makes sense. Probably not right now, but definitely (hopefully) in the
future, Maybe a different kind of filtering would make more sense, e.g.:
Debugging, Building, Stories, Analytics, ...

**Comment by matthiasrohmer** [comment]
Fixed by #2015, thanks Paul!
