### ISSUE TITLE
Playground import template fails

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1926]
It tries to load templates from localhost: https://playground.amp.dev/?url=/static/samples/standalone/amp-ad/

**Comment by matthiasrohmer** [comment]
Writing the sitemap.json doesn't seem to happen reliably enough for gulp to pick it up when it collects the static files. Therefore it's then either outdated (wrong env) or missing at all if it had been cleaned before.

**Comment by sebastianbenz** [comment]
Categories are also broken

<img width="1071" alt="Screen Shot 2019-04-24 at 10 20 35" src="https://user-images.githubusercontent.com/380472/56643859-cc3b6a80-667a-11e9-9f17-c3fd156e7af4.png">

**Comment by matthiasrohmer** [comment]
Both fixed.
