### ISSUE TITLE
AMP Project issue  on Safari browser

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/docs#193]
Originally reported here https://github.com/ampproject/amphtml/issues/5217 by @YoavRheims 

---

## Short description of your issue:

The office AMP website is broken on Safari browser. 

## How do we reproduce the issue?

Just go to https://www.ampproject.org on Safari for Windows (5.1.7). It was tested on desktop PC.

## Which AMP version is affected?

Version 1474310684773

## Screenshot

![amp-safari](https://cloud.githubusercontent.com/assets/4377522/18813924/abb68134-8313-11e6-9cd2-525ed0b0df3e.png)

**Comment by cramforce** [comment]
AMP cannot and will not support Safari 5. By policy we only supports Safari 9 (latest 2) and we make an effort for 8.

**Comment by cramforce** [comment]
Also, please stop using it! This browsers hasn't received security updates in many years.

**Comment by YoavRheims** [comment]
Understood.
