### ISSUE TITLE
Links to components do not look clickable

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#195]
See https://www.ampproject.org/docs/reference/extended.html

The component names are clickable, but there is no indication for that.

**Comment by derekcecillewis** [comment]
I agree, a simple `text-decoration: underline;` should be good enough.

**Comment by syed-haroon** [comment]
Also, components like `amp-fx-flying-carpet` and `amp-user-notification` to fit in one line, `white-space: nowrap` need to be applied?
