### ISSUE TITLE
sxg: invalid response returned under HTTP/1.1

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#1952]
When accessed via HTTP/1.1, `amp.dev` seems to be returning a response whose length does not match the length declared via the content-length header:

```sh
# declared length is 156290
$ curl -D - -o /dev/null -s --http1.1 --raw -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1"' 'https://amp.dev/index.amp.html' | grep -i content-length
Content-Length: 156290
# actual length is 156304
$ curl -D /dev/null -o - -s --http1.1 --raw -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1"' 'https://amp.dev/index.amp.html' | wc -c
  156304
```

(This mismatch trips up node's HTTP parser.)

At least part of the problem seems to be a strange `26282` added to the start of the response. (See `curl -i -s --http1.1 --raw -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1"' 'https://amp.dev/index.amp.html' | less`. This prefix also seems to make `dump-signexechange -verify` upset.)

For some reason this problem does not affect HTTP/2:

```sh
# declared length 156290
$ curl -D - -o /dev/null -s --raw -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1"' 'https://amp.dev/index.amp.html' | grep -i content-length
content-length: 156290
# actual length 156290
$ curl -D /dev/null -o - -s --raw -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1"' 'https://amp.dev/index.amp.html' | wc -c
  156290
```

/cc @sebastianbenz @twifkak

**Comment by sebastianbenz** [comment]
Yeah, this is my hacky proxy replacement to check whether the node proxy I've been using was causing the problems. Will switch back to the old version soon...

**Comment by sebastianbenz** [comment]
Switched back to the old version. Thanks for looking into this. Michael!
