### ISSUE TITLE
Autosuggest popup in the Autosuggest example appears out-of-place

### ISSUE THREAD

**Issue by zhangsu** [ampproject/docs#1954]
## Description of the issue found on ampproject.org

Please provide:

- Page link: https://amp.dev/documentation/examples/interactivity-dynamic-content/simple_autosuggest/#text-input
- Description of the documentation issue
Autosuggest popup in the Autosuggest example appears out-of-place

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to the link above
2. Type "a" in the City input box
3. The autosuggest popup appears in a weird place. If you scroll the city input box to the bottom of the page, you probably won't see the popup since it would be off-screen.

What browser are you using?

Chrome Version 75.0.3766.2 (Official Build) dev (64-bit)

What O/S are you using?
Linux

**Comment by sebastianbenz** [comment]
That's working as intended. The popup appears above the code snippet triggering the popup. This is to demonstrate which code does which part of the sample. If you open the standalone demo via "View Demo" it'll work as expected.
