### ISSUE TITLE
"Add to Cart" in product page demo failing

### ISSUE THREAD

**Issue by demianrenzulli** [ampproject/docs#1996]
## Description of the issue found on ampproject.org

Please provide:

- Page link: https://amp.dev/documentation/examples/e-commerce/product_page/
- The "Add To Cart" functionality of the product page is failing ([the endpoint](https://amp.dev/samples_templates/product_page/add_to_cart?__amp_source_origin=https%3A%2F%2Famp.dev) being called is returning 404).

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to [product demo](https://amp.dev/documentation/examples/e-commerce/product_page/) and scroll down to the "add to cart section".
2. Click on "add to cart".

The endpoint being called returns 404.

## Proposed fix

The demo calls an endpoint uploaded to [this Glitch repo](https://glitch.com/~abe-cart-service).
We need to either add this logic to amp.dev server, or make sure that the page calls the appropriate endpoint, and the service contains the proper amp.dev headers for CORS.

Additionally, we need to check that the related [Shopping Cart demo](https://amp.dev/documentation/examples/e-commerce/shopping_cart/?referrer=ampbyexample.com) is working properly.

**Comment by matthiasrohmer** [comment]
@keevkeev, try to migrate the endpoint according to the existing `amp-live-list` sample.
