### ISSUE TITLE
Suggestion: amp.dev/stories should redirect to stories landing page

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#2008]
https://amp.dev/stories currently 404s, but it would be a great URL to redirect to https://amp.dev/about/stories

**Comment by matthiasrohmer** [comment]
Hm... currently we don't have any internal redirects as previously on ampproject.org but the only redirects are the new go.amp.dev links where there's also one for the stories page: go.amp.dev/stories 🙂Is amp.dev/stories then needed as well? WDYT?

**Comment by rudygalfi** [comment]
My sense is go links really shine when the path is long and the page is deep in the hierarchy. amp.dev/stories is clearly better than go.amp.dev/stories, which nobody is ever going to think to type.

I don't feel strongly here, but to the extent that we want the best URLs for jumping into the pages about specific uses of AMP, paths like /stories, /email, and /ads will be the optimum for URLs that appear in slides or spoken aloud.

**Comment by mattludwig** [comment]
Strong endorsement on my side for having direct paths for stories, emails, ads. Unless there are technical reasons not to do this or @pbakaus disagrees, let's do it.

**Comment by matthiasrohmer** [comment]
Nothing that holds us back technically and I guess Paul won't veto 😁Going to add this for one of the next releases.

**Comment by pbakaus** [comment]
You're guess is correct :) Let's make it happen.

**Comment by matthiasrohmer** [comment]
https://amp.dev/ads
https://amp.dev/docs
https://amp.dev/email
https://amp.dev/learn
https://amp.dev/samples
https://amp.dev/stories
https://amp.dev/websites

Work for the start!
