### ISSUE TITLE
ALP vs. AMP

### ISSUE THREAD

**Issue by vilav** [ampproject/docs#202]
Hello

Some guidance / docs on the difference between ALP and AMP would be very helpful.

Thanks

**Comment by bpaduch** [comment]
@jasti - Can you comment on this?  Are there docs that contrast the two?

**Comment by pbakaus** [comment]
Standalone in formation about ALP/A4A is in the works, but not ready yet. Assigning this one to @jasti.

**Comment by jasti** [comment]
@vilav Can you clarify your question?
If I am understanding you - an ALP is just an AMP page but specifically for the ads usecase, we perform some optimizations.
You can read about it here: https://amphtml.wordpress.com/2016/08/11/fast-ad-landing-pages-with-amp/

**Comment by bpaduch** [comment]
@vilav - friendly ping.

**Comment by bpaduch** [comment]
Closing issue for now; if it's still a problem, please reopen.
