### ISSUE TITLE
Broken links on Supported CSS page

### ISSUE THREAD

**Issue by P3N5K4** [ampproject/docs#203]
On the "Supported CSS" page, in the Custom Fonts Exception section there are 2 external links:

https://fast.fonts.net
https://fonts.googleapis.com

Both of these give a 404 error when followed.

To reproduce:

1. Navigate to https://www.ampproject.org/docs/guides/responsive/style_pages.html#the-custom-fonts-exception

2. Click either of the external links

**Comment by P3N5K4** [comment]
I've just re-read the page - it's listing the accepted origins.
Maybe these shouldn't be links?

**Comment by pbakaus** [comment]
Good catch! Fixed with the next deploy.
