### ISSUE TITLE
Suggestion: Add an anchor to story examples on story overview page

### ISSUE THREAD

**Issue by mattludwig** [ampproject/docs#2037]
Would it be possible to put an anchor on the "Check out AMP stories on the web" section of the Stories About page? This would let some of our team directly link to the examples as a showcase of stories on the web. Something like: https://amp.dev/about/stories/#examples

**Comment by sebastianbenz** [comment]
it'll be: https://amp.dev/about/stories#check-out-amp-stories-on-the-web
