### ISSUE TITLE
broken on iphone6+

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/docs#204]
![img_2361](https://cloud.githubusercontent.com/assets/354746/19004336/5173aada-870a-11e6-8be7-984974fafce8.PNG)

**Comment by erwinmombay** [comment]
@pbakaus think you have this handled but let me know if i can help in any way

**Comment by pbakaus** [comment]
Fixed via https://github.com/ampproject/docs/commit/0de42aa81dddf5d7c7f0bf2eb9cbc29937ddb20d
