### ISSUE TITLE
AMP for Email playground examples don't load

### ISSUE THREAD

**Issue by johnbarr** [ampproject/docs#2058]
## Description of the issue found on ampproject.org

Please provide:

- Page link: https://playground.amp.dev/?runtime=amp4email
- Description of the documentation issue

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to https://playground.amp.dev/?runtime=amp4email
2. Select an example from the drop down menu
3. See "Could not fetch template"

What browser are you using? Chrome
What O/S are you using? Linux

**Comment by sebastianbenz** [comment]
@matthiasrohmer https://amp.dev/static/samples/samples.json links to localhost

**Comment by matthiasrohmer** [comment]
Fixed.
