### ISSUE TITLE
Parse title from URL for email samples in playground

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2059]
...otherwise the playground won't show a title in the header

**Comment by sebastianbenz** [comment]
A title doesn't really make sense for emails, but it's not invalid either.

**Comment by sebastianbenz** [comment]
@fstanis let me know if you have a better idea how to add a title to email samples.

**Comment by fstanis** [comment]
I don't think `<title>` is a good idea. Feedback so far shows it confuses users since they wrongly assume it changes the subject and I think we should move to disallow it in the validator.

Could we use something like `<h1>`? If that doesn't work, maybe a meta attribute?

**Comment by matthiasrohmer** [comment]
I think (@sebastianbenz, correct me if I am wrong) the initial background on this is that the sample parser relies on the `<title>` element to define a title for the sample which is then used for the `<title>` element on sample documentation, preview and source documents.

WDYT about adding a frontmatter key `title` to the email samples which takes precedence over the `<title>` element?

**Comment by fstanis** [comment]
So this would be a like a meta attribute, e.g.

```
<!---
preview: amp4email
skipValidation: 'true'
title: 'Hello World Email'
--->
```

If so, I agree.

**Comment by fstanis** [comment]
#2096 should add this functionality

**Comment by sebastianbenz** [comment]
Originally on ampbyexample, the file name defines the title if no `<title>` is defined. This is still the case and I would like to keep it. The problem is: the playground uses the title attribute to show a title in the header. For now, we can fix this by also using the filename in the playground if no `<title>` is defined.
