### ISSUE TITLE
SMBs Landing page for AMP

### ISSUE THREAD

**Issue by Christosap** [ampproject/docs#207]
Create a landing page for less savvy implementers of AMP

**Comment by bpaduch** [comment]
@Christosap - With the newly redesigned site, do you still see the need for SMBs landing page?

**Comment by Christosap** [comment]
yeap

Christos Apartoglou
Google Inc.
111 8th Ave
New York, NY 10011

**Comment by bpaduch** [comment]
Closing due to new direction of IA - where all audiences will be covered.
