### ISSUE TITLE
amp-form Page is Blank 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#2076]
Doesn't even display 404:

https://amp.dev/documentation/components/amp-form?format=websites

**Comment by sebastianbenz** [comment]
I cannot reproduce. @CrystalOnScript can you provide more info?

**Comment by KESchuettler** [comment]
@sebastianbenz I am having this same issue this morning. It appears to only affect the amp-form page (no other component page is mimicking this behavior).

More info:

The page is loading, but the ```<body>``` tag is empty, though the ```<head>``` tag is importing various AMP component scripts. 

Occurred using Chrome 74 on both Linux and MacOS machines. 

![Screenshot from 2019-05-14 10-53-32](https://user-images.githubusercontent.com/8907103/57707992-931d6700-7636-11e9-8b70-0963b14d4509.png)
![Screenshot from 2019-05-14 10-52-49](https://user-images.githubusercontent.com/8907103/57707993-931d6700-7636-11e9-99cf-340208c81f1a.png)

**Comment by CrystalOnScript** [comment]
+1 to @KESchuettler said - I'm experiencing the same thing on Chrome 74 on MacOS and my Pixel phone.

**Comment by sebastianbenz** [comment]
Is it only the amp-form page?

>

**Comment by KESchuettler** [comment]
I clicked through maybe 10 different components and had no issue. I can try to verify if necessary.

**Comment by johnbarr** [comment]
I'm experiencing this on the amp-animation in Chrome 74.0.3729.131 on Linux
https://amp.dev/documentation/components/amp-animation

**Comment by sebastianbenz** [comment]
Can someone please curl the URL and check whether the body gets included then.

**Comment by sebastianbenz** [comment]
Another thing: can someone please try https://amp.dev/documentation/components/amp-form?random-parameter-to-bust-the-cdn and see if it works.

**Comment by KESchuettler** [comment]
@sebastianbenz 
```$ curl -v --silent https://amp.dev/documentation/components/amp-form?format=table``` command returns body content. Navigating to the same link does not. I used ```?donald=duck``` as well with same results. Also tried both pages with FireFox to no avail. 

+1 to @johnbarr. ```amp-animation``` page was also broken for me, though the ```curl``` command succeeded with a response ```<body>```.

**Comment by sebastianbenz** [comment]
It should be working again. The VMs located in the US were returning broken responses for these two pages. The other VMs running in Europe (with the same version of the site) worked fine. 

It seems to be related to your compression middleware (shrink-ray) as:

`curl 'http://localhost:80/documentation/components/amp-form' --compressed` => failed
`curl 'http://localhost:80/documentation/components/amp-form'` => worked

**Comment by KESchuettler** [comment]
@sebastianbenz Confirmed working.

**Comment by CrystalOnScript** [comment]
Works for me too! Woop!

**Comment by johnbarr** [comment]
Works for me too now. amp-form and amp-animation

**Comment by matthiasrohmer** [comment]
@sebastianbenz, close as it's currently fixed and (hopefully) doesn't seem to be a persisting issue?
