### ISSUE TITLE
List of all ad tech vendors supporting AMP

### ISSUE THREAD

**Issue by Christosap** [ampproject/docs#208]
Analytics, Video, Ad networks, embeds etc This will replace the who page

**Comment by ivenckus** [comment]
Hi,

Please add http://site.adform.com/ to the Ads section. We have been one of the first companies adopting AMP but for some of the reason we are not in this list - https://www.ampproject.org/learn/who/

Thanks!

**Comment by bpaduch** [comment]
Fixed on Oct 26 via #240
