### ISSUE TITLE
ampbyexample amp-lightbox-gallery URL redirects to amp-lightbox which is a different component

### ISSUE THREAD

**Issue by aghassemi** [ampproject/docs#2089]
https://ampbyexample.com/components/amp-lightbox-gallery/ redirects to https://amp.dev/documentation/examples/components/amp-lightbox (which is a different component) instead of https://amp.dev/documentation/examples/components/amp-lightbox-gallery/ which is the correct Url.

**Comment by sebastianbenz** [comment]
Fixed by https://github.com/ampproject/amp-by-example/commit/a64b263eaa7bdb2b5488c27b0ad593c21dd672a4
