### ISSUE TITLE
Restore missing features on roadshows map

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#2094]
As per #2085 : 

The Roadshow Cities map on https://amp.dev/events/amp-roadshow lacks the dots I added on ampproject.org for Africa. Would love to get those back.

We used to add in new cities by creating a dot for each city that was absolutely positioned to resemble its actual location. This system was imperfect but worked. Can we get that, or something like it, back?

I also liked that dots for upcoming cities used to flash... 😄

**Comment by matthiasrohmer** [comment]
@keevkeev, is that something you could take care of?

**Comment by keevkeev** [comment]
@matthiasrohmer yeah, I'll have a look at a nice solution

**Comment by sebil** [comment]
Hey @morsssss I've created a PR for this #2310 
I've tried to find the same spots for the cities as before and added the missing ones for africa freestyle.
Feel free to adjust the coordinates of all cities how you'd like it the best.
