### ISSUE TITLE
Search results leads to 404

### ISSUE THREAD

**Issue by westonruter** [ampproject/docs#2098]
I did a Google search for `site:https://amp.dev/ amp keyframes` and a result was:

![image](https://user-images.githubusercontent.com/134745/57811720-e3242880-771f-11e9-83dd-4975db921289.png)

However, https://amp.dev/tr/docs/fundamentals/spec goes to a 404:

![image](https://user-images.githubusercontent.com/134745/57811766-ff27ca00-771f-11e9-8f78-417a10a18754.png)

**Comment by sebastianbenz** [comment]
Thanks for reporting, looks like the index is not yet fully up-to-date. Searching for `amp spec` still shows the old ampproject.org URL. I don't think there's anything we can do except wait.

**Comment by westonruter** [comment]
Shouldn't redirects be put in place? What if someone linked to that page from their site?

**Comment by matthiasrohmer** [comment]
There are redirects in place but it's sadly really the index that's doing strange things here. The old URL https://ampproject.org/tr/docs/fundamentals/spec actually redirects to the new location on amp.dev but Google Search somehow combined source and target to a non-working URL.

And also makes languages randomly appear in SERPs.
