### ISSUE TITLE
Image assets point to firebase path 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#2100]
Guides and component documentation that feature images don't have the correct image path. They still point to firebase. Such as:

- [Include images & video](https://amp.dev/documentation/guides-and-tutorials/develop/media_iframes_3p/?format=websites)
- [amp-carousel](https://amp.dev/documentation/components/amp-carousel?format=websites)

**Comment by sebastianbenz** [comment]
@tharders can you take a look at this?

**Comment by matthiasrohmer** [comment]
Thanks for bringing this up again, @CrystalOnScript! Them pointing to Firebase actually wasn't really the issue but the path resolving wasn't working with trailing slashes added to the inline sample URLs per configuration.

They now all seem to be fixed (together with #1804 and #1870) - additionally we're currently working on updating them to the new look in #2053 🙂
