### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#211]
See example query https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=amp-video

![Google.com](http://i.imgur.com/SHTTnIt.png)

Both the docs and ABE should have proper meta tags or JSON-LD for descriptions. The current descriptions contain some unneeded word like the literal "Description".

It would be neat if we find a way to tell Google that our docs site is a better resource than the Github itself. Maybe we could do that by linking from the GitHub MD file to the respective main docs site resource.

CC @sebastianbenz

**Comment by bpaduch** [comment]
@cramforce  -  I tried the same query and the docs and ABE are at the top.  Not sure who fixed it, but it appears to be fixed. Yes?

**Comment by cramforce** [comment]
Awesome. Maybe we just rank better now.

We could consider to update the title, though 

"amp-video – reference documentation"

Would be much more helpful than "amp-video – Accelerated Mobile Pages Project"

**Comment by pbakaus** [comment]
I fixed this two days ago or so, actually – crazy how fast the index
updated. Agree we can improve the title further. I had some really
elaborate title management in there at some point, not sure where it went.

**Comment by cramforce** [comment]
Would be cool if we'd also update ampbyexample in line. We often rank at 1 and 2 and it would be good if people could choose between them just from the title.

**Comment by sebastianbenz** [comment]
Makes sense. How about "amp-video - samples & code" for ABE?

**Comment by cramforce** [comment]
LG, Maybe "annotated samples & code", but that extra word is not all that useful :)

**Comment by pbakaus** [comment]
Closing this here as it seems the last bit concerns ABE. Can you open a new bug on ABE if needed? Thanks!
