### ISSUE TITLE
Broken frontmatter for amp-connatix-player

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2111]
<img width="1110" alt="Screen Shot 2019-05-16 at 20 17 16" src="https://user-images.githubusercontent.com/380472/57878907-71c9a000-781b-11e9-8fb9-4c4a146eb463.png">

**Comment by matthiasrohmer** [comment]
Has been fixed by https://github.com/ampproject/amphtml/commit/b8f083c11f0eb01b8be32a2c3020e1c7c29db48c#diff-5d9b8861703f862d368d0fb8e42e9f80.
