### ISSUE TITLE
Component docs: add margin below validation section

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2112]
See screenshot:

<img width="851" alt="Screen Shot 2019-05-16 at 20 16 34" src="https://user-images.githubusercontent.com/380472/57878958-932a8c00-781b-11e9-8ceb-f4bda747c5a6.png">

**Comment by robertdudaa** [comment]
I would like to take up this issue.

**Comment by sebastianbenz** [comment]
Great! Thanks for your help!
