### ISSUE TITLE
Resizable amp-iframe example is broken (Origin of <amp-iframe> must not be equal to container)

### ISSUE THREAD

**Issue by westonruter** [ampproject/docs#2115]
See https://amp.dev/documentation/examples/components/amp-iframe/#resizable-iframe

The `amp-iframe` is blank:

![image](https://user-images.githubusercontent.com/134745/57889468-bdfbec80-77e9-11e9-823e-e995959b7e00.png)

An error is raised: `Origin of <amp-iframe> must not be equal to container`

![image](https://user-images.githubusercontent.com/134745/57889526-e1269c00-77e9-11e9-8f94-f372b1648bd2.png)

Errors are also being raised on the playground: https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-iframe

![image](https://user-images.githubusercontent.com/134745/57889579-04e9e200-77ea-11e9-8a28-c28e62f8a56d.png)

**Comment by westonruter** [comment]
@matthiasrohmer @lluerich The resizable iframe is now loading, but…

![image](https://user-images.githubusercontent.com/134745/58059388-7cd54680-7b21-11e9-94bc-45cf758d6122.png)

It is _not_ resizing:

![image](https://user-images.githubusercontent.com/134745/58059404-878fdb80-7b21-11e9-9351-d0b422aead11.png)

Clicking the button has no effect.

Same is true on https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-iframe

![image](https://user-images.githubusercontent.com/134745/58059446-c4f46900-7b21-11e9-889f-e66a3f26f810.png)

![image](https://user-images.githubusercontent.com/134745/58059452-cb82e080-7b21-11e9-9df2-a8e05b282d0f.png)

**Comment by westonruter** [comment]
@matthiasrohmer @lluerich This is still broken. The issue should be re-opened.

**Comment by matthiasrohmer** [comment]
Yes indeed, thanks for flagging @westonruter. We are currently investigating what's the actual issue here as at least the resizing is implemented as documented.
