### ISSUE TITLE
AMP Story samples are missing the bookend

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2124]
On ampbyexample this used to be an endpoint listing all story samples:

https://amp.dev/json/bookend.json?__amp_source_origin=https%3A%2F%2Fpreview.amp.dev

**Comment by dlemm** [comment]
Closed, because changes are live already. Changes were made in the example/source/ files for the example stories. The links were changed from ```<% hosts.platform %>/json/bookend.json``` to ```<% hosts.platform %>/static/samples/json/bookend.json``` in order to get the social share screen at the end of the example stories.
