### ISSUE TITLE
CSS animations are not whitelisted as it says in the docs

### ISSUE THREAD

**Issue by johnbarr** [ampproject/docs#2125]
## Description of the issue found on ampproject.org

Please provide:

- Page link: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages#restricted-styles
- Description of the documentation issue
This whole section "Restricted styles" section on "transition property" and "@keyframes {...}" should be deleted. There is no whitelist on the properties used by these CSS rules.

From Greg: "Documentation bug. AMP wanted to do that, but didn't have a CSS parser in the validator early enough in the history, so it's too late now."

## How do we reproduce the issue?

Paste the attached example (which uses CSS animation on the "padding" property) into the playground and see it pass validation and work.

[css_animation_example.txt](https://github.com/ampproject/docs/files/3192236/css_animation_example.txt)

**Comment by sebastianbenz** [comment]
Yes, this already has caused quite a bit of confusion. However, we should keep the section, but rephrase it as a performance recommendation. 

//cc @pbakaus @aghassemi

**Comment by CrystalOnScript** [comment]
Ah yup, I know this one 😅. I'll do some rephrasing. Thanks!
