### ISSUE TITLE
Force experiment variant not working

### ISSUE THREAD

**Issue by agusmoles** [ampproject/docs#2138]
## Description of the issue found on ampproject.org

Link: https://amp.dev/documentation/examples/components/amp-experiment/?format=websites

## How do we reproduce the issue?

Clicking any of the 3 links of the Development Tip tittle. 

What browser are you using? Google Chrome
What O/S are you using? Windows 10

**Comment by sebastianbenz** [comment]
Thanks for reporting. The links are broken and need to be:

https://amp.dev/documentation/examples/components/amp-experiment/?format=websites#amp-x-button-color-experiment=2

>
