### ISSUE TITLE
Text not correctly translated in Italian

### ISSUE THREAD

**Issue by kul3r4** [ampproject/docs#214]
Go to [link](https://www.ampproject.org/it/learn/how-amp-works/), the menu contains:
Learn

Che cos’è AMP?
Who uses AMP?
Il metodo di AMP per ottimizzare le prestazioni
Design Principles

Basically, half of it is in Italian and half in English.

**Comment by pbakaus** [comment]
This is by design – rather than not showing the other, not translated pages, we think it's better to show the fallback in english.
