### ISSUE TITLE
Make translation notification actionable

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2157]
Currently, we show a notification to help us translate the page,  but don't tell how to actually do it. Ideally, we'd be linking to an explainer on how to help us translating. 

@CrystalOnScript have we already got a link to an explainer? 
@matthiasrohmer / @sebil can you do the integration?

**Comment by techhtml** [comment]
I think this link can help translators:
https://github.com/ampproject/docs/blob/future/TRANSLATIONS.md

**Comment by CrystalOnScript** [comment]
+1 to @techhtml - that link should work for now!
