### ISSUE TITLE
Validation issue on home page

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#216]
It looks like a recent deployment introduced a validation issue on pages.

For the home page, ampproject.org, I see 1 error:

The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '//fonts.googleapis.com/css?family=Material+Icons'.

**Comment by pbakaus** [comment]
So icon fonts aren't allowed in AMP? If so, our bug is that we don't document it. /cc @cramforce

**Comment by cramforce** [comment]
I think this is just the missing `https:`

**Comment by pbakaus** [comment]
aaaah. OK, easy fix :)

**Comment by pbakaus** [comment]
Fixed.
