### ISSUE TITLE
amp-addthis meta text update

### ISSUE THREAD

**Issue by chadhedmonds** [ampproject/docs#2168]
## Description of the issue found on ampproject.org

- Page link: https://amp.dev/documentation/components/amp-addthis?format=websites
- Matt Ludwig recommended I set up a ticket to have the meta text updated for our AddThis component. Currently, it reads, “Displays an AddThis website tools embed.” and we would like to change this to "Displays [AddThis](https://www.addthis.com/)’ customizable social share buttons."
 
Please let me know if this request can be completed or if you need additional information.

**Comment by sebastianbenz** [comment]
That's no problem. Please create a PR with the suggested changes here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-addthis/amp-addthis.md. The component docs are maintained in the amphtml repository.

**Comment by matthiasrohmer** [comment]
@dlemm, can you please check if this has been done and otherwise create the PR yourself?
