### ISSUE TITLE
Allow go.amp.dev to append the rest of the path to target

### ISSUE THREAD

**Issue by fstanis** [ampproject/docs#2182]
Edit: moved part of suggestion to #1860

Would be great to extend `go.amp.dev` to append suffixes, so that e.g. `go.amp.dev/docs/start/create/` would redirect to `https://amp.dev/documentation/guides-and-tutorials/start/create/` if `go.amp.dev/docs` redirects to `https://amp.dev/documentation/guides-and-tutorials`.

This would then allow us to create e.g. `go.amp.dev/component/amp-form` if we only add `go.amp.dev/component` to [go-links.yaml](https://github.com/ampproject/docs/blob/future/platform/config/go-links.yaml).

**Comment by matthiasrohmer** [comment]
We've discussed at least a component shortlink in #1860: the proposed scheme there was either just `go.amp.dev/amp-img` or `go.amp.dev/c/amp-img`. But I also like your first idea.

Introducing another subdomain additionally to the many we already have seems a bit irritating, at least for me.

**Comment by fstanis** [comment]
Ah, apologies, let's continue the component-specific discussion there then.

I think the link suffix idea for `go.amp.dev` is useful regardless of what we decide, so keeping this open for discussing that.

**Comment by fstanis** [comment]
**My plan to implement this:**

Modify go-links.yaml to accept either:

- `string` URL to redirect to (current behaviour)
- `object` that can have the following fields:
    - `url` URL based to redirect to
    - `includePath` optional boolean that determines whether to append the path suffix

In other words, these two would become equivalent:

```yaml
/ads: /about/ads
```

```yaml
/ads:
  url: /about/ads
```

And this entry would allow `go.amp.dev/c/amp-form` style redirects as discussed in #1860:

```yaml
/c:
  url: https://amp.dev/documentation/components/
  includePath: true
```

This would make `go.amp.dev/c` redirect to `https://amp.dev/documentation/components/` and `go.amp.dev/c/amp-form` redirect to `https://amp.dev/documentation/components/amp-form`.

I'm planning to implement this some time this week. Let me know if you have any feedback / comments on the proposal.

**Comment by sebastianbenz** [comment]
How about making this more generic via regex: 

* `/c/amp-(.*): /documentation/components/amp-$1`
* `/s/amp-(.*): /documentation/examples/components/amp-$1`

In any case, can you please add tests for the redirects when implementing this? We should have tests for the regex based redirects (and ideally check that all redirects are valid URLs). 

Tests go into the same dir as the implementation, e.g. `redirects.js -> redirects.test.js`. I've got an open PR which adds Jest as test runtime using this pattern.

**Comment by fstanis** [comment]
I like that better. In that case, instead of `includePath` flag in my original proposal, I'll add one `useRegex`.

The main problem I see is having two regexes that overlap. I'll add a test that checks if a regex overlaps with any existing non-regex route, but we'll need to keep track of overlapping regexes manually.
