### ISSUE TITLE
how to create AMP Cache?

### ISSUE THREAD

**Issue by Christosap** [ampproject/docs#219]
Do we have any instructions for platforms?

**Comment by pbakaus** [comment]
I don't think this should live on the homepage – it's too specific. @pietergreyling has been working on it, I think.

**Comment by Christosap** [comment]
lol ok :) Sorry just trying to find what we need :)

**Comment by pietergreyling** [comment]
The current AMP Cache Guidelines are under `/amphtml/spec` on the main project:
https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md

Sorry for the inconvenience :)
