### ISSUE TITLE
Fix sidebar scrolling behaviour

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#2195]
The sidebar scrolling/nesting behaviour is really off currently and needs an update. See #1652 for history.

**Comment by matthiasrohmer** [comment]
@sebil, just noticed the TOC sidebar has a similar problem as the one on the left. What do you think? Is this also fixable?

**Comment by sebil** [comment]
This is already fixed with the same PR for the sidebar.

**Comment by sebil** [comment]
I just added a new PR #2266 for more improvements.
