### ISSUE TITLE
Get rid of amp-font on amp.dev

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#2207]
@cramforce wants us to get rid of `<amp-font>`, and use `font-display` instead.

While we're here Malte: If you don't want folks to use amp-font anymore, maybe we should add that as disclaimer to https://amp.dev/documentation/components/amp-font and deprecate the component?

**Comment by cramforce** [comment]
Yes, let's deprecate and point people to `font-display`. Especially now that Google Fonts finally has display support

**Comment by pbakaus** [comment]
Got it.

@nainar @aghassemi can you help me route this to the right person to do the work on the eng side (deprecating amp-font)? 

In the meantime, I'll remove from amp.dev.

**Comment by aghassemi** [comment]
@pbakaus https://github.com/ampproject/amphtml/issues/22623

**Comment by matthiasrohmer** [comment]
Fixed by #2226.
