### ISSUE TITLE
Is the heights attribute documented anywhere?

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#221]
CC @dvoytenko 

I think we should either document it or kill it.

I recently saw that there was some standards work in this direction (like a `h` descriptor in srcset).

**Comment by pbakaus** [comment]
what is the heights attribute? :) (answer is no, it's not documented)

**Comment by dvoytenko** [comment]
It's definitely documented. In the https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#heights

IMHO it makes a lot of sense and parallels well the `sizes` attribute.

**Comment by pbakaus** [comment]
nice one! I'll add it to the actual docs then.

**Comment by pbakaus** [comment]
Fixed: https://www.ampproject.org/docs/guides/responsive/art_direction
