### ISSUE TITLE
Broken link to AMP Story

### ISSUE THREAD

**Issue by amedina** [ampproject/docs#2216]
## Description of the issue found on ampproject.org

Outgoing link broken: 
https://www.mic.com/stories/327/what-happens-in-your-brain-when-you-listen-to-music

Linked from "This AMP story from Mic.com is a good example of using minimal text and full screen portrait images and video to give the reader a good understanding of the topic."

In page:
https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices

**Comment by matthiasrohmer** [comment]
Has been fixed by #2301.
