### ISSUE TITLE
Monetize your AMP page with ads Ads vendors

### ISSUE THREAD

**Issue by IXMark** [ampproject/docs#2227]
## Description of the issue found on ampproject.org

Please provide:

https://amp.dev/it/documentation/guides-and-tutorials/develop/monetization/ads_vendors?format=websites

Was #1318 created just to build the content page or was someone supposed to be moving content over too

**Comment by IXMark** [comment]
Old ticket that was closed- https://github.com/ampproject/docs/issues/1318

**Comment by akashagrjsr** [comment]
Why is page https://amp.dev/it/documentation/guides-and-tutorials/develop/monetization/ads_vendors?format=websites 

not available?

**Comment by matthiasrohmer** [comment]
No, the content has actually moved to the [Platform & Vendor partners](https://amp.dev/it/community/platform-and-vendor-partners) page. See the sections "Ads".

Thanks for the hint that the deprecated page is still there. Going to remove this!

**Comment by matthiasrohmer** [comment]
Instead of removing it I updated the page to forward visitors to the Platform & Vendor partners page.
