### ISSUE TITLE
Markdown format does not support code blocks inside a list

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2235]
For example:

<pre>
1. First...
   ```
   Code
   ```
2. Second....
3. Third...
</pre>

Does not render the code inside `code` and not a `pre`. 

This doesn't work either, as the enumeration resets to `1` after the code block.

<pre>
1. First...
```
   Code
```
2. Second....
3. Third...
</pre>

**Comment by matthiasrohmer** [comment]
That's a limitation of python-markdown. The following syntax works - though it is not really straightforward:

```
1. First... [sourcecode:html]
<html>
    <p>Indented content.</p>
</html>[/sourcecode]
2. Second....
3. Third...
```

**Comment by sebastianbenz** [comment]
//cc @CrystalOnScript we should document that
