### ISSUE TITLE
I find the Learn/Build distinction very confusing

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#224]
But maybe that is just me.

**Comment by pbakaus** [comment]
any other proposals?

**Comment by bpaduch** [comment]
Learn/Develop?

**Comment by derekcecillewis** [comment]
It may sound cliché, but what if it was "About" instead of "Learn"? "Develop" instead of "Build" sounds good to me too.

**Comment by cramforce** [comment]
I'd consider merging them into "Docs"

**Comment by pbakaus** [comment]
"About" and "Docs" works for me. I'll also rename "Guides" to "Documentation", as the tutorials are really guides. @ericlindley-g @rudygalfi thoughts?

**Comment by rudygalfi** [comment]
SGTM

**Comment by pbakaus** [comment]
Done! Let's see if that works better.
