### ISSUE TITLE
Robots.txt for subdomains

### ISSUE THREAD

**Issue by tharders** [ampproject/docs#2251]
The subdomains currently have no own robots.txt.

https://playground.amp.dev/robots.txt
https://go.amp.dev/robots.txt
https://preview.amp.dev/robots.txt
https://log.amp.dev/robots.txt

For go we get a 404.
The other redirect to the amp.dev/robots.txt.

For preview and log a robots.txt should be returned that disallows all.
For playground and go we might return a robots.txt that allows all, but a redirect to the amp.dev/robots.txt is not so nice, since we have site specific rules there.

**Comment by tharders** [comment]
@sebastianbenz Do you have any specific requirements for the subdomain robots.txt files?

**Comment by sebastianbenz** [comment]
Good find! We should fix this (the redirect is not intentional). 

I agree with your suggestions except for log.amp.dev:

* playground -> allow all
* preview -> disallow all
* go -> allow all
* log -> allow all (the error pages can be valuable in the future once we add more relevant information).
