### ISSUE TITLE
Align path for 'optimize & measure' pages

### ISSUE THREAD

**Issue by tharders** [ampproject/docs#2261]
The analytics pages below the 'optimize & measure' pages have a different parent path ('optimize-measure' vs 'optimize-and-measure')

https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange?format=websites
https://amp.dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/?format=websites

Maybe we want to align those folder names.
If we change this, the redirects on ampproject.org must also change.
For example https://www.ampproject.org/docs/analytics/analytics_basics

**Comment by sebastianbenz** [comment]
+1 to aligning the folder names. We need to setup redirects on amp.dev as well, which would also fix the problem with redirects from amp project.org.
