### ISSUE TITLE
Gradient makes code samples hard to read.

### ISSUE THREAD

**Issue by calebcordry** [ampproject/docs#2284]
## Description of the issue found on ampproject.org

Please provide:

Most obvious on large code samples like the editor in https://playground.amp.dev/

I would imagine that white text on whiteish background is bad for accessibility. It looks a bit like there is a glare on the screen. 

With gradient:
![image](https://user-images.githubusercontent.com/16087874/59060118-3c7e0400-8855-11e9-9455-eeab8bdf2ec6.png)

Without gradient:
![image](https://user-images.githubusercontent.com/16087874/59060245-88c94400-8855-11e9-8539-a3a9ffb5a99f.png)

**Comment by matthiasrohmer** [comment]
Thanks for flagging @calebcordry, we were already aware of this when we were first implementing it but went for the fancyness instead of the experience. We'll work on getting the colors better.
