### ISSUE TITLE
AMP Story best practices: some examples now 404

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#2287]
Several outlinks to example AMP Stories from the [Best practices for creating an AMP story](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices) now 404, including:

- https://mic.com/stories/327/what-happens-in-your-brain-when-you-listen-to-music
- https://mic.com/stories/500/did-you-know-these-fun-facts-about-stan-lee

These seem to have completely disappeared from the internet? We should remove and replace with alternatives.

/cc @newmuis @rudygalfi @vinaymahag

**Comment by vinaymahag** [comment]
For the first mic.com link, let's switch to this WaPo [story](https://www.washingtonpost.com/world/2018/07/16/amp-stories/why-india-has-million-stray-cows-roaming-country/). The sentence will read: 

> This [AMP story](https://www.washingtonpost.com/world/2018/07/16/amp-stories/why-india-has-million-stray-cows-roaming-country/) from The Washington Post is a good example of using minimal text and full screen portrait images and video to give the reader a good understanding of the topic.

For the second mic.com link, let's use this [story](https://www.cnn.com/ampstories/travel/12-beautiful-reasons-to-visit-italy) from CNN. The sentence will read:

> This [AMP story](https://www.cnn.com/ampstories/travel/12-beautiful-reasons-to-visit-italy) from CNN about traveling in Italy makes it easy to see at-a-glance who published the story and how recent it is.

**Comment by newmuis** [comment]
@CrystalOnScript are you able to help with this?
