### ISSUE TITLE
Custom fonts docs are out of date and misleading

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#229]
See
https://www.ampproject.org/docs/guides/responsive/style_pages#the-custom-fonts-exception

1. The list of whitelisted providers is stale. The full is is here https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#custom-fonts
2. We should emphasize that people can use `@font-face` completely freely. It is only that if they want to use a font provider from the list above that there is anything to worry about.

**Comment by pbakaus** [comment]
Fair point. Enjoy: https://www.ampproject.org/docs/guides/responsive/custom_fonts
