### ISSUE TITLE
What happened to this link!?

### ISSUE THREAD

**Issue by richardpringle** [ampproject/docs#23]
https://github.com/ampproject/docs/blob/master/docs/guides/validate.html

It's the last link on this page: `https://github.com/ampproject/docs/blob/master/_get_started/about-amp.md`

**Comment by Meggin** [comment]
These are actually legacy docs, and I should remove them!

Docs now live on ampproject.org.

Keeping this issue alive until I remove legacy content.

**Comment by Meggin** [comment]
I've added deprecation warnings to the two remaining docs in the /docs folder. Docs now live in ampproject.org. Original set of docs in /docs were for developer preview only.
