### ISSUE TITLE
Translate custom fonts page into korean

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#230]
I've just updated the custom fonts docs, and created this new page in support: https://www.ampproject.org/docs/guides/responsive/custom_fonts

https://www.ampproject.org/docs/guides/responsive/style_pages#the-custom-fonts-exception is now much shorter and links to the new page.

This is a tracking bug to make sure the korean translation gets updated.

**Comment by techhtml** [comment]
I've complete translation that,
if previous translation will merged, i'll send pull request.

korean translation commits are here:
https://github.com/techhtml/docs/commit/6312caa3c2f7e0a302fb3fab53bbcfdee44b4c3a

**Comment by techhtml** [comment]
This issues been done.
@pbakaus

**Comment by pbakaus** [comment]
Awesome, thanks again! BTW – if you want to translate the high level UI as well in the future, you can do it here: https://github.com/ampproject/docs/blob/master/translations/ko/LC_MESSAGES/messages.po
