### ISSUE TITLE
Hides menu on support page because footer comes up

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/docs#2309]
- Page link: https://amp.dev/support/
-  when going to the support page because the content is less it collapses it up and when we navigate menu they are under them

Please provide the steps to reproduce the issue:

1. visit the link https://amp.dev/support/
2. hover over other menu options

browser - chrome
os- windows 10

this can be easily fixed by sticking footer to bottom or increasing z-index

**Comment by sebil** [comment]
Thanks for reporting this, I'll take care of this
