### ISSUE TITLE
Document how to use overflow properly

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#232]
We previously said that overflow scroll/auto is disallowed, which isn't actually the case. However, there might be a need for a paragraph that explains how to use overflow effectively in AMP, as there are some issues (when running within an AMP Viewer).

/cc @cramforce

**Comment by pbakaus** [comment]
@cramforce any progress on how we're dealing with overflow on the Google side of things?

**Comment by cramforce** [comment]
@dvoytenko

**Comment by dvoytenko** [comment]
Not yet. A bit behind on this. @jridgewell has started on layers update just recently and we'll see how much we can actually get out of the automatic detection and if `overflow` control via CSS could ever work for us.

**Comment by bpaduch** [comment]
@pbakaus  - still an issue?

**Comment by pbakaus** [comment]
not sure, but I think so. @dvoytenko?

**Comment by bpaduch** [comment]
@dvoytenko - ping.

**Comment by dvoytenko** [comment]
@jridgewell are we ready to enable this?

**Comment by jridgewell** [comment]
It’s in experiment phase. I’ve been privately using it for a month, and haven’t noticed issues.

We can either push it to OptIn Canary phase, or just 1%?

**Comment by jridgewell** [comment]
It's not pushed yet, but will be soon. I don't think we need to do anything for this.
