### ISSUE TITLE
amp-analytics visibilitySpec bullets are malformed

### ISSUE THREAD

**Issue by zhangsu** [ampproject/docs#2324]
## Description of the issue found on ampproject.org

https://amp.dev/documentation/components/amp-analytics#visibility-spec

The different properties inside the `visibilitySpec` object should be in bullet.

On the other hand, the source correctly renders on GitHub:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#visibility-spec

**Comment by matthiasrohmer** [comment]
@dlemm, can you please have a look how the markdown needs to be formatted to correctly render as a list in Grow?

**Comment by dlemm** [comment]
Yes, I'll have a look.

**Comment by dlemm** [comment]
a blank line did it. I'll fix and push it
