### ISSUE TITLE
Tools page: allow deep linking to format

### ISSUE THREAD

**Issue by fstanis** [ampproject/docs#2341]
Would be good to add support for deep linking on https://amp.dev/documentation/tools e.g. have https://amp.dev/documentation/tools?format=stories select the "stories" filter for tools.

**Comment by matthiasrohmer** [comment]
(Note to myself: write actual issues for everything that I've planned in my head)

Thanks for flagging, Filip! I am actually already on this with #2325. The idea is the same as with #1694 and I'll implement them together.
