### ISSUE TITLE
about amp-form & amp-lightbox Usage

### ISSUE THREAD

**Issue by clodisewp** [ampproject/docs#2357]
In my project, I use lightbox as a popup window which contains a form with inputs and a submit button. When a user submit the information, I need to close the lightbox according to the information is correct or not, and I do not want ther user to submit the same information frequently in a second.
Could you please help out with an available way or a suitable solution.
Thank you!

**Comment by matthiasrohmer** [comment]
Hi @clodisewp! This repository is about maintaining the AMP Project documentation on amp.dev - sadly we can't provide direct support for using the framework itself here. Please consider asking your question either on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) (make sure to tag it with `amp-html`!) or in the #using-amp channel in [AMP's Slack](https://bit.ly/amp-slack-signup).
