### ISSUE TITLE
"Send email" link doesn't work

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#2368]
### Current Behavior
[Email landing page](https://amp.dev/about/email) second button "Send emails" doesn't link to anywhere. Just updates to the url to:
`https://amp.dev/about/email#stories`

### Expected behavior/code
I'm not sure where this is supposed to link to. Maybe [here](https://developers.google.com/gmail/ampemail/)?
### How do we reproduce the issue?

What browser are you using?
Chrome, current

What O/S are you using?
Mac

**Comment by matthiasrohmer** [comment]
@fstanis, you have an idea where that link should point to?

**Comment by fstanis** [comment]
I'm assuming to the "Start sending AMP Emails" section at the bottom of that page?

Ideally, we'll add other sending tools there over time, but right now it only contains Gmail.
