### ISSUE TITLE
`gulp bootstrap` creates/modifies git-tracked files

### ISSUE THREAD

**Issue by fstanis** [ampproject/docs#2369]
### Current Behavior
Running `gulp bootstrap` modifies the following git-tracked files:

-   `pages/content/amp-dev/community/governance.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md`
-   `pages/content/amp-dev/support/index.md`
-   `pages/shared/data/blog.yaml`

It also creates the following files:

-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-html.md`
-   `pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md`

### Expected behavior/code
Side-effect free in terms of `git status`.

It seems this section of the `.gitignore` file needs an update:

https://github.com/ampproject/docs/blob/d18e2f13c8d3d9b409cecd2a1f2c1f9d4fd77e9e/.gitignore#L17-L30

### How do we reproduce the issue?

Run `gulp bootstrap` and then `git status`.

**Comment by matthiasrohmer** [comment]
That's known actually - not to say intended. `gulp bootstrap` imports the most recent documents from ampproject/amphtml, while the versions in the repository could be stale - which isn't a problem as on every build they get imported freshly.

We aim to decouple both `gulp bootstrap` and the builds from the import with #2163. So long the changed/new files are save to be either thrown away or committed.
