### ISSUE TITLE
Email example is called "index"

### ISSUE THREAD

**Issue by fstanis** [ampproject/docs#2371]
### Current Behavior

[Article Bookmark Email](https://amp.dev/documentation/examples/interactivity-dynamic-content/article_bookmark_email/?format=email) has the title "index" since the file was moved in #2320.

### Expected behavior/code

The title (inferred from the filename, per #2059) should be "Article Bookmark Email".

**Comment by matthiasrohmer** [comment]
@fstanis, you've got an idea how to solve this? My first idea was to re-add a `<title>` element to the email sample, but we don't want to have them allowed anymore in the long run. So bad idea.

Second idea would be to add a edge case to the samples builder and use the parent directory's name as a title if the sample filename is index. @tharders, how does this sound?

**Comment by fstanis** [comment]
Could we perhaps read title from metadata? E.g. have the sample contain this at the top:

```html
<!---
preview: amp4email
title: 'Article Bookmark Email'
--->
```

**Comment by matthiasrohmer** [comment]
@sebastianbenz, what do you think? I have a slight memory we discussed allowing `title` in the frontmatter somewhen.

The parser's usual current fallback for examples without a `<title>` is to use the filename (`doc.title = exampleFile.title();`) which fails in this case.

**Comment by sebastianbenz** [comment]
The correct fix is to change `exampleFile.title()` to use the folder name if the file name is index.

**Comment by fstanis** [comment]
I guess another solution is to extend the parser logic to `if title == 'index' then use parent directory`.

That said, I fear this filename-is-title is getting increasingly clunky.

**Comment by sebastianbenz** [comment]
I still like it :-)

**Comment by matthiasrohmer** [comment]
Does anyone has strong feelings where to implement this? Rather in [amp-by-example/ExampleFile.js](https://github.com/ampproject/amp-by-example/blob/master/lib/ExampleFile.js) or in SamplesBuilder.js?

**Comment by sebastianbenz** [comment]
ExampleFile.js please
