### ISSUE TITLE
Japanese translation on "Add Translations" page

### ISSUE THREAD

**Issue by hogashi** [ampproject/docs#2378]
### Language

- Japanese

### File

- https://github.com/ampproject/docs/blob/4d2a30fe248835b0e8fe9de6b86fd19b313b9c0a/pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md

### Estimation of how much of the file I am translating

- Full File

### Estimation of how much time it will take

- 1 month

### Motivation

Translated "Add Translations" page should encourage translation. @CrystalOnScript

**Comment by hogashi** [comment]
I made a P-R: https://github.com/ampproject/docs/pull/2405

and I have some questions:

- Is `heath` typo of `health` ?  I couldn't understand what the word `heath` mean in this document.
  - >An area of open uncultivated land, typically on acid sandy soil, with characteristic vegetation of heather, gorse, and coarse grasses.
  - from: https://www.lexico.com/en/definition/heath
- Is the Slack team showed in "Currently, our process is:" aimed to localize even now?  The Google Form of that hyper link says "not really to talk about how to make AMP documents".
  - >"Some volunteer translators have created channels on Slack where a localized documentation tracker has been created. We encourage you to join and introduce yourself! Join the AMP Slack Channel here."
  - from: https://github.com/ampproject/docs/blob/4d2a30fe248835b0e8fe9de6b86fd19b313b9c0a/pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md#currently-our-process-is
  - >Enter your email address to get invited to the AMP developer Slack. We use this to talk about actually building AMP – not really to talk about how to make AMP documents. We might create a new Slack for that in the future, for now please ask on http://stackoverflow.com/questions/tagged/amp-html
  - from: https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877
- I couldn't align table of "amp.dev translation file suffixes" because Japanese uses multibyte characters.  Tell me if it matters.

Review my P-R and reply me if you have any problems. @CrystalOnScript @matthiasrohmer

**Comment by CrystalOnScript** [comment]
Hi @hogashi, thanks so much for opening a PR!

To answer your questions:
Q1: You are correct, `heath` was supposed to be `health`. I've sent up a correction. Thanks for catching and flagging that!

Q2: The slack channel does support translation channels for group chats. The description on the form is no longer an accurate description for the community. I've started a search for the form owner to see if we can update it!

Q3: Thanks for trying to get it aligned! I think it will be fine as is :)

**Comment by hogashi** [comment]
Thank you for answering the questions and merging the PR!  I hope this will help 
to increase translators and improve the documentantion. :+1:

**Comment by CrystalOnScript** [comment]
Me too! Thanks so much for your contribution!
