### ISSUE TITLE
AD

### ISSUE THREAD

**Issue by ahmedsmaq** [ampproject/docs#2379]
I am trying paste the google adsense code on Url

**Comment by matthiasrohmer** [comment]
Hi @ahmedsmaq! This repository is about maintaining the AMP Project documentation on amp.dev - sadly we can't provide direct support for using the framework itself here. Please consider asking your question either on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) (make sure to tag it with `amp-html`!) or in the #using-amp channel in [AMP's Slack](https://bit.ly/amp-slack-signup).
