### ISSUE TITLE
Add tracking pixel to "Get the courses" button

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#2386]
We'd like to know how many people are clicking on the "Get the courses" button at https://amp.dev/documentation/courses/teachers.

To do this, I'm planning to create a new event in GA. I'd then like to give that "Get the courses" button an ID and track it with a trigger as described [here](https://developers.google.com/analytics/devguides/collection/amp-analytics/).

I'm looking at the `analytics.j2` partial. I guess I'd need to add something to the podspec to let the config include triggers. At this point, I thought I should ask others for guidance!

/cc @matthiasrohmer @sebastianbenz @pbakaus @CrystalOnScript

**Comment by matthiasrohmer** [comment]
Once again @morsssss: sorry for not getting back sooner. 😞

You are totally free to add any trigger/event to the JSON configuration inside the `analytics.j2` partial. To make sure it only gets triggered on the courses pages, you could use the following condition for example:

```jinja2
{% if '/courses/' in doc.pod_path %}
  "defaultPageview": {
    "on": "visible",
    "request": "pageview",
  }
{% endif %}
```

No need to add something to the podspec - given I've got you right 😉 Let me know that helps already!

**Comment by morsssss** [comment]
That sounds great!

As long as you're not concerned that someday `analytics.j2` will become a morass of conditionals. I suppose that we can cross that bridge if we ever come to it 😃

**Comment by matthiasrohmer** [comment]
Hehe, see what I've did in `frontend/templates/views/partials/structured-data.j2` and fear no more. 😁 But yes in case it gets out of hand we need to think of a different solution.
