### ISSUE TITLE
Update https://www.ampproject.org/learn/who/ page

### ISSUE THREAD

**Issue by jasti** [ampproject/docs#240]
The who page is behind compared to how many platforms/ ad tech companies that have actual support in Github.

1. As you can see the number of ad networks in this [link](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/amp-ad.md#supported-ad-networks) are much more than what's listed under https://www.ampproject.org/learn/who/#ads

2. Update https://www.ampproject.org/learn/who/#analytics with https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#analytics-vendors
 
3. Update https://www.ampproject.org/learn/who/#video with https://github.com/ampproject/amphtml/tree/master/extensions#audiovideo

Major bonus points if we can automate this instead of manually updating it on a schedule.

**Comment by pbakaus** [comment]
I was able to create a script to automatically parse out the ad networks and analytics vendors, but the other sections still need to be manually updated for now (which I did).
