### ISSUE TITLE
Viewport documentation and requirements are out of date.

### ISSUE THREAD

**Issue by briansmith** [ampproject/docs#241]
See https://www.ampproject.org/docs/reference/spec, which says "`width=device-width,minimum-scale=1` is required to ensure GPU rasterization is enabled."

However, https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization says "Define a viewport. (Either as a `<meta>` tag, or in CSS as `@viewport`). Any viewport definition will work."

In particular, it isn't clear whether or not `minimum-scale=1` should be required going forward.

**Comment by bpaduch** [comment]
@dvoytenko  - Can you comment on this? What viewport is required?

**Comment by dvoytenko** [comment]
We can remove GPU rasterizaton reasoning. But I'd keep the rule itself given that we still support iOS.

**Comment by briansmith** [comment]
> But I'd keep the rule itself given that we still support iOS.

I see that the old reason for the rule (GPU rasterization) was removed, but the new reason (something about iOS that I'm not sure about) was not added. Could the new reasoning be added?

**Comment by bpaduch** [comment]
@dvoytenko - Can you explain why we are keeping the `minimum-scale=1` rule for iOS?

**Comment by dvoytenko** [comment]
For uniform support across iOS Safari and Chrome.

**Comment by briansmith** [comment]
> For uniform support across iOS Safari and Chrome.

I don't see how AMP breaks without `minimum-scale=1`. Isn't this choice an aesthetic decision that the website creator should be able to make themselves, like a normal web page? Or is there something that actually goes wrong in an AMP context if it is missing?

**Comment by dvoytenko** [comment]
GPU optimization, I believe, is still an issue in most of Chrome deployments and iOS Safari. If/when it's not, we'll need to update validator first before updating docs.

/cc @Gregable @cramforce

**Comment by cramforce** [comment]
We care a little bit about older Chromes. I don't feel strongly about it. Also to consider is impact on triggering fast-click in browsers.
