### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected end of JSON input at pixel.js:203

### ISSUE THREAD

**Issue by amp-blogs** [ampproject/docs#2435]
Bug Report
Unexpected end of JSON input at pixel.js:203

Current Behavior
Uncaught (in promise) SyntaxError: Unexpected end of JSON input at pixel.js:203

On my blog and on everyone blog hosted on blogspot
https://all-about-zodiac-signs.blogspot.com/

Expected behavior/code
    .then(res => res.json())    < HERE IS NO SEMICOLON AND THE ISSUE IN THE CONSOLE 
    .then(json => {
      const {pixels = []} = json;
      if (pixels.length > 0) {
        dropPixelGroups(pixels, {
          sid: eventData['sid'],
          ampDoc,
        });
      }
    });
};

Thanks

**Comment by matthiasrohmer** [comment]
This repository is about maintaining the AMP Project documentation on amp.dev - sadly we can't provide direct support for using the framework itself here. 

Please consider asking your question either on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) (make sure to tag it with `amp-html`!) or in the #using-amp channel in [AMP's Slack](https://bit.ly/amp-slack-signup).

**Comment by amp-blogs** [comment]
> This repository is about maintaining the AMP Project documentation on amp.dev - sadly we can't provide direct support for using the framework itself here.
> 
> Please consider asking your question either on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) (make sure to tag it with `amp-html`!) or in the #using-amp channel in [AMP's Slack](https://bit.ly/amp-slack-signup).

Thanks for your reply matthiasrohmer, but someone here has read the message and after months living with this problem, now it has been solved.

thanks anyway, next time I try to post it in the right section.
greetings from germany.
