### ISSUE TITLE
Support page

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#2443]
Hi,

Is this page a regression?
https://amp.dev/support/

Currently the support page references the README which references the support page.

I think this needs to be fixed quite urgently

**Comment by sebastianbenz** [comment]
The page is imported from ampproject/amphtml/support.md
<https://github.com/ampproject/amphtml/blob/master/SUPPORT.md> and the
content got changed as part of this PR:
https://github.com/ampproject/amphtml/commit/d24a5d48d9380c0f59f4fd6224b8395bdac32322#diff-b6de2700983073cf649bb620766ffce7
.

**Comment by matthiasrohmer** [comment]
Tracked by #2339.
