### ISSUE TITLE
Add Clang to the list of tools that support AMP⚡️Email

### ISSUE THREAD

**Issue by svmaris** [ampproject/docs#2444]
## Request to add third-party tool/service/platform/vendor

**1. What's the name?**
Clang (https://www.e-village.com/clang/)

**2. For which format?**
email

**3. What type is it?**
service provider

**4. What page should it appear on?**
https://amp.dev/documentation/tools

**5. If you choose 1 in Step 4:**
https://www.e-village.nl/images/footer/Clang-2015.png
Clang is a complete omnichannel marketing platform for email marketing and marketing automation.

**Comment by fstanis** [comment]
Hi @svmaris, could you provide a link to some page in the docs that makes it clear Clang supports AMP?

**Comment by svmaris** [comment]
Hi @fstanis, sure:

https://docs.myclang.com/en/getting-started-with-clang/e-mail-content/creating-amp-emails
