### ISSUE TITLE
amp-list example not displaying 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#2471]
### Current Behavior
Theres an empty space where there should be an example on the [amp-list reference documentation under usage](https://amp.dev/documentation/components/amp-list#usage). 

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-list#usage
- Screenshots: 
- [sample location in AMPHTML Repo](https://snag.gy/3rgk6K.jpg)
- [Lack of sample on amp.dev](https://snag.gy/AdvFH5.jpg)

**Comment by matthiasrohmer** [comment]
Duplicate of #2469.

**Comment by CrystalOnScript** [comment]
haha, back to back - thanks!

**Comment by matthiasrohmer** [comment]
You're welcome 😁
