### ISSUE TITLE
Clarification on <amp-video> tag

### ISSUE THREAD

**Issue by imoraes2006** [ampproject/docs#27]
I have implemented the <amp-video> tag and it works fine.  But I have some questions that I have not been able to find answers for and our Google advocate advised creating an issue .
1.  For a responsive page that has a video, the poster image does not adjust when the viewport size changes while other page components do.  That is, when a page is rendered in a larger viewport, a larger image should be able to be specified for the video.  
2.  Same comment for the controls. Also, can the controls be customized in any way? 
3.  After a video starts to play, if a user starts to scroll through the article and the video is not in the viewport, should the video pause?

Thanks
Ian

**Comment by cramforce** [comment]
1. You can create a child `div` with the `placeholder` attribute. We should document this much better.
2. Not right now.
3. I don't think it should. That is not what users typically expect.

@Meggin We should definitely fix the first point.

**Comment by imoraes2006** [comment]
Thanks for the clarification.

**Comment by bpaduch** [comment]
To clarify, if the amp-video component has `layout=responsive`, the poster does resize as in this example.  @cramforce - do we need further documentation on how to specify alternative poster images (e.g., srcset)?

**Comment by cramforce** [comment]
@bpaduch I don't think that is supported.

But over to @aghassemi for actually qualified comments :)

**Comment by bpaduch** [comment]
Hmm okay, as this was over a year ago, I'm wondering if this bug is relevant any more.

**Comment by aghassemi** [comment]
@bpaduch @cramforce `poster` can only have one source but a good alternative is to provide a custom `click-to-play` overlay instead of a `poster` (better UX than a `poster` too). The overlay can use `amp-img` and therefore can have `srcset` and other responsive features supported by `amp-img`. We have a sample for it on ABE: https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/

**Comment by bpaduch** [comment]
Okay, cool.  I've just added some text to the `poster` attribute section to "as an alternative, use click-to-play".  I think that'll help clear things up.
