### ISSUE TITLE
Validator 404s with SW

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#278]
URL is https://cdn.ampproject.org/v0/validator.js

Trigger on any AMP page with `#development=1`

**Comment by bpaduch** [comment]
@cramforce  - Is this docs related?  Any other details?

**Comment by cramforce** [comment]
Not at all. Software bug.

@jridgewell probably fixed this and it can be closed.

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/6788
