### ISSUE TITLE
New AMP Supported Platform

### ISSUE THREAD

**Issue by grudnitzki** [ampproject/docs#281]
Hi Paul,

I am proud to announce that our e-commerce platform now supports AMP natively.

Please check it out at https://www.fastcommerce.com.br/accelerated-mobile-pages-amp

All Fastcommerce virtual stores will be able to easily create an AMP-compatible design of the site, including its home, categories, product list, product details and news pages.

See an example at https://www.halitopuroprodutos.com.br/home.asp?useamp=1

We would like to be included in the Supported Platforms page of the official AMP site, in the CMS group.

Thank you!

Regards,

Guilherme Rudnitzki
Equipe Fastcommerce

**Comment by grudnitzki** [comment]
Hi, Paul!

Many stores here in Brazil are already using AMP, using our e-commerce platform.
Please check our AMP hotsite at https://www.fastcommerce.com.br/accelerated-mobile-pages-amp

Unhappily we don't have an English site. Is this a requirement to be included in the Supported Platforms page of the official AMP site?

Cheers!
Guilherme

**Comment by grudnitzki** [comment]
Hi Paul,

Is there something else I can do to Fastcommerce be included in the Supported Platforms page of the official AMP site?

BTW, I will attend the AMP Conf in NY, mainly to see the news first hand.

See you!

Guilherme

**Comment by ithinkihaveacat** [comment]
@grudnitzki I think this will work just fine, but out of interest, why are you linking to `cdn.ampproject.org` from your canonical?

<img width="1101" alt="screen shot 2017-02-21 at 5 27 43 pm" src="https://cloud.githubusercontent.com/assets/51244/23176517/2f6005a2-f85b-11e6-93d5-cd3d6c63f3b9.png">

(That is, <https://www.halitopuroprodutos.com.br/home.asp?useamp=1> links to <https://cdn.ampproject.org/c/s/www.halitopuroprodutos.com.br/listaprodutos.asp?idloja=8079&idproduto=5560704&q=kit-para-a-limpeza-da-lingua-verifresh-&useamp=1>.)

**Comment by pbakaus** [comment]
Sorry it took so long. Added via 8484277, will be deployed this week.

**Comment by grudnitzki** [comment]
No problem, Paul.

I am honored and pleased to have Fastcommerce listed in the supported
platforms page of the AMP project site!

https://www.ampproject.org/support/faqs/supported-platforms

Thank you!


2017-04-24 15:26 GMT-03:00 Paul Bakaus <notifications@github.com>:
>
> Sorry it took so long. Added via 8484277, will be deployed this week.
