### ISSUE TITLE
Better document how layouts work including 'heights'

### ISSUE THREAD

**Issue by Meggin** [ampproject/docs#29]
The current doc, https://www.ampproject.org/docs/guides/responsive/control_layout.html, does a decent early job explaining layouts in AMP.

But it definitely needs to be updated to cover 'heights' (wherever sizes documented).

It also could do more to talk about common layout patterns for amp tags (like how container isn't supported in most, and some have nodisplay only, and how default behaviors work, etc.).

**Comment by Meggin** [comment]
FYI, this one will get done post-launch.

**Comment by cramforce** [comment]
Friendly ping on this one.

I think this page kind of misses the point: https://www.ampproject.org/docs/guides/responsive_amp.html and this one is way too complicated https://www.ampproject.org/docs/guides/responsive/control_layout.html Nobody should need to understand anything about how AMP manages layouts to work with AMP.

We need to say somewhere: If you want to make your AMP elements responsive, put `layout="responsive" on them. That should be front and center. (And all our examples should use this by default. Non-responsive layout should be the exception) We hide it behind other more obscure stuff right now and make it look really complicated.`

**Comment by Meggin** [comment]
Got it. I'll target this one today/tomorrow.

**Comment by Meggin** [comment]
I also think we could add more around validation errors that relate to
layout stuff, so that when developers get those errors, they understand
clearly what's causing it. At least where the docs describe these errors,
we should point to the docs, and the docs should mention the errors too.
More round-about connecting the dots.

**Comment by Meggin** [comment]
Wrote a better set of responsive docs. They aren't perfect, but they are better. So closing.
