### ISSUE TITLE
 Prioritize visible content

### ISSUE THREAD

**Issue by fassetar** [ampproject/docs#292]
I was able to meet this condition with Google Page Speed using
```
<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
 <style amp-custom=''>.something{margin:0}</style>
```

however with the [latest boilerplate](https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md) I can't meet this condition. Is there something I'm missing?

**Comment by bpaduch** [comment]
@Gregable - Can you advise on this?

**Comment by Gregable** [comment]
@cramforce who knows a bit more about how AMP interacts with Page Speed recommendations.

**Comment by cramforce** [comment]
@fassetar Nothing you can do really. We are in ongoing discussions with the PageSpeed team to make their heuristic not have these false positives.

**Comment by jaspersorrio** [comment]
Hi @cramforce, we recently did a test on [pagespeed insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fexpressmaid.com.sg%2F&tab=mobile) but we still got the Prioritize visible content rule listed as a possible optimization. As a result, some of our clients whom we are developing Amp Websites for are questioning our ability to make websites fast. 

Was wondering how are the discussions with the PageSpeed team? Thank you for facilitating the discussions!

Can check out this website at [https://expressmaid.com.sg](https://expressmaid.com.sg).

**Comment by cramforce** [comment]
I think they are kind of working on it, but I wouldn't expect immediate changes.
