### ISSUE TITLE
Add Tools Dropdown

### ISSUE THREAD

**Issue by jridgewell** [ampproject/docs#295]
We got a [request](https://github.com/ampproject/amphtml/issues/7105) to add a Tools dropdown to collect links like the validator extension and https://validator.ampproject.org/.

> Is it possible to create and add a section called "tools" in the top navigation and then link it to a webpage with all your tools.

> (Because it's a nightmare trying to find this link [below] and other tools)

**Comment by bpaduch** [comment]
@ayumihamsaki - As there's only one tool I can think of that's specific to AMP, that is, the [AMP Validator](https://validator.ampproject.org/), I can't justify a dropdown for this one item.  Are there other tools to consider?

**Comment by bpaduch** [comment]
Will close this issue.  If there's further info or a need to reopen this, please do.
