### ISSUE TITLE
Give straightforward explanation how to make a responsive image

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#3]
It is in here, but really dug under lots of detail that is almost never necessary.
https://www.ampproject.org/docs/guides/responsive_amp.html

**Comment by Meggin** [comment]
I'm going to punt this till after launch. It's important, but there's so many higher importants above this one.

**Comment by Meggin** [comment]
Wrote a better set of responsive docs, not perfect, but better. Closing this.
