### ISSUE TITLE
Invalid IDs generated for some headings

### ISSUE THREAD

**Issue by yunelee** [ampproject/docs#310]
It looks like the auto-generated IDs for headings ignore non-Roman characters, which means that if the only English word is "AMP", the ID for the heading will be "AMP" -- this throws an error during validation.

See https://www.ampproject.org/ko/docs/guides/validate#development=1 and the first `<h2>` for an example.

**Comment by bpaduch** [comment]
This appears to be an issue with Grow on how it generates heading IDs. I've reported it as an issue -https://github.com/grow/grow/issues/360.

**Comment by bpaduch** [comment]
Fixed in Grow 0.1.0.

Reviewed https://www.ampproject.org/ko/docs/guides/debug/validate#development=1 and validation passes.
