### ISSUE TITLE
Analytics guide does not have navigation buttons

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#315]
On https://www.ampproject.org/docs/guides/analytics_amp, there's no way to access the next sections of content. Other guides feature a button that lets readers continue on to the next step.

**Comment by bpaduch** [comment]
As this is a guide and not a tutorial, I wouldn't expect navigation buttons.  The sub-content for Analytics can be seen/accessed via the lefthand navigation, similar to other guides (e.g., [Styling & Layout](https://www.ampproject.org/docs/guides/responsive_amp)). I *could* add a single nav button to "Learn more with AMP Basics", which takes them to the next subtopic - basics.  Thoughts?

**Comment by pbakaus** [comment]
Agree with Barb. The way to fix this is to threat it properly as an
overview page, and naturally lead into the sub sections, like I've done in
https://www.ampproject.org/docs/guides/responsive_amp (with the "read more"
callouts).
