### ISSUE TITLE
Add wordpress.com help page 

### ISSUE THREAD

**Issue by sachiyos** [ampproject/docs#330]
Currently the WordPress help page under ampproject.org/who points to .org Help page (https://wordpress.org/plugins/amp/). Can we add .com help page also (https://en.support.wordpress.com/google-amp-accelerated-mobile-pages/)?

**Comment by bpaduch** [comment]
The way the page is set up, we can only specify one link.  Both links you point out have interesting and useful content.  @pbakaus, you know more about WordPress, which link would be best?

**Comment by pbakaus** [comment]
Mhh hard to say. One is helpful for WordPress.com, one for WordPress the CMS. Wonder if we should split them in the listing?

**Comment by sachiyos** [comment]
Ideally both will be available on the site. We have many questions from WP users and I want to make sure that all the WP users can find the right content.
