### ISSUE TITLE
Add lang attributes to <html>

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#331]
This is probably a transient error, but right now searching for `amp-bind` is returning <https://www.ampproject.org/es/docs/reference/components/amp-bind> (the Spanish language version) as the first search result. (I do not speak Spanish, nor am I in a Spanish speaking country.)

Adding `lang=XX` attributes as appropriate to the HTML will probably help.

<img width="677" alt="screen shot 2017-02-21 at 5 05 31 pm" src="https://cloud.githubusercontent.com/assets/51244/23175759/35e02388-f858-11e6-8c35-fd0dc21643fb.png">

(Note the `/es/` in the URL.)

**Comment by bpaduch** [comment]
This appears to be fixed.  If not, please reopen.
