### ISSUE TITLE
"Allow only asynchronous scripts" is confusing on How AMP Works page

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#335]
As per @chenshay, this title is misleading, as one could think they could add JS to the page that isn't AMP's:

![image](https://cloud.githubusercontent.com/assets/43004/23315741/5bfb35b4-fa7c-11e6-99fb-44654d154b3d.png)

@cramforce's proposed title, which I like: All AMP JavaScript is fetched with the async attribute.

**Comment by chenshay** [comment]
my suggestion:

Javascript is only allowed to come from from AMPHTML.....and it is loaded asynchronously

**Comment by cramforce** [comment]
I don't think this is the right place to focus on what is allowed and is
not allowed, as this is really meant to talk about why a particular loading
technique is used. The whole point is that is could also work for non-AMP
JS.
