### ISSUE TITLE
Language picker cuts off on smaller screen

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#342]
<img width="216" alt="screen shot 2017-03-06 at 10 03 48 am" src="https://cloud.githubusercontent.com/assets/89679/23615395/435f02b2-0254-11e7-8f9b-17b5ee48ba6c.png">

**Comment by bpaduch** [comment]
to: @leeee

**Comment by bpaduch** [comment]
@cramforce - Is this still an issue?  I cannot replicate, I get this:

![screenshot](https://cloud.githubusercontent.com/assets/1012254/23767133/70aabc92-04d5-11e7-938f-ac8717abfa9d.png)

**Comment by cramforce** [comment]
Definitely still the case. The lang picker on https://www.ampproject.org/ looks different from the screen above.

**Comment by leeee** [comment]
There's a shorter version of the lang picker for short screens now.
![image](https://cloud.githubusercontent.com/assets/1018021/23870660/62ccf4d4-07e4-11e7-8207-0799d86c27b4.png)

**Comment by cramforce** [comment]
I'm getting what @leeee is getting but it doesn't fit on my screen.

**Comment by bpaduch** [comment]
@cramforce - Can you please provide spec details (OS, Browser, Screen Size, Browser Build. etc)? Thanks.

**Comment by cramforce** [comment]
I think this has gotten better for me. It still repros, by simply making
the window less tall, but it now probably handles realistic sizes well
enough.
