### ISSUE TITLE
Logs & Paywalls guide - 404

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#343]
The guide for "Logins & Paywalls" is missing.  When I search for it on ampproject.org, I get this link https://www.ampproject.org/docs/guides/login-paywalls, which ends up as 404.

**Comment by bpaduch** [comment]
to: @leeee

**Comment by leeee** [comment]
I believe we decided to axe this page in one of our IA meetings, since it didn't really have much content. I can set up a redirect for that url, maybe to here makes sense? https://www.ampproject.org/docs/get_started/login_requiring

**Comment by pbakaus** [comment]
Agree, there was very little on the page. I think the redirect works. Barb,
if you think we should restore it instead, I'm OK with it. Thoughts?

**Comment by bpaduch** [comment]
Redirect works!
