### ISSUE TITLE
amp-sticky-ad: Required Scripts?

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#347]
Hello, here: https://www.ampproject.org/docs/reference/components/ads/amp-sticky-ad it said that just `<script async custom-element="amp-sticky-ad" src="https://cdn.ampproject.org/v0/amp-sticky-ad-1.0.js"></script>` is required for "sticky-ads". 

I put that required script into a new AMP page, and validate with `#developer=1`, and everything it's OK. But... google webmaster tools detects AMP error, and said that it's required `<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>` too. 

So, the documentation for **amp-sticky-ad** must be edit or not about required scripts?

**Comment by bpaduch** [comment]
@zhouyx - Can you confirm the required scripts?

**Comment by zhouyx** [comment]
Well I think it makes sense in both ways. One can argue `sticky-ad` should require both `amp-sticky-ad` and `amp-ad` scripts. However from another aspect, `amp-sticky-ad` itself is only a format, it is the `amp-ad` child inside that requires `amp-ad` script. 
I would prefer the current documentation, as the extension only requires its own script.
@bpaduch what do you think.

**Comment by bpaduch** [comment]
@zhouyx - Thanks for the clarification, and yes, I agree.  `amp-stick-ad` on its own requires it's "amp-stick-ad" JS.  When they add `amp-ad` as child, they need to bring along the "amp-ad" required script.

**Comment by SidVal** [comment]
I disagree.
Perhaps it is "obvious" to you, but you are giving incorrect information to those who come to read the documentation without knowing if the "amp-sticky-ad" requires or not the other "parent script".

But look at the illogical of all this:
If you do the `#developer=1` test, it comes out OK (with no errors).
And then Google Webmasters detects errors.

At least in the "behavior" section, when it said:

> The `<amp-sticky-ad>` should only have one direct child of `<amp-ad>`.

Please clarify that requires the `<amp-ad>`

**Comment by bpaduch** [comment]
Hmmm, interesting.  When I create a page with an `amp-sticky-ad`, the AMP Validator *warns* me about `amp-ad` script with the following message: `The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-ad'. This will soon be an error.` 

Did you get that warning?  I think the Google webmaster tools found that warning and that's the reason for the error.

I'll clarify that the direct child of `amp-ad` requires its script.



When I validate via `#devel

**Comment by SidVal** [comment]
Agree with your PR modification @bpaduch ! :+1: 
Nice recommendation. If that PR merges, I think this issue may be closed :smiley:  

Thank you again.
Regards

**Comment by bpaduch** [comment]
Thank you @SidVal for your feedback and help!

**Comment by SidVal** [comment]
No way @bpaduch, you ROCK! :1st_place_medal:  :100:  
Thank you very much!
