### ISSUE TITLE
Formatting issues for Case Studies

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#349]
1) On desktop sites (width > 956 px), the "Results" blue box extends on the sides and looks odd.
![case-studies-blue-box](https://cloud.githubusercontent.com/assets/1012254/23706489/5f72c9d2-03dc-11e7-9805-f9fcae3261aa.png)

2) When trying to create a case study that included bulleted text ( see [Milestone](https://www.ampproject.org/case-studies/milestone/), I wanted the image of the phone to be displayed on left via <div class="img-left"> but that class displaces the bullets (see example attached), so I had to use "img-right".  

![div-left-case-studies](https://cloud.githubusercontent.com/assets/1012254/23706644/07cf8ad4-03dd-11e7-81b5-a9a39df5554d.png)

to: @leeee

**Comment by leeee** [comment]
#1 is working as intended as far as I can tell. The blue box is supposed to be wider than the content on desktop.

Just pushed a fix for #2 so you can try using img-left there again.

**Comment by bpaduch** [comment]
Re: 1: It just seems weird to have the post-sheet box block out the blue for the middle section and having those blue bits on the sides of the article.

![weird-box](https://cloud.githubusercontent.com/assets/1012254/23755225/a752005c-04ad-11e7-9f6a-bd539dc6e394.png)

**Comment by pbakaus** [comment]
Might be OK if you give the white container a slight shadow to separate it
from the background, so it actually is clear that it is floating on top of
the header.

**Comment by bpaduch** [comment]
That might work, the only thing is the smartphone pics would be outside the box, like so:

![shadowbox](https://cloud.githubusercontent.com/assets/1012254/23762055/e35d1bb2-04c2-11e7-8f20-b865528f686f.png)

**Comment by pbakaus** [comment]
Should work if we manually remove the shadow from the mobile phone pics..

**Comment by leeee** [comment]
Talked to our designer and she thinks we should just bump the content down to it doesn't overlap the blue box. Does that sound ok?

**Comment by pbakaus** [comment]
WFM.

**Comment by bpaduch** [comment]
+1.

**Comment by leeee** [comment]
This change is live on staging: https://ampproject-staging.firebaseapp.com/case-studies/gizmodo/

**Comment by bpaduch** [comment]
LGTM

**Comment by bpaduch** [comment]
Another issue found with formatting, this time with bullets where text is longer than one line:

![selection_002](https://cloud.githubusercontent.com/assets/1012254/23914898/bc2eb358-08bd-11e7-9016-b11919324c9a.png)

The text should be indented and line up after the bullet.

**Comment by pbakaus** [comment]
Fix: add "display: flex" to the CSS of the `<li>` elements. You're welcome :)
