### ISSUE TITLE
Sub-nav links for Guides don't go to localized version

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#353]
Issue: On a localized page, the navigation links to Guides > **Author /Dev**, Guides > **Debug**, and Guides > **Deploy**  go to the English page and  not the localized page.

The links should direct to the specified language's page for "Author/Dev", "Debug", and "Deploy".

![subnav-links-wronglang](https://cloud.githubusercontent.com/assets/1012254/23768339/a1f5c98c-04d9-11e7-95ea-c56ad4557caf.png)

**Comment by leeee** [comment]
This is fixed on staging

**Comment by bpaduch** [comment]
LGTM
