### ISSUE TITLE
Better share image needed for social sharing

### ISSUE THREAD

**Issue by jeremydw** [ampproject/docs#354]
The image that appears when the website is shared on Facebook isn't very good. Screenshot below. I think it'd be nice to replace it with the AMP logo or some of the new imagery from the new visual refresh.

![image](https://cloud.githubusercontent.com/assets/646525/23778707/c6067530-04f0-11e7-81f4-022ee6c75767.png)

Once this is fixed, the Facebook cache can be refreshed here: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.ampproject.org%2F

**Comment by bpaduch** [comment]
@pbakaus - I don't have any idea on how to change this. :)

**Comment by sebastianbenz** [comment]
You can take a look here for an example:
https://github.com/ampproject/amp-by-example/blob/master/templates/metadata.html
This
improves sharing across twitter and facebook.

**Comment by jeremydw** [comment]
Basically, what we do on our sites is add a `1200x630` sized image using the `og:image` tag. The value of the `content` property should be a URL pointing to a `1200x630` sized image.

```
<meta property="og:image" content="{{url}}">
```
