### ISSUE TITLE
Build breaks for KO text in who-uses-amp file

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#362]
[Build](https://travis-ci.org/ampproject/docs/builds/210608906) breaks with the following error: `grow.pods.errors.BuildError: Error building <Rendered(view='/views/about-who.html', doc='/content/learn/who-uses-amp@ko.yaml', locale='ko')>: 'ascii' codec can't encode characters in position 19-21: ordinal not in range(128)`

Investigated and it's related to the KO text in the card's `name` attributes (see [content/learn/who-uses-amp@ko.yaml](https://github.com/techhtml/docs/blob/802d640f3563ab8a31d397dc628892257cd15648/content/learn/who-uses-amp%40ko.yaml) file).

**Comment by techhtml** [comment]
I fix it.
