### ISSUE TITLE
Update case study PDFs with new design

### ISSUE THREAD

**Issue by elegeros** [ampproject/docs#366]
Older case studies are now mocked up with the new design and should be swapped out to match rest of site. Barb/Elena should have access to the doc to download the PDFs.

**Comment by bpaduch** [comment]
@mattludwig - Do you want to handle this one?

**Comment by mattludwig** [comment]
Yes, I can handle. Though given my priorities, I'll aim to have this done in the next 2 weeks.

**Comment by mattludwig** [comment]
I took a look at this and all case studies appear to have been updated. Let me know if I'm missing something but I believe this can be resolved.
