### ISSUE TITLE
If the <meta http-equiv> attribute is banned, why do you use it on your website?

### ISSUE THREAD

**Issue by collinanderson** [ampproject/docs#369]
In the spec, it says "The http-equiv attribute is banned." However, the source of the pages _uses_ http-equiv and the page still validates. I assume there's a `X-UA-Compatible` exception to the rule that needs to get documented?

`<meta content="IE=Edge" http-equiv="X-UA-Compatible">`

https://www.ampproject.org/docs/reference/spec

**Comment by bpaduch** [comment]
@pbakaus or @Gregable - can you comment?  Should the [spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md) be updated to account for `X-UA-Compatible`?  Can you provide details?

**Comment by Gregable** [comment]
The documents should be updated, however only very specific values are
allowed.

-Greg

**Comment by bpaduch** [comment]
How about this:

The `http-equiv` attribute may be used if the value is `"X-UA-Compatible"` and `content="IE=Edge"` or `content="Chrome=1"` . Otherwise allowed.

**Comment by Gregable** [comment]
Here are the actual rules:

# This tag is a hack to tell IE 10 to use its modern rendering engine as
opposed
# to the IE8 engine. So it's explicitly allowed.
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=X-UA-Compatible"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "x-ua-compatible"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
    value_properties: {
      properties: { name: "ie" value: "edge" }
      properties: { name: "chrome" value: "1" }
    }
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv content-language tag
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=content-language"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "content-language"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv pics-label tag
# https://www.w3.org/PICS/
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=pics-label"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "pics-label"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv imagetoolbar tag
# https://msdn.microsoft.com/en-us/library/ms532986(v=vs.85).aspx
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=imagetoolbar"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "imagetoolbar"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv content-style-type
# https://www.w3.org/TR/REC-html40/present/styles#h-14.2.1
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=Content-Style-Type"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "content-style-type"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
    value_casei: "text/css"
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv content-script-type
# https://www.w3.org/TR/html4/interact/scripts#h-18.2.2.1
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=Content-Script-Type"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "content-script-type"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
    value_casei: "text/javascript"
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv origin-trial tag
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=origin-trial"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "origin-trial"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
  spec_url: "https://www.ampproject.org/docs/reference/spec#html-tags"
}
# http-equiv resource-type
tags: {
  tag_name: "META"
  spec_name: "meta http-equiv=resource-type"
  mandatory_ancestor: "HEAD"
  attrs: {
    name: "http-equiv"
    mandatory: true
    value_casei: "resource-type"
    dispatch_key: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
}


In other words, these are all technically allowed:

   - http-equiv=x-ua-compatible content="ie=edge"
   - http-equiv=x-ua-compatible content="chrome=1"
   - http-equiv=x-ua-compatible content="ie=edge,chrome=1"
   - http-equiv=x-ua-compatible content="chrome=1,ie=edge;"
   - http-equiv=content-language content=*
   - http-equiv=pics-label content=*
   - http-equiv=imagetoolbar content=*
   - http-equiv=content-style-type content="text/css"
   - http-equiv=content-script-type content="text/javascript"
   - http-equiv=origin-trial content=*
   - http-equiv=resource-type content=*

However, none of these are really recommended. I think that they are all
no-ops on an amp page.

   - Microsoft will enable edge mode if it sees <!doctype html>.
   - Chrome frame no longer exists
   - content-language has some value for crawlers, but can and should be
   set in a server header.
   - pics-label, imagetoolbar are both relics of ancient browsers that
   aren't in mobile devices
   - content-style/script-type are only allowed to be defaults.
   - I'm unsure about origin-trial and resource-type off the top of my head.


I don't know how much detail the docs should cover here. We don't intend to
recommend any of these, just make it easier for folks to validate by
relaxing some requirements that aren't needed. Most of these tags get
stripped by the amp cache anyway.

-Greg

**Comment by bpaduch** [comment]
@Gregable - Can you review the doc fix in https://github.com/ampproject/amphtml/pull/8993.  Thanks.

**Comment by Gregable** [comment]
Done. You may also want to remove the `<meta content="IE=Edge" http-equiv="X-UA-Compatible">` tag from ampproject.org's template.

This tag was designed to prevent newer versions of IE from falling back into a document parsing mode from an older version of IE. However, IE is now doing this for any document that starts with `<!doctype html>` which all amp documents do, so the meta tag is a no-op.
