### ISSUE TITLE
Refine list of disallowed and restricted CSS

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/docs#373]
*-selector and :not(), for instance are not currently validated ([spec](https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages))

Options: 
Actually enforce these in the validator (not recommended — some of these are good to have)
Update documentation to distinguish "not recommended" CSS from "restricted" and "disallowed" CSS

**Comment by pbakaus** [comment]
I would lump overflow into this list as well, which is a big pain point for
me, as overflow works outside the viewer but not in the viewer :(

**Comment by camelburrito** [comment]
http://www.telerik.com/blogs/css-tip-star-selector-not-that-bad 

I dont see a huge upside for banning star and not selectors. The performance impact is almost negligible.

**Comment by timBrockman** [comment]
#367 is covering similar `*` ground.

**Comment by dvoytenko** [comment]
Correct, https://github.com/ampproject/docs/issues/367 is meant to address it:

- Universal selectors are no longer disallowed
- Neither are `not()` selectors
- We are tracking `overflow` changes/fixes in a separate bug. So let's just focus on selectors here.

**Comment by bpaduch** [comment]
It looks like the doc was updated on March 17 in https://github.com/ampproject/docs/commit/d137fda90bb6bf854aa980c80b6e089496ae02a3 and  removed the items that are no longer disallowed.

@ericlindley-g  - Can we close this issue?

**Comment by ericlindley-g** [comment]
I think so — /cc @dvoytenko to confirm that the right rules are removed and re-open if anything needs to be changed (since I can't seem to find the review for these changes)
