### ISSUE TITLE
No mention of AMP Start

### ISSUE THREAD

**Issue by dereklewis** [ampproject/docs#374]
Some sort of endorsement for AMP Start seems like it would be appropriate at this time since the launch was announced at AMP Conf. A blog post would be great.

**Comment by ericlindley-g** [comment]
Blog post in the works :) (time before the conf was spent getting it ready for launch)

ampproject.org plans include putting a link in the footer of the site to AMP Start and AMP by Example, but might be nice to feature it elsewhere to give a better idea of what it is before going there.

**Comment by bpaduch** [comment]
@ericlindley-g  -  any word on the blog post?

**Comment by ericlindley-g** [comment]
Some new features are landing soon, so we're holding off on a blog post until those launch, but are also thinking through some ways to point to AMP Start from other places on the site

**Comment by bpaduch** [comment]
Blog post created - https://www.ampproject.org/latest/blog/start-fast-with-new-amp-start-templates/
