### ISSUE TITLE
Grammar detail for layout guide.

### ISSUE THREAD

**Issue by loh** [ampproject/docs#38]
The title "How AMP **layouts** its pages" should be written "How AMP **lays out** its pages" at the top of this section:

https://www.ampproject.org/docs/guides/responsive/control_layout.html#how-amp-layouts-its-pages

**Comment by Meggin** [comment]
Fixed in this commit (will be live in site in next push): https://github.com/ampproject/docs/commit/2523c110131f000d3907b139bf5570b212431934
