### ISSUE TITLE
Linking to vendors.js in docs

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#391]
> You can also look at the vendors.js file for further information on each vendor's configuration.

Found here https://www.ampproject.org/docs/guides/analytics/analytics-vendors

@rudygalfi Should we just delete that sentence?

**Comment by rudygalfi** [comment]
The sentence was added to provide greater transparency into how each vendor's configuration works (in case people want to tweak on top of it or debug it). 

What's the motivation for removing it? To not link to code from documentation?

**Comment by bpaduch** [comment]
@cramforce - friendly ping

**Comment by cramforce** [comment]
I felt it would confuse users, because that file isn't really supposed to be consumed by humans.

**Comment by pbakaus** [comment]
I propose we rephrase it as a callout (tip), saying something like "Tip: If you're comfortable digging through code, you can explore the raw configurations in the [vendor.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js) file."

I think it's nice to keep it, but I agree that the current wording makes it sound like it's a human readable doc.

**Comment by pbakaus** [comment]
@cramforce ping – do you agree with the compromise?

**Comment by bpaduch** [comment]
@cramforce - friendly ping

**Comment by cramforce** [comment]
Sorry, yes, SGTM
