### ISSUE TITLE
what this  <meta name="amp-experiments-opt-in" content="visibility-v2,visibility-v3">

### ISSUE THREAD

**Issue by hosamalzagh** [ampproject/docs#400]
what mean 
  meta name="amp-experiments-opt-in" content="visibility-v2,visibility-v3"

in head tags

**Comment by dvoytenko** [comment]
These are page-level experiments. See https://github.com/ampproject/amphtml/blob/master/src/experiments.js and https://github.com/ampproject/amphtml/blob/master/tools/experiments/experiments.js#L52
