### ISSUE TITLE
<amp-social-share type="system"> : data-mode or data-param-data-mode?

### ISSUE THREAD

**Issue by alfredmyers** [ampproject/docs#406]
Regarding the Web Share API provider for `<amp-social-share>`:

[Docs](https://www.ampproject.org/docs/reference/components/social/amp-social-share) says the attribute for defining the `mode` is `data-params-data-mode`

While [AMP by Example](https://ampbyexample.com/components/amp-social-share/) says the attribute is `data-mode`

My tests show that `data-mode` works as described while `data-params-data-mode` doesn't.

PS.: I tried to find the corresponding source file here in the docs repo to contribute a fix, but I wasn't able to find it.

**Comment by bpaduch** [comment]
Thanks for the info.  I've fixed the file, which is actually in the amphtml repo (and pulled in nightly for the docs build). See https://github.com/ampproject/amphtml/pull/8445.
