### ISSUE TITLE
Content area is movable with touch on tablets

### ISSUE THREAD

**Issue by aghassemi** [ampproject/docs#408]
![a](https://cloud.githubusercontent.com/assets/2099009/24419935/da069bfa-13a5-11e7-9647-248be92bf5e7.gif)

I think `.wrap` just needs a `overflow:hidden`, not sure if that might break something else though (hence creating an issue instead of a PR)

**Comment by pbakaus** [comment]
good catch, seems to work without issues. Thanks!
