### ISSUE TITLE
Some of the untranslated pages and sections are broken for RTL languages.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/docs#410]
Example:
https://www.ampproject.org/ar/docs/reference/spec

This part of the site isn't translated, so it should probably just be LTR? I'm not an Arabic speaker, so you may want to consult with language QA. However, for the examples within the page, I think they look wrong syntactically because the quotes are not in the right place. Almost certainly, these examples of AMPHTML source code should be blocks of LTR text even if the rest is formatted differently. This is also true on this page, which is translated - but the embedded Javascript snippet looks broken:

https://www.ampproject.org/ar/docs/reference/experimental
 
Thanks much for looking into it.

**Comment by pbakaus** [comment]
The untranslated LTR issue I'm torn about, since I think switching things around after every click is much more annoying than what we currently have. Would love actual users to chime in though.

The JS snippet looks indeed broken, that looks like a bug. Will investigate.
