### ISSUE TITLE
Missing documentation for amp-facebook-comments

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#425]
I noticed this when looking through the new URL pattern (new directory under components/). I assume this will end up at https://www.ampproject.org/docs/reference/components/social/amp-facebook-comments and updating the validator to point to that.

Merged PR: https://github.com/ampproject/amphtml/pull/7629.
MD: https://github.com/ampproject/amphtml/blob/master/extensions/amp-facebook-comments/amp-facebook-comments.md

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/docs/pull/438
