### ISSUE TITLE
Missing documentation for amp-gist

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#426]
This is a very new extension, so not surprised that it's missing. 
Merged PR: https://github.com/ampproject/amphtml/pull/8263
MD: https://github.com/ampproject/amphtml/blob/master/extensions/amp-gist/amp-gist.md

Also please ping me which directory under components/ this will go in so I can update the validator.protoascii. Thanks!

**Comment by aghassemi** [comment]
hmm not sure which category makes most sense for this. Either Dynamic Content or Presentation I guess.

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/docs/pull/438
