### ISSUE TITLE
Please support desktop/laptop usage

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#428]
I'm trying to use this site on my laptop but I'm stuck with three major columns where two of them has very little to do with what I'm trying to read and understand.

356 pixels are given to a very high-level Table of Contents type first column and another 200 pixels are for another Table of Contents in the third column. Why are there two Table of Contents for a single page and taking up 556 pixel and giving the content only 666 pixels? Lets fix this to only giving the Table of Contents a single 200 pixels (or slightly more) and giving the primary content the spotlight it deserves.

The real gain might be to reign in the first column since it has a large font size with very little to offer. If this can be merged with the third column then that's already a huge savings, but it still does not need to have that large font size that exists in the first column.

Again, the content that matters is in the second column and on laptops and desktops (except for desktops with very large resolutions) the user experience suffers.

**Comment by honeybadgerdontcare** [comment]
Apparently the three column approach only shows up on this page: https://www.ampproject.org/docs/reference/validation_errors

Perhaps it's time to remove that third column from that page.

And I still believe there's too many pixels for that first column for desktop/laptop usage. Please reconsider the font sizes.

**Comment by pbakaus** [comment]
I just did some optimizations. The left menu is flattened and quite a bit narrower on smaller resolutions. Try it out and let me know what you think.

**Comment by honeybadgerdontcare** [comment]
Your work added 56 more pixels to the content of the page, thank you!

I do find the third 200px column not that useful when reading...maybe provide a hide mechanism for it? :/

**Comment by pbakaus** [comment]
OK compromise – I didn't make it collapsible, but I made it elastic as well, as well as fixing the styles so it's both more accessible and lighter on the eye, and matches the rest of the site. This should again restore some space for you and help restore focus on the content:

https://www.ampproject.org/docs/reference/validation_errors

I'll close this bug for now – if you feel very strongly we need more optimizations, please open another specific one :) Thanks!
