### ISSUE TITLE
Each extension should include the script tag that needs to be copy pasted into the page

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#43]
We can probably auto generate that in jekyll.

I've heard this feedback a lot and it would greatly increase our copy-pasteability.

CC @Meggin @rudygalfi

**Comment by Meggin** [comment]
I've included the script tag in the intro tables, as a starting point.

**Comment by Meggin** [comment]
I'm going to close this, as the script tag for every extension is in it's spec.
