### ISSUE TITLE
Update masthead photo on Latest page

### ISSUE THREAD

**Issue by mattludwig** [ampproject/docs#430]
[Low prio request]

Page link: https://www.ampproject.org/latest/
Update the masthead photo on this page to a presentation from AMP Conf. Suggest we use someone other than Paul since he is in other videos as well.

Possible photo options:
https://goo.gl/photos/VPdqf4j1AQ7VhwiY7
https://goo.gl/photos/chjuLkJrGggTvDzq7
https://goo.gl/photos/pBScFbnuN849EzeR9
https://goo.gl/photos/GHM3e4s9adn48Mc16

**Comment by SidVal** [comment]
Agree with you.
I vote for this pic: https://goo.gl/photos/chjuLkJrGggTvDzq7

If it was downloaded, renamed and replaced for  `https://github.com/ampproject/docs/blob/master/assets/img/latest/latest_hero.jpg`, will be work fine?

**Comment by pbakaus** [comment]
probably! But you should test it in a local build, and further minimize the image to a smaller file size, e.g. using something like https://tinyjpg.com/ or doing it manually. Go for it if you like!

**Comment by SidVal** [comment]
I tried to use grow, but I couldn't. So I can't test it in a local build. :( 

Sorry about that.

**Comment by pbakaus** [comment]
We should fix that! If you post your grow issues in the Slack channel ("docs"), we're happy to help you troubleshoot.

**Comment by bpaduch** [comment]
Definitely test it out.  I tried that pic but because of the dark screen on the left side, the words "Latest News" are difficult to read.  Need some good photo editing skills to lighten it or something else.
