### ISSUE TITLE
Vertical text on amp-access-laterpay !? 

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#431]
## Description of the issue:

Please provide:

- Page link: www.ampproject.org/docs/reference/components/dynamic/amp-access-laterpay
- Description of the documentation issue: 
Read the "property" - "values" - "description" section.
Why are the text written in vertical style? :-1:  

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to [amp-access-laterpay](https://www.ampproject.org/docs/reference/components/dynamic/amp-access-laterpay)
2. Scroll down to "`The following values can be set in the laterpay config object`" section
3. You may see it! 

What browser are you using? Chrome, last version. Desktop
What O/S are you using? Windows 7

**Comment by SidVal** [comment]
@bpaduch .. I still seeing the vertical align :sob:

**Comment by bpaduch** [comment]
Will be integrated in nightly build.
