### ISSUE TITLE
Sync up visibility v3 spec

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/docs#433]
See https://github.com/ampproject/amphtml/pull/8354

Thanks!

**Comment by bpaduch** [comment]
@dvoytenko - Can you clarify what "sync up visibility spec" means? I've looked at the doc changes you made iin https://github.com/ampproject/amphtml/pull/8354, and it looks fine.  Am I missing something?

**Comment by dvoytenko** [comment]
Yeah, just those changes in case there were any edits you'd rather make...
