### ISSUE TITLE
Wrong text / typo

### ISSUE THREAD

**Issue by ruborg** [ampproject/docs#442]
### Page: 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/amp-sidebar.md

### Issue:
Typo/wrong word: "lightbox" used instead of "sidebar" in this sentence:

> Alternatively pressing the escape key on the keyboard will also close the lightbox.

## Expected
Alternatively pressing the escape key on the keyboard will also close the **sidebar**.

**Comment by jridgewell** [comment]
Fixed.
