### ISSUE TITLE
Incorrect link: amp-fit-text docs link to amp-carousel example

### ISSUE THREAD

**Issue by ruborg** [ampproject/docs#443]
## Description:

Page: https://www.ampproject.org/docs/reference/components/presentation/amp-fit-text

Example link brings points to the wrong page

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1.  Follow link "Annotated code example that includes amp-fit"
2.  Brings you here: https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/

## Expected:
Brings you here: https://ampbyexample.com/components/amp-fit-text/

**Comment by jridgewell** [comment]
Fixed.
