### ISSUE TITLE
Document AMP Dev Channel

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#45]
All the info is here https://github.com/ampproject/amphtml/pull/2113

I just don't feel qualified to find the right place for this in our docs.

**Comment by Meggin** [comment]
Hey, Malte

I created this doc awhile back: https://www.ampproject.org/docs/reference/experimental.html

And I've also linked the intro tables in the specs to this experimental page, where relevant, for example in amp-access-spec, there's a link in Status: https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-spec.md

Note that I realize the link only works in ampproject.org (not in spec), and I'm fixing these now.

But as a solution-- how is this?

I like it, as there's a simple page, and then the specs indicate what it means very simply.

**Comment by cramforce** [comment]
I think we should just delete that experimental page. This doesn't need to be documented in a place where people that aren't at least on our Slack can see it. Github only is fine.

What we do want is tell people how to turn on dev channel, because that helps everyone.

**Comment by Meggin** [comment]
So how about just documenting the second part of the existing page, which
says how to enable channel (
https://www.ampproject.org/docs/reference/experimental.html - Opt into AMP
Dev Channel)?

I can make it the title in nav and on page.

Meggin

**Comment by cramforce** [comment]
Yep, but it should have at least all the info here:
https://github.com/ampproject/amphtml#amp-dev-channel
