### ISSUE TITLE
Ability to include required scripts for examples in reference docs

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#457]
**Want**: In a component's reference doc (e.g. [amp-img](https://www.ampproject.org/docs/reference/components/amp-img)) be able to easily include any required scripts for components that appear in an embedded example.

Right  now, to embed samples within a component's doc, you need the amp-iframe script and the associated scripts for any of the components in the example.  In guides, it's easy to include associated components because you can specify it in the yaml, like the following example, where I include the amp-iframe component:

```text
---
$title: Create Responsive AMP Pages
$order: 5
toc: true
components:
  - iframe
---
```

However, in reference docs, those docs are imported from the amphtml repo, and the markdown is converted.  Any yaml content in the component's original .md file is converted by the import-docs script.

**Workaround**: Specify script in [views/partials/head.html](https://github.com/ampproject/docs/blob/master/views/partials/head.html#L28), but this will bloat the files, including unnecessary amp scripts.

**Comment by bpaduch** [comment]
@pbakaus - Any chance you can look at this one.  I'd like to embed samples into the ref docs but I'm uncertain how to proceed.

**Comment by pbakaus** [comment]
np, will take a look now.

**Comment by pbakaus** [comment]
Et voila: https://github.com/ampproject/docs/pull/458

**Comment by bpaduch** [comment]
This is great and works, *except* if I have multiple samples in the same document, the component's required script is imported more than once so I'll have multiple instances of:

```html
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
```

Causing an AMP validation warning: "The tag 'amp-iframe extension .js script' appears more than once in the document. This will soon be an error."

Can you work s'more magic? :)

**Comment by pbakaus** [comment]
Ah good catch! Will take a look.

**Comment by pbakaus** [comment]
OK fingers crossed it's actually working now :)

**Comment by bpaduch** [comment]
Works. Thank you!
