### ISSUE TITLE
Improve CORS docs

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#478]
I heard the feedback that our CORS docs are confusing in two ways:

1. how they are written
2. how it is made clear that CORS stuff is even needed.

Maybe we can rewrite them and also audit all the places where we link to them and there highlight (like with a warning sign) that readers need to follow the links.

Our CORS docs are here:

https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md

It think it would be good to update this to be more friendly and to be rendered on the main site.

This is one example page that could be improved in terms of how it links to those docs https://www.ampproject.org/docs/reference/components/amp-list

CC @dvoytenko

**Comment by bpaduch** [comment]
- [x] Rewrite CORS spec/guide
- [ ] Update amp components' doc reference to call out using the CORS guide
- [ ] Include/import CORS guide into ampproject.org
