### ISSUE TITLE
Breadcrumb "Who is AMP for" is broken

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#481]
1. Go here: https://www.ampproject.org/learn/who-uses-amp/advertisers/
2. In the breadcrumbs, click "Who is AMP for".
3. Get a 404, it's looking for https://www.ampproject.org/learn/who-uses-amp/who-uses-amp/

**Comment by bpaduch** [comment]
cc: @derekcecillewis

**Comment by derekcecillewis** [comment]
Good catch! Should be taken care of with my PR.

**Comment by SidVal** [comment]
I've got a doubt here, did not know if I could talk here or should I open an other issue.

Check this:

1. https://www.ampproject.org/es/support/developer/
2. Breadcrump: Support >> Developer Support
3. If you click on "Support" link, goes to: https://www.ampproject.org/support/ (in English).

How do I edit the file to redirect to: https://www.ampproject.org/es/support/ ?

**Comment by bpaduch** [comment]
@SidVal - Localization breadcrumb fixes will be fixed in Derek's revised version of https://github.com/ampproject/docs/pull/486.
