### ISSUE TITLE
Move analytics-vendors to ampproject/amphtml

### ISSUE THREAD

**Issue by lannka** [ampproject/docs#489]
The [analytics-vendors page](https://www.ampproject.org/docs/guides/analytics/analytics-vendors) lists all AMP compatible analytics vendors. 

Can we move this file into `ampproject/amphtml` repo, so that new vendor can have all changes in one PR? Instead of doing context switching between 2 repos?

/cc @avimehta

**Comment by bpaduch** [comment]
We *can* but by keeping it in the Docs repo, we can localize it.  We've just recently had an external contributor translate the content into Spanish.  Since the CLA covers both repos, can we leave as is?

**Comment by lannka** [comment]
Should we also localize docs in the amphtml repo? We have many docs out there.

**Comment by bpaduch** [comment]
Eventually.  Our plan first is to localize the docset in ampproject.org.

**Comment by lannka** [comment]
Do we have overall guidelines where should a doc go? We right now have all ad vendors' docs in amphtml repo, but analytics vendors' docs in docs repo.

As long as it's consistent, either way is fine to me.

**Comment by bpaduch** [comment]
No, not at the moment.  For visibility we'd eventually like to see everything show up in ampproject.org - either by import or by living in the repo.  I'll set aside some time for Q3 to dig further into this (and meet with you and the team's feedback).

**Comment by bpaduch** [comment]
@lannka  - After talking with AMP DevRel and evaluating the pros/cons of single repo for docs vs. as is now, we'll keep things as they are.  That is, most spec-like docs will remain in amphtml repo (e.g., ad networks, components, specs).  Anything in-depth, like guides, will live in docs repo.  The analytics vendors file is less spec-like (no code configurations, like ads vendors), and has been translated into a number of languages, so we'll keep in docs repo.  HTH.

**Comment by lannka** [comment]
The reasoning makes sense. Thanks for following up on this.
