### ISSUE TITLE
Update for AMP HTML documentation regarding structured data

### ISSUE THREAD

**Issue by elegeros** [ampproject/docs#49]
The structured data example shown at https://www.ampproject.org/docs/get_started/create/basic_markup.html isn't sufficient to validate in the structured data testing tool. 

We should consider replacing this with the code in the example on:
https://developers.google.com/structured-data/carousels/top-stories

![screen shot 2016-02-24 at 5 32 58 pm](https://cloud.githubusercontent.com/assets/14796344/13306965/cdbadc0c-db1c-11e5-80d8-64448b7e22e6.png)

**Comment by cramforce** [comment]
@Meggin We should explain this and link out to Google's docs. AMP cannot aim to be complete in whatever Google would like to see there, but we can certainly point people over to Google.

**Comment by Meggin** [comment]
This commit fixes the docs:
https://github.com/ampproject/docs/commit/361884b79b4da4aaf7ef482cddaca2ac63b69257

Also have this pending PR to update the AMP HTML spec schema too:
https://github.com/ampproject/amphtml/pull/2490

**Comment by pbakaus** [comment]
Since both referenced commits are landed, closing this for now. Reopen if still needed. Thanks!
