### ISSUE TITLE
Amp Ads Templates?

### ISSUE THREAD

**Issue by chrisblakley** [ampproject/docs#504]
Just watched the Google I/O Amp Ads stream and they mentioned providing 6 templates for ad creators (and showed 3 examples), but I can't find where the templates are. Are they available yet, or was that something that was coming soon?

**Comment by bpaduch** [comment]
They are in AMP By Example - https://ampbyexample.com/amp-ads/#amp-ads/introduction

cc: @jasti

**Comment by chrisblakley** [comment]
Great- thanks for the quick response!
