### ISSUE TITLE
Case study menu too long for drop down

### ISSUE THREAD

**Issue by mattludwig** [ampproject/docs#509]
When hovering over the case study menu, I'm not able to see all the case studies available because there are too many to list on a smaller (13") screen. Bottom of attached screenshot is as far as I can see/select.

Can we add the categories here or is there a method we can scroll through them within the menu? We have more case studies coming, including CNBC which I just submitted the PR for. Thanks!

![screen shot 2017-05-22 at 8 08 12 pm](https://cloud.githubusercontent.com/assets/22876422/26333279/6b47195a-3f2a-11e7-8fac-0792876939c4.png)

**Comment by bpaduch** [comment]
Similarly reported issue - items at bottom of list aren't displaying and/or selectable:

![case-studies-menu](https://user-images.githubusercontent.com/1012254/27883774-b9495018-619f-11e7-9585-d8d0fd2c7ce1.jpg)

**Comment by sebastianbenz** [comment]
FYI we had the same problem with ABE for the components menu. We solved it by making the menu scrollable and giving it a fixed height based on the viewport height.
