### ISSUE TITLE
Source/preview tabs don't look like tabs

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#510]
The embedded source/preview with tabs don't appear to look like tabs, like in this [guide](https://www.ampproject.org/docs/guides/responsive/responsive_design#example:-embedding-a-youtube-video). Can we improve the styling?

![source-preview-tabs](https://cloud.githubusercontent.com/assets/1012254/26366013/7923d8a0-3fb7-11e7-9889-0707e084ead7.jpg)

**Comment by SidVal** [comment]
What do you think about this style?
https://codepen.io/oknoblich/pen/tfjFl

**Comment by bpaduch** [comment]
Looks cool, as long as it's in keeping with the design aesthetics of the site, @pbakaus is the expert on that.

**Comment by SidVal** [comment]
Yeap, I tried to apply the changes to https://ampproject-b5f4c.firebaseapp.com/examples/responsive.youtube.embed to preview but I had no luck :cry:
