### ISSUE TITLE
Build breaks for localized names in cards of "Who is AMP for?" page

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#519]
Testing the changes made in this PR https://github.com/ampproject/docs/pull/515 causes the build to break with the following error:

```text
Building: 2727/3566 (in 0:03:44)                                                                                                        [08:51:10] Error building: <Rendered(view='/views/about-who.html', doc='/content/learn/who-uses-amp@es.yaml', locale='es')>
  File "/usr/local/home/bpaduch/amp-docs/views/about-who.html", line 3, in top-level template code
    {% set navmarkup %}
  File "/usr/local/home/bpaduch/amp-docs/views/base.html", line 73, in top-level template code
    {% block main %}
  File "/usr/local/home/bpaduch/amp-docs/views/about-who.html", line 42, in block "main"
    <a class="card" id="{{card.name|slug}}" href="{{g.doc('/content/learn/who/' ~ card.name|slug ~ '.yaml', locale=doc.locale).url.path}}">
IOError: [Errno 2] No such file or directory: u'/usr/local/home/bpaduch/amp-docs/content/learn/who/editores.yaml'
Failed to execute script grow
```
Contents of `who-uses-amp@es.yaml`

```yaml
cards:
  - name@: Editores
    cta@: Aprender Más
    icon: who_icon_publishers.svg

  - name@: Plataformas Tecnológicas de Anuncios
    cta@: Aprender Más
    icon: who_icon_adtech.svg

  - name@: Editores
    cta@: Aprender Más
    icon: who_icon_advertisers.svg
```

Seems to be related to the code in  [views/about-who.html](https://github.com/ampproject/docs/blob/master/views/about-who.html#L42) for handling of card names.

Need to figure out a way to have those names translatable and still look for 'docs/content/learn/who/<cardname>.yaml` files.

cc: @SidVal

**Comment by SidVal** [comment]
Hello @bpaduch, a doubt here.
This issue is similar to #520 ?

**Comment by bpaduch** [comment]
Yeah, I know but different errors too. I suspect that the characters in KO caused an initial error that if those characters weren't present, would lead to the error I describe above.  As you'll notice, the KO file has English card names.
