### ISSUE TITLE
Hero subtitle in "Who is AMP for?" page doesn't pick up localized text

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#520]
On a localized page of "Who is AMP for" (like the [Korean page](https://www.ampproject.org/ko/learn/who-uses-amp/). The text "Join an ecosystem of 850,000 domains, leading platforms, and 100+ technology providers using AMP." should be translated.

Translations for that subtitle are present in the [KO file ](https://github.com/ampproject/docs/blob/master/content/learn/who-uses-amp%40ko.yaml#L9).

I believe the [views/about-who.htm](https://github.com/ampproject/docs/blob/master/views/about-who.html) needs to be corrected for the subtitle to pick up the localized term.

**Comment by SidVal** [comment]
Same happend with spanish localization https://www.ampproject.org/es/learn/who-uses-amp/ :cry:

**Comment by bpaduch** [comment]
Yep, that's where I noticed it when testing your changes.

**Comment by SidVal** [comment]
I should learn grow :smiley:

**Comment by bpaduch** [comment]
So, I looked into this, and it appears that this is a limitation in Grow.  Grow handles translations as an 'OR' condition, not an 'AND'.  That is, Grow will use translation variables OR localization file, but not both.  So, if you specify translation variables (e.g., via `@`), it'll just look for those.   So, in this case, the English file specifies translation variables, even though there are localized files.  To get grow to use the localized files, we must remove `@` from https://github.com/ampproject/docs/blob/master/content/learn/who-uses-amp.yaml. However, then those languages that have translated content (like IT), for that page will need to be added to localized files.

Resolution:  Will create localized files and remove translation variables syntax from English file.
