### ISSUE TITLE
ColAnalytics & Nielsen are not linked on supported platforms page

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#521]
Under analytics in https://www.ampproject.org/support/faqs/supported-platforms

It is confusing as to what that means.

Reported via https://twitter.com/theuserdesign/status/867755661014315009

**Comment by bpaduch** [comment]
Yeah, the links are pulled in from the [analytics-vendors.md](https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md) file, *if* there's a link present.

- For ColAnalytics, they have no link that I could ever find.
- For Nielson, they were just added, and didn't supply a link.

**Comment by cramforce** [comment]
Its a bit weird. Should we remove them from the analytics-vendors.md file then?
I think Nielsen might have fixed that since, right?

**Comment by bpaduch** [comment]
I agree it's weird for the ColAnalytics one.  It's a weird one. If you're okay with me removing them, I will. As for Niels  I've contacted the dev for Nielsen to supply a link, which I'll add.

**Comment by bpaduch** [comment]
Corrected.  If ColAnalytics provides a link, I'll add them back.  As for Nielsen, I just linked to their site.
