### ISSUE TITLE
AMP Landing Pages and AMP Ads blog post is not valid AMP

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#523]
Reported at [amphtml](https://github.com/ampproject/amphtml/issues/9579), moving there.

Page: https://www.ampproject.org/latest/blog/bringing-the-speed-of-amp-to-search-display-ads/
Errors:
631:189 The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'? 
639:43 The attribute 'type' may not appear in tag 'iframe'. 
639:43 The attribute 'allowfullscreen' may not appear in tag 'iframe'. 
639:43 The inline 'style' attribute is not allowed in AMP documents. Use 'style amp-custom' tag instead. 
639:43 The tag 'iframe' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-iframe'? 
644:43 The attribute 'type' may not appear in tag 'iframe'. 
644:43 The attribute 'allowfullscreen' may not appear in tag 'iframe'. 
644:43 The inline 'style' attribute is not allowed in AMP documents. Use 'style amp-custom' tag instead. 644:43 The tag 'iframe' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-iframe'?

**Comment by bpaduch** [comment]
Another blog post invalid AMP + weird display issues - https://www.ampproject.org/latest/blog/start-fast-with-new-amp-start-templates/

**Comment by bpaduch** [comment]
Fixed with Paul's mega blog fix in https://github.com/ampproject/docs/pull/724
