### ISSUE TITLE
Where is /reference/components/ docs?

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#536]
## Description of the issue:

I'm trying to add more translated content, and I can not find the docs for reference.

- Page link: https://www.ampproject.org/docs/reference/components/amp-iframe
- Description of the documentation issue: 
I found: https://github.com/ampproject/docs/tree/eeb3abee08c2ad482fdae1983e584a3b32dbde06/content/docs/reference/components/layout but, there are not files :cry:  

Thanks

**Comment by bpaduch** [comment]
Hi Sid, I'm not sure I understand the issue.  There is no landing page for "Layout" as it's category used to group those components that are related to layout, like here - https://www.ampproject.org/docs/reference/components#layout.

Does that help?

**Comment by SidVal** [comment]
Mmm forget the layout link.
I need the source file for https://www.ampproject.org/docs/reference/components/amp-iframe URL.
In "github" site :+1:

**Comment by bpaduch** [comment]
Ahhh, it's imported from amphtml repo.  All reference docs for components are imported via a script from the amphtml repo into this docs repo.  The component's document lives with the component, so, the original source file for amp-iframe is [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md).

**Comment by bpaduch** [comment]
And they remain in English.

**Comment by SidVal** [comment]
Ohh, nice info :+1:  
Thanks!
