### ISSUE TITLE
Invalid word breaking

### ISSUE THREAD

**Issue by kernc** [ampproject/docs#54]
Word breaking is invalid, unacceptable. The culprit must be hiding somewhere [in these lines](https://github.com/ampproject/docs/blob/5ce07f344ad482d23e34032e052d3849861cd6ba/_sass/content.scss#L42).
![what is amp 2016-03-02 20-37-04](https://cloud.githubusercontent.com/assets/684364/13472870/0ddf886a-e0b7-11e5-937a-59dbc7484265.png)

**Comment by Meggin** [comment]
Adding to first /docs milestone as part of cleaning up site messiness.

**Comment by pbakaus** [comment]
Fixed with the next deploy. Thanks for the report!
