### ISSUE TITLE
Documentation: HTML Tags reference doesn't provide the special 'rel' value for whitelisted font providers

### ISSUE THREAD

**Issue by atomicjack** [ampproject/docs#542]
Upon researching how to include fonts from Google Fonts, I came upon this documentation: https://www.ampproject.org/docs/guides/responsive/custom_fonts

In there, it states the following:

> Use a `<link>` tag (usually in the head of your page), like so:
> 
> `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">`
> The following origins are whitelisted and allowed for font serving via link tags:
> 
> Typography.com: https://cloud.typography.com
> Fonts.com: https://fast.fonts.net
> Google Fonts: https://fonts.googleapis.com
> Font Awesome: https://maxcdn.bootstrapcdn.com

This, however, is incorrect. The example mentions using 'rel="stylesheet' - but this isn't accurate, as 'stylesheet' is invalid for AMP.

I then landed on this documentation, under the HTML Tags section:
https://www.ampproject.org/docs/reference/spec

Which states:

> **link**	rel values registered on microformats.org are allowed. If a rel value is missing from our whitelist, please submit an issue. stylesheet and other values like preconnect, prerender and prefetch that have side effects in the browser are disallowed. There is a special case for fetching stylesheets from whitelisted font providers.

This states that, while 'stylesheet' cannot be used, there is a special case for fetching whitelisted font providers, but doesn't explain how to do so.

**Comment by bpaduch** [comment]
Hi atomicjack,


Yes, `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">` is allowed for the whitelist fonts, which were listed just below the example, that is:

- Typography.com: https://cloud.typography.com
- Fonts.com: https://fast.fonts.net
- Google Fonts: https://fonts.googleapis.com
- Font Awesome: https://maxcdn.bootstrapcdn.com

There's also further information  in the [Custom Fonts](https://www.ampproject.org/docs/reference/spec#custom-fonts) section of the HTML spec.

---

Perhaps this is an opportunity to clarify the docs.

On the [Custom Fonts](https://www.ampproject.org/docs/guides/responsive/custom_fonts) page: 

- Authors can include fonts through two ways:  `link` tags pointing to white-listed font providers (listed below) and by including `@font-face`.
    - Then state that the AMP spec only allows `link` with `rel=stylesheet` for whitelisted font providers.
    - Font providers can be whitelisted if they support CSS-only integrations and serve over HTTPS. 

On the [HTML spec](https://www.ampproject.org/docs/reference/spec), clarify that `stylesheet` can be exception for whitelisted font providers. And link to the relevant section.

---
Does that help?

**Comment by atomicjack** [comment]
@bpaduch - if it is allowed, then it would appear the AMP Validator is incorrect, as the following error appears when using <link rel="stylesheet" on a Google Font:

> The attribute 'rel' in tag 'link rel=' is set to the invalid value 'stylesheet'.

Which is the cause of the initial confusion over 'stylesheet' not being valid.

**Comment by bpaduch** [comment]
Just specifying the URL itself won't work:
`<link rel="stylesheet" href="https://fonts.googleapis.com" rel="stylesheet">`

Otherwise you get the error:
` The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https://fonts.googleapis.com'. Learn more.`

You need to pick a font and specify it (e.g., `/css?family=Roboto`)

Examples:
- `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">`
- ` <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400" rel="stylesheet">`

**Comment by atomicjack** [comment]
@bpaduch - this is the code I'm using:
`<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
`
That is what causes the error for being invalid, which, from what I can see, shouldn't be.

**Comment by bpaduch** [comment]
When I use that value, I don't get the error.  Which validator are you using?  Can you share the rest of your code?

**Comment by atomicjack** [comment]
@bpaduch - I'm using the official one, AMP Validator (https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc). 

It all works fine until that line is added - using a WordPress site with the AMP plugin by Automattic (which works fine on other sites without fonts being included). I can't show the full code as it is all separated out amongst the plugin + custom HTML, but the file affected is just the header:

```
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

<header id="#top" class="amp-wp-header">
	<div>
			<amp-img src="/example/image/url.png" width="450" height="60" layout="responsive" class="logo" alt="Logo">
			<noscript>
				<img src="/example/image/url.png" class="logo" />
			</noscript>
			</amp-img>
		<p class="site-sub">Rated 5 stars on TrustPilot</p>
		<a id="hamburger" on='tap:mainmenu.toggle'>&#9776; Menu</a>
	</div>
</header>
```

**Comment by bpaduch** [comment]
+ @amedina - Can you look at this; you know WordPress way more than I do.

**Comment by bpaduch** [comment]
Hmm, I think it's because that `<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">` is not in the `<head>`.  I can replicate the error if I put that line in the body.  Please try and put it in the `head`.

**Comment by amedina** [comment]
@atomicjack is there a link to the offending page?

**Comment by atomicjack** [comment]
@bpaduch that was it! I've now included it in the head via the AMP plugins' functions and voila! Thank you so much :)

**Comment by bpaduch** [comment]
Cool.  I've also submitted a recommendation to improve the error message.
