### ISSUE TITLE
Add amp-ad-exit markdown to ampproject.org

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/docs#564]
The validator link for amp-ad-exit currently 404s: https://www.ampproject.org/docs/reference/components/amp-ad-exit

It should be this markdown file: https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-exit/amp-ad-exit.md

**Comment by bpaduch** [comment]
Shouldn't this be a fix for the validator to point to the raw file -  https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-exit/amp-ad-exit.md?  The amp-ad-exit extension is for the amp4ads format, which isn't even listed on ampproject.org - all their docs remain in the amphtml repo.

**Comment by SidVal** [comment]
@honeybadgerdontcare you said:
>The validator link for amp-ad-exit currently 404s: ... 

Can you tell us please which URL are you seeing? 
I mean, where did you see that link to 404 ?

**Comment by bpaduch** [comment]
@SidVal - He saw it in the amp-ad-exit validator - https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-exit/validator-amp-ad-exit.protoascii, which generically points to the component's reference documentation.  However, this component isn't available yet, and it's all part of AMP4Ads.

**Comment by honeybadgerdontcare** [comment]
@bpaduch We tend to view ampproject.org as authoritative for amp "stuff". We didn't realize amp4ads only extensions wouldn't show up there. While we can force amp4ads links to go directly to github, maybe a fall back would be for ampproject.org to redirect to github as well in these cases.

@sidval this is the link that 404s: https://www.ampproject.org/docs/reference/components/amp-ad-exit

**Comment by bpaduch** [comment]
@lannka - In the past, anything related to amp4ads wasn't to be published on ampproject.org (reference https://github.com/ampproject/amphtml/issues/4965).  What should be happening for this particular extension (`amp-ad-exit`), which also doesn't seem complete, given the availability status of ["fill this in"](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-exit/amp-ad-exit.md).

**Comment by bpaduch** [comment]
@lannka, @taymonbeal - friendly ping.

**Comment by taymonbeal** [comment]
Hi, sorry I missed this. That issue was never meant to imply that amp4ads components shouldn't appear on ampproject.org. The reason we exclude `amp-ad-network-doubleclick-impl` and similar extensions is that they are internal implementation details of `<amp-ad>`; webmasters are never supposed to write `<amp-ad-network-doubleclick-impl>` in a document. That's not the case for `<amp-ad-exit>`; authors of AMP creatives do use it directly. So it should appear on ampproject.org.

**Comment by bpaduch** [comment]
Cool, thanks.  I'll import the doc; first going to clean it up.
