### ISSUE TITLE
Improvements to ads_getting_started doc

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#572]
Improvements to `/docs/guides/ads_on_amp/ads_getting_started.md`

When the doc is talking about [placeholder](https://github.com/ampproject/docs/blame/master/content/docs/guides/ads_on_amp/ads_getting_started.md#L46)

Maybe we can add a link (with note style):

```
{% call callout('Note', type='note') %}
[Learn more about `placeholder`](/docs/guides/responsive/placeholders#placeholders).
{% endcall %}
```

And when is talking about fallback attribute:

```
{% call callout('Note', type='note') %}
[Learn more about `fallback`](/docs/guides/responsive/placeholders#fallbacks).
{% endcall %}
```

***

PS: this is what I talking about in #566 to @bpaduch.

**Comment by SidVal** [comment]
@bpaduch, if you are agree, I can put a new PR for this.

**Comment by bpaduch** [comment]
@SidVal - Yes, thanks.
