### ISSUE TITLE
Missing rule in example

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#581]
- Page link: https://www.ampproject.org/docs/guides/responsive/responsive_design
- Description of the documentation issue:

Here at the **Restricting width of responsive images** example:
https://www.ampproject.org/docs/guides/responsive/responsive_design#example:-restricting-width-of-responsive-images

Said:

>However, we want the image to not stretch beyond its intended size, so we set the `max-width` on the container to 700 px.

I (as a reader) understand that the example have got the `max-width` rule.
But, it hasn't.

Can you check the code please?
```
<div class="resp-img">
  <amp-img alt="flowers"
    src="images/flowers.jpg"
    layout="responsive"
    width="640"
    height="427"></amp-img>
</div>
```

**Comment by SchnWalter** [comment]
@SidVal, would you care to give your opinion  on ampproject/amphtml#7009? Thanks!

**Comment by SidVal** [comment]
Hi @SchnWalter, I'm relatively new here and that link to 7009 amp's issue it's just great! 

The info that you [posted here](https://github.com/ampproject/amphtml/issues/7009#issuecomment-311246429) is excellent. Thank you!

Concluding, with the information I read thanks to your post, I think the _[doc for Responsive Design](https://www.ampproject.org/docs/guides/responsive/responsive_design)_ are outdated.

We will see what the rest of the official Documentation team thinks.

**Comment by SchnWalter** [comment]
@SidVal, that is just a discussion, those arguments aren't implemented yet, and we need some more feedback before we can proceed. Please take a look at the exeptions in the table for the last comments and see if you can provide some feedback.

Have a great day!

**Comment by bpaduch** [comment]
@SidVal - I wouldn't say the documentation is out-of-date; rather it needs clarification that thee max-width is applied via CSS in the container's "resp-img" class. I've clarified the wording in the doc (https://github.com/ampproject/docs/commit/8cabfc33e185393251c7432d1f5cf1ea8e7dddf9).

**Comment by SidVal** [comment]
Thanks Barb., can we add some link to better reference and understanding for "resp-img" class? 

About the out-of-date thing.
_[This doc](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#sizes)_ confused me. Sorry about that.

I read this code:
```
<amp-img src="https://acme.org/image1.png"
    width="400" height="300"
    layout="responsive"
    sizes="(min-width: 320px) 320px, 100vw">
</amp-img>
```
I did not read about the uses of the `sizes` attribute.
So that confused me.

**Comment by bpaduch** [comment]
I'd love to include the CSS in the "Source" tab so it's clear that I'm using a basic CSS class named "resp-img" that has the `max-width: 700px;` but the Source/Preview tab feature extracts only the relevant AMP code for the example from a [larger file source](https://github.com/ampproject/docs/blob/master/examples/src/responsive.html#L10). I didn't think it was a big deal because it's basic CSS. I'll look into a better way to clarify.

**Comment by SidVal** [comment]
Well this is disappointing, because I searched about that class _[here](https://github.com/search?q=org%3Aampproject+resp-img&type=Code)_ (in the project), and there isn't any doc or explanation about this css class :-1:  

I'm sure it's basic css, but... we are documenting to clarify to the people how to have a better web, and how to optimize the user experience through AMP pages.

If to delimit the width of images, I also have to add basic CSS to the style of the page (in the header), in my opinion, it is something that we must clarify and leave well explained somewhere.

**Comment by bpaduch** [comment]
I'll investigate.

**Comment by bpaduch** [comment]
How about this:


![include-max-width](https://user-images.githubusercontent.com/1012254/27606868-ddbcd952-5b4f-11e7-849c-c59f4fd580b8.jpg)

**Comment by SidVal** [comment]
I think it's great!
