### ISSUE TITLE
Error 404 https://www.ampproject.org/es/docs/guides/debug/validate

### ISSUE THREAD

**Issue by robiscjuan** [ampproject/docs#584]
## Description of the issue:

Please provide:

Error 404 at https://www.ampproject.org/es/docs/tutorials/create/preview_and_validate . The wrong link goes to https://www.ampproject.org/es/docs/guides/debug/validate.

**Comment by bpaduch** [comment]
Thanks for reporting.  A fix has been submitted in https://github.com/ampproject/docs/pull/579, which is being merged into Production today.
