### ISSUE TITLE
Improve "Discovery" Guide w/ examples and diagrams

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#592]
There's a lot of questions/confusion over canonical linking and rel=amphtml, let's improve this doc with examples and diagrams.

**Comment by SidVal** [comment]
> (...) with real-life examples (...)

What sites can we referer? :roll_eyes:

**Comment by bpaduch** [comment]
Correction -examples.

**Comment by SidVal** [comment]
I mean if we are going to quote real websites or if we are going to put invented examples to give a better understanding of how the <link> tag works?

**Comment by bpaduch** [comment]
We aren't using real sites, but we'll use examples to clarify the
relationship b/w canonical and rel=amphtml.

**Comment by bpaduch** [comment]
Closing as already documented in this tutorial - https://www.ampproject.org/docs/fundamentals/converting/discoverable
