### ISSUE TITLE
One item invisible on hover of the menu

### ISSUE THREAD

**Issue by aghassemi** [ampproject/docs#598]
Moved from amphtml repo: https://github.com/ampproject/amphtml/issues/10259 

Reported by @zahiribishi 

*You have a bug in menu
![bug](https://user-images.githubusercontent.com/15115833/27859146-18d9c53a-6178-11e7-9d09-ed3fcf3105db.png)

**Comment by bpaduch** [comment]
Closing this issue as there's an already existing issue that's similar/duplicate  - https://github.com/ampproject/docs/issues/509
