### ISSUE TITLE
add list of components with validator status and experiment status

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/docs#6]
a few people have been asking for this, its a little hard to figure out if something should be turned on in experiments or if something is not in the validator yet which is why they are getting errors.

**Comment by rudygalfi** [comment]
:+1:

**Comment by kzap** [comment]
the only docs so far on how to use the experiments or what they are is here:
https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md
and here:
https://cdn.ampproject.org/experiments.html

**Comment by Meggin** [comment]
Done. We've got an experimental docs page here: https://www.ampproject.org/docs/reference/experimental.html

And the new intro tables in the specs link to this page (if the component is still experimental).

See amp-access-spec (note link works in ampproject.org, but I need to make it work in amphtml as well-- doing this for launch, and this can be closed once sorted).

**Comment by Meggin** [comment]
This was done for public launch. Each component has an intro and validation table. If relevant, validation table links to experimental page.
