### ISSUE TITLE
Lets not advertise iframes so front and center

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#61]
As in this page https://www.ampproject.org/docs/guides/amp_replacements.html#display-an-iframe

Also the example is incomplete, because it is missing the needed script tag, so copy pasting from the docs would be broken.

**Comment by pbakaus** [comment]
I'm torn on this. Not a huge fan of iframes, but they're used to get stuff done right now when there isn't a component for AMP. How would you restructure the page?

**Comment by cramforce** [comment]
Media first, then iframes.

**Comment by pbakaus** [comment]
Ah. Easy enough :) Fixed with next deploy.
