### ISSUE TITLE
Create paywall/amp-access guide

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#62]
If I go to our docs thinking I want to implement a paywall, there is no way I find the amp-access page.

**Comment by Meggin** [comment]
We need a better set of paywall docs in general. Adding this to our first /docs milestone and marking it critical.

**Comment by bpaduch** [comment]
@cramforce - Would you still consider this a high-priority request considering we do have [amp-access](https://www.ampproject.org/docs/reference/components/dynamic/amp-access) docs.

**Comment by cramforce** [comment]
@bpaduch Not at all. Paywalls might be rare and different enough to not warrant additional docs, and what we have is pretty good.

**Comment by bpaduch** [comment]
Closing issue as docs are sufficient.
