### ISSUE TITLE
Text wraps poorly on doc categories

### ISSUE THREAD

**Issue by rosa-g** [ampproject/docs#621]
**Page links:**
https://www.ampproject.org/docs/guides/
https://www.ampproject.org/docs/reference/

**Description of the documentation issue:**
See included screenshot. Some of the text wraps in an unpleasant manner.

<img width="1073" alt="screen shot 2017-07-16 at 10 23 17 pm" src="https://user-images.githubusercontent.com/30220234/28256311-e94a639a-6a75-11e7-90da-d6222719d3b0.png">

**What browser are you using?**
Chrome 59.0.3071.115

**What O/S are you using?**
macOS 10.12.2

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/docs/commit/40a7e1388d64084d9e4abd2ad05b5bdd687e58ce
