### ISSUE TITLE
Document XHR batching

### ISSUE THREAD

**Issue by choumx** [ampproject/docs#624]
It's currently not obvious that we batch XHRs for JSON endpoints (currently amp-list and amp-state) and we've gotten feature requests for it even though it already exists (https://github.com/ampproject/amphtml/issues/7463#issuecomment-278828054). 

The way it works is the following: if an amp-list makes an XHR to endpoint A, while that XHR is in flight, all subsequent XHRs to A (e.g. from other amp-lists) won't trigger and instead return the first XHR's result.

This is useful because amp-list supports rendering from a subset of a JSON result via the `items` attribute: https://www.ampproject.org/docs/reference/components/amp-list#items-(optional) 

For example, two amp-lists can render different content and share a single XHR.

/cc @cvializ

**Comment by bpaduch** [comment]
So, this is only required in those two components: amp-list and amp-bind?

**Comment by choumx** [comment]
Yea, only amp-list and amp-state exhibit this behavior so far.
