### ISSUE TITLE
amp-font docs should be more use case driven

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#65]
Right now it is super hard to understand what `amp-font` is for.

@sriramkrish85 Could you work with @Meggin on this? Thanks!

**Comment by sriramkrish85** [comment]
Yes i will work with @Meggin . Assigning to her so that she can grab me when she has time.

**Comment by bpaduch** [comment]
@cramforce - Can we close this one as this appears to be documented well on https://www.ampproject.org/docs/reference/components/amp-font?
