### ISSUE TITLE
Grey text on light grey background is very difficult to read for the vision impaired

### ISSUE THREAD

**Issue by mark-iennaco** [ampproject/docs#67]
Options for a higher contrast (and other accessibility options) are highly desirable.

**Comment by mark-iennaco** [comment]
Just for reference:
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

**Comment by pbakaus** [comment]
This is fixed in the code, and will be rolled out with the next deploy (today or tomorrow). Thanks!
