### ISSUE TITLE
Explicitly document HTTPS requirement

### ISSUE THREAD

**Issue by paulschreiber** [ampproject/docs#670]
Currently, the need to use HTTPS with is documented only where `src` attributes are listed:

* amp-ad: https://www.ampproject.org/docs/reference/components/amp-ad
>AMP documents only support ads/embeds served via HTTPS.

* amp-video: https://www.ampproject.org/docs/reference/components/amp-video#src
>Required if no <source> children are present. Must be HTTPS.

* amp-list: https://www.ampproject.org/docs/reference/components/amp-list#src-(required)
>The URL of the remote endpoint that returns the JSON that will be rendered within this amp-list. This must be a CORS HTTP service. The URL's protocol must be HTTPS.

It would be very helpful if a broad statement explaining HTTPS is required for AMP sites was included.

**Comment by paulschreiber** [comment]
@rudygalfi

**Comment by rudygalfi** [comment]
As far as I know, for caching support reasons, HTTPS is generally required for anything except the document itself, images, and fonts.

This seems invariant enough and useful enough to note in a more prominent place.

**Comment by paulschreiber** [comment]
It would helpful to have a statement such as "the document and all assets must be served over HTTPS."

**Comment by bpaduch** [comment]
I wouldn't put a statement that "all documents and assets have to"; however, it's strongly recommended to use HTTPS because your choices of AMP components and interactivity are limited.
