### ISSUE TITLE
Contrast is unreadably low

### ISSUE THREAD

**Issue by craigdberry** [ampproject/docs#68]
E.g. https://www.ampproject.org/docs/support/faqs.html#how-do-accelerated-mobile-pages-work

As a visually impaired person, the text on that page is nearly invisible. Even my coworkers with normal vision report that it is hard for them to read. Please adjust the contrast to meet the usual web accessiblity guidelines.

**Comment by pbakaus** [comment]
Fixed with the next deploy, closing for now.
