### ISSUE TITLE
New supported platform (CMS): Kentico

### ISSUE THREAD

**Issue by petrsvihlik** [ampproject/docs#686]
Hi,
we've finished implementation of a Google AMP module for Kentico CMS and Kentico EMS.

You can find the sources here: https://github.com/Kentico/kentico-amp
NuGet: https://www.nuget.org/packages/Kentico.AcceleratedMobilePages/

Sample implementation: 
- HTML: https://advantage.kentico.com/introduction ->
- AMP HTML: https://amp.advantage.kentico.com/introduction

A blogpost about how we implemented it: https://devnet.kentico.com/articles/google-amping-the-kentico-advantage-site

Could you please include Kentico in supported platforms with a link to the GitHub repo?

Thanks!

**Comment by petrsvihlik** [comment]
Hi @pbakaus ! Do you have any ETA on this? Thank you

**Comment by petrsvihlik** [comment]
Created a PR: https://github.com/ampproject/docs/pull/721

**Comment by pbakaus** [comment]
Looks good, sorry for the delay and thanks for the contribution!

**Comment by petrsvihlik** [comment]
hi @pbakaus, thank you! Do you have any idea when it's gonna be deployed live? https://www.ampproject.org/support/faqs/supported-platforms

**Comment by pbakaus** [comment]
It's live!

**Comment by petrsvihlik** [comment]
phenomenal! thx @pbakaus :)
