### ISSUE TITLE
document a solution to do 'post' with body with amp-form and page reload

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/docs#689]
For https://www.ampproject.org/docs/reference/components/amp-form
Currently in the documentation of amp-form, it is not clear how to do a page reload (similar to submit a form to a new page) when having a body payload in the form.  Many publishers are confused by this discrepancy in form submission behavior comparing to a regular `<form method='post'>` element.
Right now the document says to use action-xhr but never answers the question how to achieve the page reload to an action url.

**Comment by bpaduch** [comment]
@aghassemi - Can you provide some insight?

**Comment by aghassemi** [comment]
Hi @AndrewKGuan, this is documented under `Redirecting after a submission` section on https://www.ampproject.org/docs/reference/components/amp-form#redirecting-after-a-submission 

Essentially, you just need to return a `AMP-Redirect-To: https://example.com/` as part of the HTTP response header of the POST action.

**Comment by AndrewKGuan** [comment]
Hi, thanks for pointing me to the right place.  But after reading the that section, Im still not sure what's the right code.  Is it <amp-form method=post amp-redirect-to:"https://example.com>  or <amp method=post><amp-redirect-to:https://example.com></amp-redirect-to></amp-form>?

**Comment by aghassemi** [comment]
It has to be present in the HTTP response (similar to [CORS related headers](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md)), it is not an attribute on the form. 

@bpaduch Maybe we can improve the docs to make this clear? I can see the confusion as everything else is pretty much an attribute except this one.
