### ISSUE TITLE
The media attribute example should show how to select an image based on screen width

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#7]
The current example is kind of useless. Usually you want e.g. one image with a max-width and one with a min-width, so that only one is shown.

**Comment by Meggin** [comment]
Wrote a better set of responsive docs, which includes a section on creating responsive images, that also uses srcset. Also better describe 'w' in srcset. It's not perfect, but it's better.

We still have the media example, as it's separate to srcset. Not too sure if we want to remove this all together, as it's a different use case.
