### ISSUE TITLE
Some errors to fix in new tutorials

### ISSUE THREAD

**Issue by SidVal** [ampproject/docs#710]
Some corrections:

## Missing text TODO

- [Page link](https://www.ampproject.org/docs/tutorials/interactivity/advanced-interactivity#bind-the-image-elements) - [Source](https://github.com/ampproject/docs/blob/master/content/docs/tutorials/interactivity/advanced-interactivity.md#bind-the-image-elements)

- Description of the documentation issue:
Check the info, it is incorrect, because there is not exist this text:
>Bind the image elements
>Then, add bindings to the <amp-img> elements inside the <amp-carousel> (look for `<!-- TODO: "Changing images in amp-carousel-->"`) ...

Referer: https://github.com/SidVal/docs/issues/58

***

## Error link

- [Page link](https://www.ampproject.org/docs/tutorials/interactivity/remote-data) - [Source](https://github.com/ampproject/docs/blob/master/content/docs/tutorials/interactivity/remote-data.md)

- Description of the documentation issue:
Check the link for "src", has got a mistake:
> `[`src`](https://www.ampproject.org/docs/reference/components/amp-<bind id="attributes"></bind>)`

Referer: https://github.com/SidVal/docs/issues/59

***

## CTA: note link

- [Page link](https://www.ampproject.org/docs/tutorials/add_advanced) - [Source](https://github.com/ampproject/docs/blob/master/content/docs/tutorials/add_advanced.md)
- Description of the documentation issue:
Check this note, both link are for same URL, is that correct?
>NOTE — This tutorial is a continuation of the concepts introduced in the "Convert your HTML to AMP" tutorial. If you don't already have a basic understanding of AMP’s core concepts, please try out the "Convert your HTML to AMP" tutorial.

Referer: https://github.com/SidVal/docs/issues/62

***

**Comment by bpaduch** [comment]
1. Yes, that "todo" text is in the source code.  See https://github.com/googlecodelabs/advanced-interactivity-in-amp/blob/master/static/index.html#L155.
2. Fixed in your PR https://github.com/ampproject/docs/pull/711
3. CTA: note link -- It's correct

If there's nothing else, let's close this issue.

**Comment by SidVal** [comment]
Ah perfect.

Thanks!
