### ISSUE TITLE
Documentation issue with amp-list. "single-result" attribute is documented whereas validator uses "single-item"

### ISSUE THREAD

**Issue by diegovar** [ampproject/docs#712]
## Description of the issue:

The documentation for amp-list specifies that the "single-result" attribute can be used, but the validator uses "single-item".

Please provide:

- Page link: <insert the URL link to the ampproject.org page(s) that you found the issue on>
https://www.ampproject.org/docs/reference/components/amp-list#validation
https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/validator-amp-list.protoascii
- Description of the documentation issue:

## How do we reproduce the issue?
Attempting to use the "single-result" attribute in an amp-list triggers a validation error.

**Comment by bpaduch** [comment]
I'm closing this issue because the documentation and code were updated in https://github.com/ampproject/amphtml/pull/11524.  Once the production build runs tonight, it'll pick up the changed documentation.
