### ISSUE TITLE
Analytics vendors not up to date

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#713]
I noticed that the analytics vendors file is now maintained in the docs repo. This means it cannot be updated in line with new vendors coming on board anymore.

@bpaduch Could we do a round of updates and find a process to update it on a regular basis?

https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md

CC @zhouyx @lannka @rudygalfi

**Comment by bpaduch** [comment]
As part of implementing a new analytics configuration, a step should be added to the ["Integrating Analytics"](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md#adding-your-configuration-to-the-amp-html-runtime) process doc that indicates creating a PR to ampproject/docs to add vendor to [Analytics Vendor](https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md) list.
