### ISSUE TITLE
AMP v0 stability inconsistent with semantic versioning meaning of version 0.

### ISSUE THREAD

**Issue by diegovar** [ampproject/docs#714]
Use the following template to report documentation issues for the www.ampproject.org site.  

**Note**: For issues or questions about AMP (e.g., how it works, bugs with syntax, etc.) please do the following:

- Ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ
- [File bugs in AMP](https://github.com/ampproject/amphtml/issues/new)

## Description of the issue:

AMP is currently in version 0:

According to https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md , AMP follows semantic versioning. According to http://semver.org/#spec-item-4:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Is this the case? If it's not, can it be clarified in https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md ?

Please provide:

- Page link: https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md

**Comment by cramforce** [comment]
Not sure this is super important to clarify, but happy to against a PR against the MD file with something like

- For sad historical reasons many version numbers start at zero, which was a bad idea.

**Comment by bpaduch** [comment]
Clarification provided here; leaving as is and closing.  If you feel this should remain open, please let me know.
