### ISSUE TITLE
Text on main Docs page overruns its containers at certain viewport sizes

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#723]
https://www.ampproject.org/docs looks wonderful at standard desktop browser sizes and mobile sizes, but for other sizes, containers overflow and the word "Introduction" doesn't break (it needs a soft hyphen or "hyphens: auto".

<img width="641" alt="screen shot 2017-10-18 at 11 46 15 am" src="https://user-images.githubusercontent.com/29419498/31736677-43a8abda-b3fa-11e7-97dd-15c288e49028.png">

**Comment by bpaduch** [comment]
Closed in https://github.com/ampproject/docs/pull/725
