### ISSUE TITLE
Mustache syntax gets partially eaten on amp-mustache reference page.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/docs#73]
https://www.ampproject.org/docs/reference/extended/amp-mustache.html

Looks like something gets eaten there. E.g.:
"Notice also that because the body of the template has to be specified within the template element, it is impossible to specify expressions - they will always be escaped as. The triple-mustache } has to be used for these cases."

Original text from https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md:
"Notice also that because the body of the template has to be specified within the template element, it is impossible to specify {{&var}} expressions - they will always be escaped as {{&amp;var}}. The triple-mustache {{{var}}} has to be used for these cases."

This effect applies to this entire page - several of the curly braces get lost in translation.

**Comment by powdercloud** [comment]
@Meggin

**Comment by Meggin** [comment]
Adding this to our first /docs milestone as part of cleaning up site messiness.

**Comment by pbakaus** [comment]
This is fixed (and updated on the megamerge branch, will be deployed soon).
