### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by causevicamir** [ampproject/docs#738]
Use the following template to report documentation issues for the www.ampproject.org site.  

**Note**: For issues or questions about AMP (e.g., how it works, bugs with syntax, etc.) please do the following:

- Ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ
- [File bugs in AMP](https://github.com/ampproject/amphtml/issues/new)

## Description of the issue:

Please provide:

- Page link: https://www.ampproject.org/docs/tutorials/interactivity/advanced-interactivity.html
- Description of the documentation issue: Broken link

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Go to the link

What browser are you using? Firefox
What O/S are you using? Linux

**Comment by bpaduch** [comment]
Thanks. Similar issue with another file (https://github.com/ampproject/amphtml/issues/11917).  I'm rerunning the build to see if that resolves it.

**Comment by bpaduch** [comment]
Thanks for reporting this!
Fixed for now; built with Grow 3.9.
