### ISSUE TITLE
HTTPS compatibility issues

### ISSUE THREAD

**Issue by valtido** [ampproject/docs#753]
I was rewriting all the urls by omitting the protocols from urls from `https://www.example/amp/` to `//www.example/amp/` then on google search console under "Accelerated Mobile Pages" It started going all wrong with loads of pages being reported incorrect.

> The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.

I suppose the checks try to match exact urls including the protocols. I would suggest that we fix this to match without protocols "http/https" on the script tags and other elements.

Any thoughts?

**Comment by bpaduch** [comment]
This appears to be a Google Search Console question.  I suggest you post your question on the Webmasters forum - https://productforums.google.com/forum/#!forum/webmasters.

**Comment by valtido** [comment]
ok it also the same thing happens on this amp test page by google

https://search.google.com/test/amp 

when you test the page but I will post it at the suggested link.
