### ISSUE TITLE
Automate callouts

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#757]
Right now, we have to add some markup (like below), which muddies the markdown (example, the [amp-analytics component has a callout in the markdown file](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md)).

Markdown:

```
{% call callout('Read on', type='read') %}
Your text here.
{% endcall %}
```
Renders as:

![note-callout](https://user-images.githubusercontent.com/1012254/33083076-67c543bc-ceac-11e7-8d6c-87aba97f6041.png)

Possible issue: Grow has no pre-process step; might need this; Should ask Grow team (Jeremy) how he'd do this. Instead of calling Grow Run, call npm run, run other script before.

**Comment by johnw123** [comment]
If you’re looking for <a href="https://www.etech7.com/managed-it-services-in-nyc">Managed IT Services in NYC</a>, Etech7 is the right place for you. I’m a dummy in IT sphere, so all the time I need a good company to solve my IT problems. Finally I’ve found Etech7 and  when I need <a href="https://www.etech7.com/it-consulting">IT Consulting</a>, I’ll definitely call them.

**Comment by pbakaus** [comment]
This work is currently happening here: https://github.com/ampproject/docs/tree/feature/ext-pre-render

**Comment by matthiasrohmer** [comment]
Has been implemented in the meantime.
