### ISSUE TITLE
ampproject.org front page has deprecated boilerplate

### ISSUE THREAD

**Issue by Gregable** [ampproject/docs#77]
The root document only, as far as I can tell, is using the deprecated style AMP boilerplate, producing validation warnings when using '#development=1'. These will eventually be promoted to errors.

**Comment by Gregable** [comment]
@pbakaus

**Comment by Meggin** [comment]
Adding this issue to the first docs milestone. This is part of making sure ampproject.org is valid AMP.

**Comment by honeybadgerdontcare** [comment]
Ping. What is the eta on this?

**Comment by honeybadgerdontcare** [comment]
FYI, the extension is launched which would make this obvious to users of the extension when visiting ampproject.org.

**Comment by pbakaus** [comment]
ETA sometime next week, when I get to merge the front page repo (currently not open source yet) with the main repo.

**Comment by Meggin** [comment]
Fixed this today. Check out validation in https://www.ampproject.org/

**Comment by honeybadgerdontcare** [comment]
Thanks for getting these in!
