### ISSUE TITLE
Code of Conduct URL 404's

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#772]
This page 404's:

https://www.ampproject.org/amp-conf-2017/code-of-conduct/

If anyone has time to look at this, it would be useful, as we link to it from the AMP Roadhshow deck, which we're using tomorrow in Beijing. (I know I should just debug it myself, but I'm doing other things to prep for that right now... apologies...)

**Comment by bpaduch** [comment]
Curious that you're using an old AMP Conf page.  And that it's not an AMP Roadshow page.

**Comment by bpaduch** [comment]
I've set up a redirect to the correct link: https://www.ampproject.org/amp-conf/code-of-conduct/

**Comment by morsssss** [comment]
thanks! much appreciated!

(I didn't make the deck this came from, so I don't know how it got in there...)
