### ISSUE TITLE
"TM" in blog post title is large and bolded

### ISSUE THREAD

**Issue by mattludwig** [ampproject/docs#779]
For some reason the "TM" in the title of the blog post is large and/or bolded. It should be smaller and not as prominent. 

https://www.ampproject.org/latest/blog/the-total-economic-impact-of-amp-across-publishers-and-e-commerce/

**Comment by bpaduch** [comment]
I believe this is an issue (an interesting one) with Google fonts.  

Related issues: https://github.com/google/fonts/issues/237 & https://github.com/google/fonts/issues/78

**Comment by bpaduch** [comment]
I'm closing this because it's out of our control.  It's a Google Fonts issue.
