### ISSUE TITLE
Some documents on ampproject.org have validation errors

### ISSUE THREAD

**Issue by Gregable** [ampproject/docs#78]
https://www.ampproject.org/docs/support/faqs.html#development=1
2 errors.

1.  Caused by this tag: `<a class="tab hamburger" id="menu-button" href="">&#x2261;</a>`. The empty href is considered invalid.
2.  Caused by this script tag: 
```
    <script>
    document.getElementById('menu-button').onclick = function() {
      document.getElementsByTagName('header')[0].classList.toggle('menu-open');
      document.querySelector('div.content').classList.toggle('menu-open');
      document.querySelector('nav').classList.toggle('menu-open');
      return false;
    };
    </script>
```

**Comment by Gregable** [comment]
@pbakaus

**Comment by cramforce** [comment]
@sriramkrish85 Could you port this to `amp-sidebar`?

**Comment by Meggin** [comment]
Added this one to our first docs milestone. We need to replace the current navigation with a proper amp-sidebar that passes amp validation.

**Comment by honeybadgerdontcare** [comment]
Ping. What is the eta on this?

**Comment by erwinmombay** [comment]
think I had this conversation with @Meggin, that we'd replace the current js script with the amp-sidebar implementation. ETA on it for me to start working on it was after I/O, unless @sriramkrish85 wants to take over it

**Comment by honeybadgerdontcare** [comment]
FYI, the extension is launched which would make this obvious to users of the extension when visiting ampproject.org.

**Comment by pbakaus** [comment]
Fixed it in https://github.com/ampproject/docs/commit/25e9bee8431e0949df35e45130dcf6ed8c8cb198
