### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#786]
Our current 404 page is not bad:

<img width="841" alt="screen shot 2017-12-15 at 10 10 22 am" src="https://user-images.githubusercontent.com/29419498/34048040-37fc91a8-e180-11e7-862b-ba936611411b.png">

But I wonder if we can make it more AMPy.  Perhaps, for example, mentioning that the 404 page itself is AMP and thus at least we hope it provided a good user experience.  And perhaps we could include links to commonly accessed site areas?

**Comment by bpaduch** [comment]
This might be the answer (just merged today): https://github.com/ampproject/docs/pull/761

**Comment by morsssss** [comment]
Brilliant!
