### ISSUE TITLE
Table for control_layout is not well formatted on ampproject.org

### ISSUE THREAD

**Issue by cartland** [ampproject/docs#79]
The table for control_layout is hard to read:
https://www.ampproject.org/docs/guides/responsive/control_layout.html

It looks fine on GitHub.
https://github.com/ampproject/docs/blob/master/_guides/responsive/control_layout.md

Desktop screenshot:
<img width="992" alt="control_layout_website" src="https://cloud.githubusercontent.com/assets/846051/14443697/ad21180a-fff5-11e5-839a-5392196c82f9.png">

Mobile web screenshot:
<img width="201" alt="ampproject_control_layout" src="https://cloud.githubusercontent.com/assets/846051/14443737/f09a8512-fff5-11e5-9056-2ea423a2632a.png">

GitHub mobile web screenshot:
<img width="199" alt="github_control_layout" src="https://cloud.githubusercontent.com/assets/846051/14443745/f5d6324c-fff5-11e5-801c-2e0a021b4350.png">

**Comment by Meggin** [comment]
Thanks for raising this issue. Somehow the css got removed. I'll add it back in.

**Comment by Meggin** [comment]
This commit fixes the issue: https://github.com/ampproject/docs/commit/c5ec066a05f9762c7dd126d39c53108408ce3597

Will push to production over the next day.
