### ISSUE TITLE
Build breaks on "AssertionError: Task function must be specified"

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#793]
Travis build from last night and today for Production and Master breaks with the following error:

```
assert.js:81
 throw new assert.AssertionError({ ^AssertionError: Task function must be specified
    at Gulp.set [as _setTask] (/home/travis/build/ampproject/docs/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/travis/build/ampproject/docs/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/travis/build/ampproject/docs/gulpfile.js:83:6)
```
![gulp-break](https://user-images.githubusercontent.com/1012254/34494218-6444d0d6-efbd-11e7-902e-2742ffe83967.png)

Worked fine for previous night's build.
What's different:  Last night's build uses gulp@4.0.0.

**Comment by bpaduch** [comment]
- Gulp 4.0.0 was released two days ago: https://github.com/gulpjs/gulp/releases/tag/v4.0.0
- Gulp 4.0 changes the way function are to be defined, so we need to update our gulpfile.js (per this [Medium blog](https://medium.com/@_jh3y/switching-to-gulp-4-0-271ae63530c0)
- For now, restricting build to Gulp 3.9.1 - https://github.com/ampproject/docs/commit/ae83e4cb904080d7ff39e36e883886623b7f736e

**Comment by bpaduch** [comment]
Closing by using workaround of Gulp 3.9.1.

**Comment by charlotteyizhang** [comment]
To solve for gulp >4 when you are using gulp.task('default',['**task**'], function(){});
replace ['task'] with gulp.series('task') or gulp.parallel('task')
Hope this can solve your problem :) 
I found this solution here: https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/

**Comment by anjasmaradwisetiadi** [comment]
i have same problem, but i have solved this problem. i suggest you first first make sure npm install your not problem. then you downgrade version node and gulp. i used version node 10.16.1 and gulp 3.9.1.
for downgrade your gulp you can write 
"**npm install gulp@^3.9.1**"

**Comment by ezrqnkemboi** [comment]
@charlotteyizhang solved my problem. 
I think there might not be need of downgrading the version.

**Comment by kennblvnp** [comment]
@ezrqnkemboi how did u solved it

**Comment by matthiasrohmer** [comment]
Hi everyone! This issue has been created when this project (formerly ampproject.org) has been updated from Gulp 3 to Gulp 4.

For help on how to upgrade see the various migrations guides like [this one](https://samhermes.com/posts/upgrading-from-gulp-3-to-4/). If none of them solves your problem, consider asking a new question on [StackOverflow](https://stackoverflow.com/questions/tagged/gulp) tagged with `gulp`.

The chances to get your problem solved there is a lot higher than in one of thousand issues on GitHub 🙂 Thanks!
