### ISSUE TITLE
Move ads content (both regular ads and AMPHTML ads) earlier in information architecture

### ISSUE THREAD

**Issue by gbender03** [ampproject/docs#794]
The current IA flow for AMPHTML ads content is as follows:

Who is AMP for -> AMP for Advertisers -> (scroll down to bottom to find generic 'Getting started with AMP') -> (click 'Learn more' button) -> See AMP ads page.

The current IA flow for regular ads content is as follows:

Docs -> Guides -> Serving ads on AMP

We need to make this content more accessible to a wider range of audiences to drive ads-related site visits and ultimately help publishers, advertisers, and tech platforms succeed with AMP + ads.

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/docs/pull/925 + all the ads docs that were added.
