### ISSUE TITLE
Fix AMPHTML ads side-by-side demo

### ISSUE THREAD

**Issue by gbender03** [ampproject/docs#795]
Loading the AMPHTML ads link the first time almost always fails triggering the demo. 

URL: https://www.ampproject.org/learn/who-uses-amp/amp-ads/

Screenshot of error: https://screenshot.googleplex.com/o3Y7r4uWG4z.png

**Comment by bpaduch** [comment]
Can you provide more details, as I'm unable to reproduce the issue (I've tried on my Linux desktop, my Android device, and my Mac).  

Device type: Desktop, Mobile
OS
Browser name and version

**Comment by jasti** [comment]
I tried on my end again too and everything seems to work now. I wonder if it's a caching thing where If I go back to loading the for the first time, it won't work. Anyway, closing it for now.
