### ISSUE TITLE
Click a TOC item does not add hash to URL and jumps below headline.

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#8]
To repro go to
https://www.ampproject.org/docs/guides/responsive/control_layout.html
and click one of the lower TOC items.

**Comment by miketaylr** [comment]
Possibly related to https://github.com/webcompat/web-bugs/issues/1793#issuecomment-170914657?

**Comment by cramforce** [comment]
it is definitely a bug in AMP, not in the docs.

Filed https://github.com/ampproject/amphtml/issues/1397 to fix.
