### ISSUE TITLE
Tutorials page doesn't fare well between 960 and 1060 pixel widths

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#802]
Here it is, for example, at 1024 px:

<img width="359" alt="screen shot 2018-01-11 at 7 41 02 pm" src="https://user-images.githubusercontent.com/29419498/34854383-6d84fda0-f707-11e7-9abe-57b61e78ebf2.png">

**Comment by bpaduch** [comment]
The landing pages aren't meant to be landed on anymore.  To get to the tutorials landing page, you must use the link (https://www.ampproject.org/docs/tutorials). I've set up redirects so that those landing pages are redirected to the first tutorial.

**Comment by bpaduch** [comment]
Hmm, as there's no longer a tutorials page :) , I'm going to close this one.  If you see the issue elsewhere, please report it.  Thanks!

**Comment by morsssss** [comment]
A fine reason to close it! :)
