### ISSUE TITLE
Build breaks - "TypeError: inlineStyles.trim is not a function" for update_blog_links.js

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#806]
Production cron job broke last night, and local builds breaking with the following error: 

**"TypeError: inlineStyles.trim is not a function"**

- Builds were fine yesterday
- No changes to [`ampproject/docs/scripts/update_blog_links.js`](https://github.com/ampproject/docs/blob/master/scripts/update_blog_links.js)

See https://travis-ci.org/ampproject/docs/builds/329719437

**Comment by mattludwig** [comment]
FYI - Possibly related to the latest blog post which went up early this morning:

https://amphtml.wordpress.com/2018/01/17/measuring-amp-performance/

**Comment by bpaduch** [comment]
Thanks @mattludwig, that may be it.  Will have @pbakaus investigate - he's the creator of that functionality.
