### ISSUE TITLE
Blog post is not valid AMP

### ISSUE THREAD

**Issue by mattludwig** [ampproject/docs#807]
Latest blog post is not passing the AMP validator due to the error: "CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule."

https://www.ampproject.org/latest/blog/measuring-amp-performance/

https://validator.ampproject.org/#url=https%3A%2F%2Fwww.ampproject.org%2Flatest%2Fblog%2Fmeasuring-amp-performance%2F

**Comment by mattludwig** [comment]
Another instance of this on the latest post: https://www.ampproject.org/latest/blog/amp-roadshow-more-cities-more-content/

**Comment by bpaduch** [comment]
@pbakaus - can we do anything about this? What's your recommendations?

**Comment by morsssss** [comment]
I assume that migration will that handle posts like [this one](https://www.ampproject.org/latest/blog/dynamic-geo-personalization/) too?
(@ericlindley-g , that one got a little munged in translation)

**Comment by bpaduch** [comment]
@morsssss  - that's the expectation.

**Comment by mattludwig** [comment]
Flagging the latest blog post, which has a validation error: "CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule."

https://www.ampproject.org/latest/blog/contributing-to-the-amp-project/

**Comment by matthiasrohmer** [comment]
Not current anymore.
