### ISSUE TITLE
New supported platform (CMS): Rabbit

### ISSUE THREAD

**Issue by oikwsat** [ampproject/docs#811]
Hello, we provide SaaS of AMP site construction. So, I’d like to list it on Supported Platforms.

- SaaS name is Rabbit, it is like a Relay Media <https://gomobile.jp/rabbit/> (in Japanese)
- Supported Platforms page is <https://www.ampproject.org/support/faqs/supported-platforms>

However, supported platforms has not category of AMP site construction tools now.

I think that I would like to add it to CMS category.
Do I against the guideline of supported platforms?
If it does not matter,  I would like to send a pull request.

Thanks.

**Comment by bpaduch** [comment]
@pbakaus - Can you look into this?

**Comment by pbakaus** [comment]
Thanks for the suggestion! Let's add it to CMS for now, we can branch into another category if we have more than one.

**Comment by oikwsat** [comment]
Thank you very much!
