### ISSUE TITLE
AMPHTML ads microsite update

### ISSUE THREAD

**Issue by gbender03** [ampproject/docs#817]
We sunset the "AMP Ads Initiative" brand, so we need to update copy on the [AMPHTML ads page](https://www.ampproject.org/learn/who-uses-amp/amp-ads/) from this:

"We can’t make the web better if we don’t fix ads. Today’s ads fail to meet their goals because they are slow, unpredictable and disruptive. **The open-source AMPHTML ads Initiative aims to make advertising on the web better with faster, lighter, and safer ad experiences, starting with ads and extending to landing pages.**"

to this:

"We can’t make the web better if we don’t fix ads. Today’s ads fail to meet their goals because they are slow, unpredictable and disruptive. **AMPHTML aims to make advertising on the web better with faster, lighter, and safer ad experiences, starting with ads and extending to landing pages.**"

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/docs/pull/820
