### ISSUE TITLE
Libs for Markdown -> AMP / HTML -> AMP?

### ISSUE THREAD

**Issue by kaycebasques** [ampproject/docs#833]
- Page link: https://www.ampproject.org/docs/tutorials/converting/congratulations
- Description of the documentation issue: I'm exploring how to generate AMP-based versions of my personal blog. Perusing the "convert HTML to AMP" doc set, I was surprised that there was no mention of libraries that automate this. I would expect this info at the start of the docs ("if you've got an existing site and you want to learn how to generate AMP versions of your pages, see X"), and at the end, in the "next steps". A quick search also yielded few results. The top hits for "Markdown to AMP" and "HTML to AMP" don't seem to be active projects.

**Comment by bpaduch** [comment]
@pbakaus - I'm not aware of any endorsed, free conversion libs/platforms, are you?

**Comment by pbakaus** [comment]
Nope, sadly there's not much. A few npm plugins that aren't well maintained, and a few php ones.

**Comment by kaycebasques** [comment]
If anything, consider mentioning the need for these libs at the points where I mentioned, and doing a call-to-action in the community to build these libs. It was literally the only reason I came to those docs. You might have other audience coming to those docs that are in the same boat.

**Comment by pbakaus** [comment]
@kaycebasques fair point, but we really don't want to advocate for conversion. Conversion is a messy process, and often not worth it. You don't go to React and then expect "gimme lib to convert from jQuery to React plz!" :)

As general strategy, we try to reposition our docs to be more about using AMP as library to build a website.

**Comment by kaycebasques** [comment]
But then that makes this page confusing: https://www.ampproject.org/docs/guides/discovery

Which specifically says "sometimes you want to have an AMP and non-AMP version of your page" which is what I want

(just giving feedback while this is all fresh and I still have "beginner's mind")
