### ISSUE TITLE
Update FAQ page

### ISSUE THREAD

**Issue by dandv** [ampproject/docs#86]
At https://www.ampproject.org/docs/support/faqs.html, these sections should be updated:

* Why does the Accelerated Mobile Pages Project take an open source approach
* analytics
* paywalled content

Plus generally the future tense of "How will X work" should become present - "How does X work".

**Comment by dandv** [comment]
A few more sections should be updated, e.g analytics, paywalled content; and generally the future tense of "How will X work" to present - "How does X work".

**Comment by pbakaus** [comment]
Rudy, would you be able at taking a stab at updating the contents of the FAQ page? Otherwise I'll take a stab at it, and you'll review. The FAQ is sensible content, so I want to make sure your eyes are on it.

**Comment by pbakaus** [comment]
@rudygalfi

**Comment by pbakaus** [comment]
This has been done.
