### ISSUE TITLE
AMP-IMG Scaling an image to maximum width incorrect

### ISSUE THREAD

**Issue by dalyr95** [ampproject/docs#876]
## The advice given to scale an image to maximum width is incorrect. You can't apply inline styles in AMP.
Adding inline-block to the AMP-IMG element collapes the image, I've tried this on the previews on the AMP-IMG document.

- Page link: https://www.ampproject.org/docs/reference/components/amp-img#scaling-an-image-up-to-a-maximum-width

**Comment by bpaduch** [comment]
Thanks for reporting.  This was a leftover fragment from other docs that I inadvertently left in.  Glad you found it!
