### ISSUE TITLE
AMP Stories Tutorial Walkthrough Broken

### ISSUE THREAD

**Issue by JupiterBones** [ampproject/docs#877]
When going through the AMP Stories Walkthrough using the files provided in the github zip file, the completed file cannot be clicked through as a gallery. Whenever you click on the arrow to move to the next amp page, nothing happens. This happens on the completed example file and after all of the walkthrough steps on the pets.html doc. Is there anything I could do on my end to fix this? (Did notice that there is no progress bar for page tracking)

Please provide:

- Page link: 

https://www.ampproject.org/docs/design/visual_story/setting_up

https://github.com/ampproject/docs/raw/master/tutorial_source/amp-pets-story.zip

- Description of the documentation issue:

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Open the pets-completed.html doc from the github zip link above

What browser are you using? Chrome

What O/S are you using? Mac

**Comment by bpaduch** [comment]
See the "Important" notes on the [Setting Up](https://www.ampproject.org/docs/design/visual_story/setting_up) page.

1.  Did you turn on the amp-story experiment?
2.  Are you serving it from a local server?
3.  Make sure you are serving from localhost, like http://localhost:8000/pets-completed.html.
