### ISSUE TITLE
Build broken on gulp task "generate-asset-manifest"

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#878]
**Issue Description**:

Our  "generate-asset-manifest" gulp task fails with the following error **TypeError: swBuild.getFileManifestEntries is not a function** using `getFileManifestEntries` in this [gulp task](https://github.com/ampproject/docs/blob/master/gulpfile.js#L92).  This was working on the previous build  of workbox-build (2.1.3).

* [workbox-build](https://www.npmjs.com/package/workbox-build) - released new version (3.0) yesterday.  Logged bug https://github.com/GoogleChrome/workbox/issues/1359 
* Broken on Travis and locally.  
* If use previous version of workbox-build, works correctly.

Log from [Travis build](https://api.travis-ci.org/v3/job/353156575/log.txt):

```
[03:01:48] TypeError: swBuild.getFileManifestEntries is not a function
    at Gulp.<anonymous> (/home/travis/build/ampproject/docs/gulpfile.js:93:11)
    at module.exports (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:214:10)
    at /home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:279:18
    at finish (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:134:8)
```
Reverted module to `2.1.3` in https://github.com/ampproject/docs/commit/18245baeca833e6cfc4dbf7c39aff7ca6adfc567 to avoid build break.

cc: @rsimha

**Comment by bpaduch** [comment]
@pbakaus  - Can you have a look at this.  Apparently `getFileManifestEntries` was replaced with `getManifest` (https://github.com/google/WebFundamentals/pull/5911/files).

I tried replacing the method but then got: 

```
Starting 'generate-asset-manifest'...
(node:185267) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ValidationError: "staticFileGlobs" is not a supported parameter.
(node:185267) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure how to replace the `staticFileGlobs` parameter, and I'm not familiar on promises.

**Comment by rsimha** [comment]
I too can take a look at this today.

**Comment by bpaduch** [comment]
Thanks.  It looks like `staticFileGlobs` is replaced with `globPatterns` but then I receive this error:

```
(node:195722) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: entries.forEach is not a function
(node:195722) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Further docs on the method is here - https://developers.google.com/web/tools/workbox/modules/workbox-build#getmanifest_mode

**Comment by rsimha** [comment]
@bpaduch Seems like this was fixed with https://github.com/ampproject/docs/commit/18245baeca833e6cfc4dbf7c39aff7ca6adfc567? Let me know if there's anything more to do to fix the build.

For the long term, we're on the verge of implementing a solution to automatically upgrade all our dependencies on `ampproject/amphtml`. Let me know if this will be useful for `ampproject/docs`.

**Comment by bpaduch** [comment]
It's not fixed, just a workaround by not using the latest version of workbox-build.  I'd like it to use the latest version but the code has to change.

**Comment by rsimha** [comment]
@bpaduch @pbakaus I think I have a fix for your build. It appears I lack the permissions to send you a pull request with the fixes. Can you add me to the list of contributors to `ampproject/docs`?
