### ISSUE TITLE
AMP codelab for adding advanced components for amp-ad usage is missing a step

### ISSUE THREAD

**Issue by alabiaga** [ampproject/docs#896]
1. go to 
https://www.ampproject.org/docs/fundamentals/add_advanced/adding_components
2. Note that the amp-ad usage example makes no note of adding the script required to make this component work. It is only through the dev console will the user discover that this is required. The amp-youtube example notes that error for its example and explicitly states to include the the script. The step to add the amp-ad script should be noted in one of the steps as it makes the assumption that it just works without doing so.

**Comment by bpaduch** [comment]
Thanks!

**Comment by nonproftechie** [comment]
I've submitted an edit here: https://github.com/ampproject/docs/pull/898
