### ISSUE TITLE
h1 tag is not closed at the sidebar title

### ISSUE THREAD

**Issue by beiz23** [ampproject/docs#916]
h1 tag is not closed at the sidebar title.
```
<nav class="doc-sidebar">

    <div class="current-header">
      <h1 class="title"><a href="/docs">Docs</a><h1>   <---HERE
    </div>

    <div class="current-sections">
    ...
```

- Pages: https://www.ampproject.org/docs/ and other doc pages.

**Comment by bpaduch** [comment]
Thanks.  Fixed in https://github.com/ampproject/docs/commit/b473d7b1d998d61857f17b2442154ef02ee4961e
