### ISSUE TITLE
amp-form documentation doesn't correspond with valid AMP page test

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/docs#919]
Hi,

Referring to:
https://www.ampproject.org/docs/reference/components/amp-form#custom-validations

"Interact and Submit
The interact-and-submit reporting option combines the behavior of show-all-on-submit and as-you-go. Individual fields will show any errors immediately after interactions, and on submit the form will show errors on all invalid fields."

When using interact-and-submit, when I test my AMP page to see if it is valid on https://search.google.com/test/amp

It fails the validation with:
Prohibited or invalid use of HTML Tag; The attribute 'custom-validation-reporting' in tag 'FORM [method=POST]' is set to the invalid value 'interact-and-submit'.

According to the documentation, and behavior of "interact-and-submit", it works as intended on the page, however, it would appear that above test to see if it will end up in Google's Cache, fails.

Am I missing something? Or is this a bug?

Thanks!

**Comment by bpaduch** [comment]
Looks like this was a bug in the validator that was found in https://github.com/ampproject/amphtml/issues/10773 but wasn't properly fixed, the actual fix is about to go in, in this https://github.com/ampproject/amphtml/pull/14490

**Comment by bpaduch** [comment]
Will close this bug, but if you continue to have issues, please comment on https://github.com/ampproject/amphtml/issues/10773. Thanks.
