### ISSUE TITLE
Write doc on how AMP works with PWA

### ISSUE THREAD

**Issue by Meggin** [ampproject/docs#92]
We need to document how AMP works with service worker, how AMP content can be served in PWAs, and how developers can help readers start fast with AMP and keep fast with PWA.

**Comment by stephanfowler** [comment]
We're really keen to see progress on this, speaking for the Guardian.

**Comment by pbakaus** [comment]
Finally done! Woohoo. https://www.ampproject.org/docs/guides/author-develop/pwa-amp
