### ISSUE TITLE
"integrate-your-tech@ko.md" is wrong.

### ISSUE THREAD

**Issue by shuminie** [ampproject/docs#921]
**Page :** 
https://www.ampproject.org/ko/docs/integration/integrate-your-tech

**Issue :**
docs/content/docs/integration/integrate-your-tech@ko.md

This ko.md is wrong. It was translated into japanese. (same as "integrate-your-tech@ja.md")

**Comment by bpaduch** [comment]
@coryphwang  - Can you look into this?

**Comment by coryphwang** [comment]
Submitted pull request here: https://github.com/ampproject/docs/pull/922
