### ISSUE TITLE
Relative date renders a wrong translation string

### ISSUE THREAD

**Issue by retroriff** [ampproject/docs#937]
Hello,

in Spanish amp_loop_date() renders a wrong relative date translation. The string "2 years ago" is translated:

> "2 años ago"

while it should be:

> "hace 2 años"

It is only translating "2 years".

is this a plugin bug or is it caused by my settings?

Thank you.

**Comment by bpaduch** [comment]
Are you referring to using the [`amp-timeago`](https://www.ampproject.org/docs/reference/components/amp-timeago) component?

It works correctly for me, as I get: 

>hace 2 años

Using: 

```html
 <amp-timeago height="20" 
  datetime="2016-04-11T00:37:33.809Z" 
  locale="es">Saturday 11 April 2017 00.37
</amp-timeago>
```

**Comment by bpaduch** [comment]
That product/framework is unrelated to AMPProject.org or official AMP HTML.  Please log a bug for that framework: https://github.com/ahmedkaludi/amp-theme-framework/issues
