### ISSUE TITLE
Updates docs/guides/validate.html

### ISSUE THREAD

**Issue by powdercloud** [ampproject/docs#96]
- The screenshots are from a time when we were still putting the error codes into the console, as opposed to the English messages which we have now. It may be nice to update these.
- Additional ways of running the validator exist (command line tool, web ui, and NodeJS API) - though still in beta - they're documented here: https://github.com/ampproject/amphtml/tree/master/validator
It may be worth putting a link / mention them.
Thanks much!

**Comment by pbakaus** [comment]
This is already completed, and will be live with the next deploy. Thanks for the bug report!
