### ISSUE TITLE
AMP Roadmap 2.0

### ISSUE THREAD

**Issue by jasti** [ampproject/docs#977]
### Overview 
The AMP roadmap has moved to [Github Projects](https://github.com/ampproject/amphtml/projects/43) and as part of this revamp, we want to improve the non-developer facing [roadmap](https://www.ampproject.org/roadmap) as well which will use the GitHub API to reflect the most current status of planned work. 

### GitHub Project Roadmap Management 
Every quarter, the GitHub roadmap project will be updated with "Master Features" by Product Managers or Tech Leads (incase the team doesn't have an assigned PM). These are planned features that the AMP team decides to work on over the quarter. A master feature is a high-level issue that describes the issue to a non-technical audience. Tech leads and engineers are expected to create sub-issues and link them to the master issue. Also all associated PRs must be either linked to the master issue or the sub-issue. This allows developers to drill down further and find related work.

When creating a Master Feature, the creator will:
1. add "[Master Feature]" in its name
2. add a non-technical description
3. add one or more labels starting with "category:.." that it belongs to 

#### How does the GitHub project stay up to date during the quarter? 
Using GitHub automation.
Any issue added to the 'AMP HTML Project Roadmap' GitHub project is already considered as a Master Issue. 
 - All newly added issues to this project will be automatically added to ‘Feature Backlog’
- Any new pull requests or issues against an existing issue in ‘Feature Backlog’ will move the issue to ‘In Progress’.
- Once an issue is closed, the issue is moved automatically to the ‘Done’ column. 

### New ampproject.org Roadmap

We have an opportunity to make the new roadmap simpler, more accessible to non-developers and more up to date. 

#### UX Requirements 

Use the GitHub API to render a version of the GitHub project along with some UX adjustments. 
![roadmap](https://user-images.githubusercontent.com/2366341/40944436-9b677162-6809-11e8-960c-f6b678f0a92a.png)

1. Many of the smaller UX details are up for interpretation but please leave a comment if anything is unclear!
2. Show a heading/ description describing the page and add a link back to the source Github project
3. Show a single filter that lists all of the possible values from the label 'category:..' which allows the user to filter by a single category. e.g. ads
3. Show three columns, similar to the GitHub project labelling them: Feature Backlog, In Progress, Done 
4. Render each GitHub issue as a card in the column
5. Add a heading for each issue where the heading is the GitHub issue name but without the '[Master Feature] part'. Link each card’s heading so it can be used to navigate to the Master Issue in GitHub
6. Show a fixed preview of the description by copying over the first GitHub issue comment. Ensure that all links stay intact so the user can navigate out from links within the description. 
7. Render at-most 2 categories that the master issue belongs to. (optionally indicate that there are more categories being hidden if the issue belongs to more than 2 categories)

#### Other Requirements 
1. Ensure that a similar setup works on mobile browsers as well. The grid status layout could be transferred to a sequential layout, if needed. 
2. Copy the 'Stay Informed' part over from the [old roadmap](https://www.ampproject.org/roadmap) to this new one. 

CC @pbakaus

**Comment by bpaduch** [comment]
https://www.ampproject.org/roadmap/
