### ISSUE TITLE
fix tables on mobile

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/docs#988]
![image](https://user-images.githubusercontent.com/354746/41173024-5c9a6dd2-6b0a-11e8-9440-e20e04a176da.png)

page: https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events#input-elements
cc @pbakaus @bpaduch 

can anyone look into this? if not i can ask around the core team if anyone has time

**Comment by bpaduch** [comment]
FYI - tables on our site suck, especially if there's code in them.  I'll investigate.

**Comment by bpaduch** [comment]
BTW, do many people use mobile to read dev docs?  Stats seem to indicate 78%+ use desktop.
