### ISSUE TITLE
Build fails on "Error 502"

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#992]
This error started today and I'm not sure what the problem is.  The 3 other parallel jobs worked.
```
Warning: Don't know how to categorize amp-subscriptions-google.md, skipping..
/home/travis/build/ampproject/docs/scripts/import_docs.js:32
      throw err;
      ^
Error: Error 502
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
[17:14:48] 'build' errored after 9.51 s
[17:14:48] The following tasks did not complete: optimize-images, sass
[17:14:48] Did you forget to signal async completion?
```
Log: https://travis-ci.org/ampproject/docs/jobs/390843966

I've restarted the job several times and it either just fails on the script or produces a 502 error with warnings about categorization --- which shouldn't occur.

I'm thinking it's flakiness but not sure.
Can't reproduce locally.

**Comment by bpaduch** [comment]
Reran it, and now it's this:

```
Warning: Don't know how to categorize amp-compare-slider.md, skipping..
/home/travis/build/ampproject/docs/scripts/import_docs.js:211
      for (var i = 0; i < data.length; i++) {
                               ^
TypeError: Cannot read property 'length' of undefined
    at /home/travis/build/ampproject/docs/scripts/import_docs.js:211:32
    at /home/travis/build/ampproject/docs/node_modules/octonode/lib/octonode/repo.js:521:18
    at Client
```

**Comment by bpaduch** [comment]
Flakiness issue.  Closing as build now works.

**Comment by rsimha** [comment]
I think there are some inherent failure points in `grow build` that need to be made more resilient to failures. I could take a look at them if someone can could come up with a list of failure causes and file a separate tracking issue. Or just reopen this issue and update it with a full list.

/cc @pbakaus

**Comment by pbakaus** [comment]
That was a particularly odd one, as it suggests a proper issue with categorization of a component, but apparently was an entirely different issue? Weird..

**Comment by bpaduch** [comment]
This was very odd.  It's hard to list "common" failures as it seems to be different ones each day/hour.
